### ISSUE TITLE
G6 sensory expiry alerts built in to xDrip

### ISSUE THREAD

**Issue by jamespaulley** [NightscoutFoundation/xDrip#1651] opened 2021-02-19 14:16 UTC
### Is your feature request related to a problem? Please describe.
Can we get an alert built in to xDrip for G6 sensor expiry, similar to the official G6 app.

### Describe the solution you'd like
So maybe at 24 hours we get a "sensor expiring in 24 hours" alert and at 9 hours we get another? I think there should be an option to NOT override Do Not Disturb mode for these alerts, as they are not urgent/critical, they are just for convenience.

**Comment by tolot27** [comment] 2021-02-19 14:45
Duplicate of #1467.

**Closed by tolot27** 2021-02-19 14:45 UTC
