### ISSUE TITLE
Tizen os

### ISSUE THREAD

**Issue by hannahshone** [NightscoutFoundation/xDrip#1186] opened 2020-01-18 22:44 UTC
Hi there 
I understand it's possible to view your numbers on your galaxy watch but is there any way there will be an app for xdrip on the galaxy store?we would LOVE to make our daughters watch standalone but mistakenly bought her a galaxy active 2 in the hope she could leave the phone. Is it possible to develop a tizen os version for galaxy watches? How do I initiate this? Any advice?

**Comment by tolot27** [comment] 2020-01-18 23:04
Did you have a look at #460?

**Comment by hannahshone** [comment] 2020-01-19 19:58
Hi Mathias,


Yes I did. We want it to be a collector, not communicating with phone but directly with the miaomiao using xdrip.

This solution is like mirroring the phone but not acting as collector?

**Comment by doc77** [comment] 2020-01-19 20:11
You would probably be better off spending a couple hundred dollars and just getting an xDrip+ capable Android watch.

**Comment by hannahshone** [comment] 2020-01-19 20:24
Yes the thought has crossed my mind, but surely there are many others that would like this functionality? The watch is properly waterproof, is lightweight and can receive calls etc. In NZ I'd have to buy something from china  not knowing how well it would work and with no chance of getting support if something goes wrong with it.

**Comment by doc77** [comment] 2020-01-20 02:06
I would actually consider a Bluejay watch. This is the new watch built specifically for xDrip+ by the xDrip+ developer.
https://bluejay.website/
But I certainly understand your trepidation.

**Comment by hannahshone** [comment] 2020-01-20 07:10
Is there any reason the samsung option isn't in the xdrip under settings/ smartwatch features? Would it not be possible? I realise I'm probably showing my ignorance here but just wondering?

**Comment by hannahshone** [comment] 2020-01-20 07:12
> 
> 
> I would actually consider a Bluejay watch. This is the new watch built specifically for xDrip+ by the xDrip+ developer.
> https://bluejay.website/
> But I certainly understand your trepidation.

I actually would like to support them and would be happy to donate something to this endeavour but I am hoping that my daughter could have basically a waterproof watch that works as a collector without any other phone.
I stress the waterproof part as we live on an Island and I want her to have some freedom - to go swimming safely.

**Comment by leoussis** [comment] 2020-01-28 14:51
Bluejay doesn't support Libre at the moment (at least that's what it says on the faq page)

**Comment by Diabeticliberty** [comment] 2020-02-18 11:13
I used to use a Samsung watch and found the only way of getting the thing to display Xdrip+ was by using an app called Wearable Widgets which I had to download from a company by the name of Udell. The application only provided very limited functionality for Xdrip+ and the readings displayed on the watch were sometimes out of date by as much as 15 minutes. It was a real pity as the Samsung watches are fantastic and have very good battery life. It is however extremely unfortunate that the available software really lets them down. In the end I gave the watch away and bought one running Wear OS. The difference is huge in terms of having Xdrip+ on my wrist which is what I really want and not a watch that tells me I am doing a dynamic workout when I am actually driving to work in a morning which is something that my Samsung watch frequently did as its sensors seemed to get a little bit confused at times.

**Comment by Navid200** [comment] 2021-02-27 16:12
@hannahshone Would you please close this issue if it has been resolved?
If not, would you please consult with the user community first?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

Please only open an issue here if you have already confirmed that there is a bug or you are requesting a feature that has no work-around and there isn't already an open issue about it.

Thanks

**Comment by tolot27** [comment] 2021-02-27 22:31
> Bluejay doesn't support Libre at the moment (at least that's what it says on the faq page)

@leoussis Bluejay will never support Libre because this is not possible.

**Comment by Navid200** [comment] 2021-03-27 03:52
Closing due to inactivity

**Closed by Navid200** 2021-03-27 03:52 UTC
