### ISSUE TITLE
How to delete a calibration from follower?

### ISSUE THREAD

**Issue by Pikernot** [NightscoutFoundation/xDrip#955] opened 2019-07-16 21:37 UTC
When I delete a calibration from the calibration data table using master (#624), the deletion works correctly. But when I do the same using follower, the calibration record turns red but the slope and intercept do not become 0 and the calibration is not deleted from calibration graph on master.

**Comment by Navid200** [comment] 2021-03-04 15:16
@Pikernot Is this still the case with recent releases of xDrip?

**Comment by tolot27** [comment] 2021-03-04 15:22
This is a duplicate of #114.

**Closed by tolot27** 2021-03-04 15:22 UTC
