### ISSUE TITLE
Feature request in queued commands

### ISSUE THREAD

**Issue by Kaivish** [NightscoutFoundation/xDrip#1223] opened 2020-02-04 08:30 UTC
Is there a way to clear the queued commands from status? Like queued calibrations or queued stop sensor etc. Sometimes there is a need to stop it from sending these commands to the g6 tranmitter. But the problem is tgat it stays in the queue and there is no way to delete/remove commands from queue

**Comment by tolot27** [comment] 2020-10-25 14:54
Duplicate of #1118.

**Closed by tolot27** 2020-10-25 14:54 UTC
Labels: device-dexcom, duplicate, enhancement
