### ISSUE TITLE
Nightscout treatments are not downloaded

### ISSUE THREAD

**Issue by malloy139** [NightscoutFoundation/xDrip#1231] opened 2020-02-06 15:50 UTC
Treatments entered in XDrip are shown on the master and in the Webinterface, but not on the Noghtscout Follower. "Download Treatments" is turned on.
But when a treatment is entered in the Webinterface is shows up on the follower, as can be seen in the attached image.
![nightscout](https://user-images.githubusercontent.com/41596803/73953484-c1e41780-4900-11ea-94ea-27947cb99670.png)
![xdrip follower](https://user-images.githubusercontent.com/41596803/73953488-c27cae00-4900-11ea-9b1a-f78256f35363.png)

**Comment by misiek2lucky** [comment] 2020-02-09 10:06
I pin up. On stable and nightly the same.

**Comment by GPLExpert** [comment] 2020-03-22 12:08
Same for me here

> Treatments entered in XDrip are shown on the master and in the Webinterface, but not on the Noghtscout Follower

**Comment by malloy139** [comment] 2020-05-30 21:49
It is still not working.
This seems to be the only way (if it would work) to distribute treatments for people with phones that have no play services installed and can't use the sync featue.

**Comment by GPLExpert** [comment] 2020-05-31 08:48
Hello,
Yes if someone can help debugging ?
I can give all informations if needed
Thanks

**Comment by rocketman10404** [comment] 2020-06-02 19:32
Having the same issue on several phones running XDrip

**Comment by rocketman10404** [comment] 2020-06-02 21:07
From my brief and uneducated quick scan of Treatments.java, it does indeed appear as though the "Entered By" record is taken from a hard-coded constant (XDRIP_TAG) that currently cannot be changed in the app.

Also, looking at NightscoutTreatments.java (and this is my best interpretation as a hobbyist's first look) - at line 133, it looks like a check on new treatments to only process non-existing (i.e. new) treatments not coming from xdrip (i.e. "Entered By" is not "xdrip").  There's a else condition block to catch changes for pre-existing treatments whether or not they come from xdrip, but there does NOT look to be any code to process new treatments that come from xdrip.  Seems to me like this is the root cause of the issue we're describing.

I'd suggest possibly adding a configurable setting to allow user control over the XDRIP_TAG contents, but have no idea what other negative effects this may have elsewhere.  It may be easier to avoid downloading/uploading duplicates if all XDrip users syncing to a Nightscout instance could have treatments uniquely identified via the XDRIP_TAG.

Alternatively, perhaps non-existing treatments could be process whether or not they came from xdrip?

Lastly - this may be a duplicate of #1196.  Possibly related to #735, but maybe not.

**Comment by tolot27** [comment] 2020-08-14 21:42
This is a duplicate of #1196. The problem reported with #735 is that treatments entered by followers are not uploaded to nightscout.

@jamorham Please can you close this issue?

**Comment by Navid200** [comment] 2021-03-27 19:02
Please add your comments to the existing issue: https://github.com/NightscoutFoundation/xDrip/issues/1196

**Closed by Navid200** 2021-03-27 19:02 UTC
Labels: bug, duplicate, sync-nightscout

**Comment by Navid200** [comment] 2024-02-24 13:49
As of the release on February 24, 2024, there is a new switch in the "Upload Treatments" submenu titled "Skip items from xDrip" enabled by default.
If you disable this switch, treatments uploaded by another xDrip will also be downloaded.

Please tell us if you experience any issues or have any questions.
