### ISSUE TITLE
Feature Request: Notification Channel Importance

### ISSUE THREAD

**Issue by dbnsacc** [NightscoutFoundation/xDrip#999] opened 2019-09-05 11:31 UTC
I'm wondering if there is a way to add a setting so that we can set the xDrip+ notification channel which displays the number icon etc. to high priority. Prior to Android 9.0 I believe this was a change that could be made in the settings to the channel but it's no longer there. I think this has to be configured per notification channel as the Importance setting since Android 8.0.

I use the Always On display on my Pixel so that the current reading is there. Sometimes if I get a few notifications come through the xDrip+ number can get pushed off the edge and replaced by a dot to signify there are many notifications in the tray. I'd like to keep the notification for xDrip+ on the top at all times if possible.

**Comment by Navid200** [comment] 2021-02-18 17:40
@dbnsacc Would you please update?
Is the problem still present?

**Comment by dbnsacc** [comment] 2021-02-18 17:47
Hi @Navid200, yes this is still an issue through to Android 11. Without the ability to set a notification channel to high priority then it is still susceptible to being pushed off the always on display when a few other notifications from emails etc. come in.

**Comment by Navid200** [comment] 2021-02-18 18:02
Is this something that can be fixed by xDrip?
Shouldn't the priority between different apps be set in Android?

What if we raise the priority in xDrip and so does everyone else in every other app?  How is that going to change anything?

**Comment by tolot27** [comment] 2021-02-26 23:39
Duplicate of #1503.

**Closed by tolot27** 2021-02-26 23:39 UTC

**Comment by Navid200** [comment] 2021-02-26 23:52
Shouldn't we close the newer issue and maintain the older one to encourage people to not open duplicate issues?
It may also serve the community better to show the developers that the issue in fact has been waiting a longer time.
If we close the older issue, we remove part of the history.

**Comment by tolot27** [comment] 2021-02-27 21:45
Indeed, but this is only relevant for newly created issues and not such an old issue which was not addressed, unfortunately.

**Comment by Navid200** [comment] 2021-02-27 21:52
I had completely overlooked that both issues had been opened by the same person.  Thanks for pointing that out.
