### ISSUE TITLE
LibreLink App 2.4

### ISSUE THREAD

**Issue by arsinn** [NightscoutFoundation/xDrip#1237] opened 2020-02-14 11:46 UTC
Hi,
with the update of LibreLink App to 2.4 Abbott says it is much more precise, especially for low BGs. Is xdrip working with this new version? Does it make sense to change something now? What do I have to do now?

Im am using xdrip+ 6d4d283-2019.10.27

Thanks for your help!
Best,
Arne

**Comment by MasterPlexus** [comment] 2020-02-14 11:59
@arsinn this has nothing to do with xDrip, but with the LibreLink app itself. The problem is, that the new app needs to be patched, but this is hardly liunked to a specific version of LibreLink.

So under the line, it is need to find someone, who can adopt the patches to the new version of LibreLink. For the moment I see nobody who will do that, as the old version is working properly, and  the values will be filtered anyway. I would like to say, that I don't think that the exctration method will change the preceicity between old and new version of LibreLink to xDrip.

**Comment by arsinn** [comment] 2020-02-14 12:06
Hi MasterPlexus,
thanks for the instant reply! good to know it would not bring any advantage.

**Comment by utzaki** [comment] 2020-02-17 14:44
Hi MasterPlexus, as far I understood the new LibreLink app version modified the algorithm to calculate the final values. I assume they just reduced a safety reduction for low values which resulted in a quite high discrepancy compared to blood measures. As the final values are extracted by the patch and transferred to xDrip I doubt your last remark. Nevertheless, I totally agree that this is not an xDrip issue.

**Comment by MasterPlexus** [comment] 2020-02-17 15:14
@utzaki , from my experiance, what will be distributed to xDrip+ is more a Raw-Value every minute (just only filtered against internal Calibration and Temperature adjustment). I'm preaty sure Abbott just only changed the afterprocessing Algorithem to calculate the prospected Shuger value. On that hand, I also think, as you said, that they reduce the safety-level in calculation. Anyway, as this comes (as fahr as I know) after the raw-starrage, the values for xDrip will not really change... But to be sure, it is needed to made an heavy comparison between values of old and new Librelink. At the moment this will noct be possible I fear...

**Comment by tzachi-dar** [comment] 2020-02-18 09:56
Can anyone compare readings from the old version and the new version?
It is interesting to note if there a significant diff.

**Comment by utzaki** [comment] 2020-02-18 11:10
Yes, I can scan with the old (patched) version with one mobile and to the same time new version with another mobile. In general, for higher values (130) the new version is about 5 mg/dl lower, for lower values the new version is about 20 mg/dl lower.

**Comment by steve8x8** [comment] 2020-02-18 13:43
With 2.3.0, I'm already 20 mg/dL lower than finger pricks. What if they add another 20 mg/dL difference??? (I already had to disable low alerts.)

**Comment by utzaki** [comment] 2020-02-18 14:09
For me, it is the opposite. Blood is 50-60 higher than the sensor (old app version) in most cases. So for me, the new algorithm seems to be an improvement.

Maybe it is not just adding a difference but also using other criteria like noise, temperature or any other parameter which may influence the algorithm. Only Abbott knows and everyone must check that for himself and his personal situation.

**Comment by universe27** [comment] 2020-07-04 09:02
There are relevant differences between the 2.3 and 2.4 apks ... Is it possible to patch the 2.4 version? In my case is more accurate the 2.4 version, so it would be perfect to make the patched sol from the 2.4

**Comment by Supremecelo** [comment] 2020-11-09 18:36
I tried to patch mine but I got stucked in the GIT patch. Can someone help me? or also just send the patched apk...

**Comment by Navid200** [comment] 2021-03-02 03:33
Closing due to inactivity

**Closed by Navid200** 2021-03-02 03:33 UTC
