### ISSUE TITLE
xDrip+ stop pairing, won't send pair request, when using Fitbit versa lite

### ISSUE THREAD

**Issue by k10xdrip** [NightscoutFoundation/xDrip#1789] opened 2021-07-23 20:40 UTC
### Subject of the issue
Navid asked me to submit this bug report. First time using github, so please let me know if you need other/ more/ different information.
Issue: xDrip+ will stop un-pair from my transmitter. I suspect the issue is caused by my fitbit watch, as when I delete fitbit app from my phone, the xdrip issues resolve. 

### Your environment
- What version of xDrip: 2103312148, 2021.03.31
- What type of hardware data source and how do you get your data there: dexcom G6
- Is your issue specific to a device like and Android phone or a smartwatch? Moto G Power (2020) running Android 11 and Fitbit Versa Lita 
- All settings related to the issue, e.g. activated auto calibration. I am not sure what is relevant here...? All settings have been verified by Navid while troubleshooting.

### Expected behavior
I would like to be able to run my fitbit versa lite watch and xdrip concurrently. I have been using them both without issue for over a year. This problem has been happening off and on for the last 4 months.

### Actual behavior
When I restart phone, restart collector via xDrip, the log says pair request sent, but I never receive a request via xdrip on my phone. The only thing that seems to resolve this is uninstalling my fitbit application from my phone (paired via bluetooth with Versa Lite, using glance to see xdrip status and receive xdrip alerts). I stopped using fibit for weeks with no issue with xDrip. 4-5 days after re-stalling fitbit/ connecting my watch, the issue returned, and was solved again by removing the fitbit app from my phone.

### Steps to reproduce the behavior:
1. xDrip transmitter drops connection
2. restart collector
3. wait 5 minutes... nothing happens
4. check events log: see "prompting user to notice pairing request with sound.." but no pairing request was sent via xdrip/android notifications
5. try steps 2-4 several times
6. un-install fitbit from phone
7. restart xdrip collector
8. wait 5 minutes
9. pairing request notification received. Accept pair. xDrip works normally.
<img width="350" src="https://user-images.githubusercontent.com/87878432/126839187-cee66454-0502-4337-a847-995c902b2e10.png" /> <img width="350" src="https://user-images.githubusercontent.com/87878432/126839195-3353d7ba-7a57-41e5-89b9-9c36fdcf9fb8.png" /> <img width="350" src="https://user-images.githubusercontent.com/87878432/126839198-7a8020f5-1256-4496-820f-b4f684bf63bc.png" /> <img width="350" src="https://user-images.githubusercontent.com/87878432/126839202-c539e870-31ba-47ae-bbe7-19d4bc0036af.png" />

**Comment by parapenT1sta** [comment] 2021-07-24 16:57
Did you try to use the latest xDrip Nightly version?

**Comment by k10xdrip** [comment] 2021-08-01 19:01
@parapenT1sta We just tried the 8.1.21 version and it wouldn't work at all (no BG readings), so then we tried the 7.17.21 version. I will install fitbit now and see if/when it causes the issue. Will report back. It usually takes 3-5 days.
![Screenshot_20210801-115439](https://user-images.githubusercontent.com/87878432/127782372-83a204f9-3f8f-4829-8b70-0038a31160be.png)
![Screenshot_20210801-115450](https://user-images.githubusercontent.com/87878432/127782373-8248e4fb-2b4c-4be4-aaf0-ede3aea06ce0.png)

**Comment by Navid200** [comment] 2021-08-02 13:09
@k10xdrip Please don't use the August 1, 2021 release.
https://www.facebook.com/groups/xDripG5/posts/5803321493074631/
![Screenshot 2021-08-02 090653](https://user-images.githubusercontent.com/51497406/127866876-f28f9c3e-ef37-4584-b8d4-b1c2b9635ade.png)

When you like to upload an image, please reduce the size of the image as much as you can, before uploading, just to leave enough detail visible, to make reading easier.

**Comment by DjinnGallagher** [comment] 2021-08-02 16:14
Subject of the issue
I have a similar issue with my Fossil Sport watch (I've used k10xdrip's report as a template!). 

Issue: xDrip unpairs from my Dexcom G6 transmitter. I suspect the issue is caused by my Fossil watch, as when I unpaired my watch, xdrip reconnected immediately

Your environment
What version of xDrip: 2103081944, 2021.03.08
What type of hardware data source and how do you get your data there: Dexcom G6
Is your issue specific to a device like an Android phone or a smartwatch? Samsung Galaxy S10e running Android 11, and Fossil Sport
All settings related to the issue, e.g. activated auto calibration. All settings have been verified by Navid while troubleshooting.
Expected behavior
I would like to be able to run my Fossil watch and xdrip concurrently. I had them both for 18 months on my Samsung S8, using Android 9 without any problems. I bought a Samsung S10e with Android 11 three weeks ago and now have this ongoing problem

Actual behavior
My new phone loses Bluetooth connection with xdrip three or four times every day. I press "restart collector" but it doesn't connect. It recovers when I delete the xdrip cache and "forget device", then xdrip sends me a "pair request", at which point it begins to work again. Sometimes this doesn't work until I go through the sequence several times. Navid suggested disabling the 
 -> Allow OB1 unbonding in my Settings, but it's still happening. I'm looping with AAPS so losing the xdrip connection is problematic. The last time it happened, Navid encouraged me to unpair my watch, and xdrip found the connection with my Dexcom immediately.

**Comment by k10xdrip** [comment] 2021-08-04 19:18
@parapenT1sta @Navid200 After switching to 7.17.21, tried with the fitbit and it only lasted about 36 hours. Unpaired fitbit via bluetooth, had to restart my phone and then xdrip+ starting working again. Dexcom branded receiver was getting readings the whole time. See screenshots.
![Screenshot_20210803-051235](https://user-images.githubusercontent.com/87878432/128241540-73c2f970-ebad-4851-9578-73dcf7e2816b.png)
![Screenshot_20210803-051726](https://user-images.githubusercontent.com/87878432/128241560-fa527c83-7f0f-4c87-970f-6e0fd20a9465.png)
![Screenshot_20210803-051731](https://user-images.githubusercontent.com/87878432/128241575-f8a9f934-a01f-42ac-8e2d-21d21ceef466.png)
![Screenshot_20210803-090357](https://user-images.githubusercontent.com/87878432/128241579-69057208-b7b7-465b-9e6c-9f597b30116e.png)

**Comment by bionictom** [comment] 2021-08-12 12:16
I also had this problem with my G5.

Tried to start a new sensor, but xdrip was stuck at "Receiving Data from DexcomG5 Collector". With "No Data received".

I tried rebooting the phone and toggling bluetooth but nothing helped. I also have prompting user to notice pairing request with sound.." 

Navid suggested I disable the smartwatch (Ticwatch pro) which I did, then rebootet the phone, toggled bluetooth and then I got the pairing request, now everything is working. I'm leaving the watch turned off for now.

Xdrip Version: 210702815
Smartwatch: Ticwatch Pro
My xdrip settings are according to this guide: https://github.com/Navid200/xDrip/wiki/G5-Recommended-Settings


![grafik](https://user-images.githubusercontent.com/28786121/129194862-1b63fe49-ae7c-47c7-a719-76e9e33843b6.png)

**Comment by tolot27** [comment] 2021-08-13 05:24
A few questions:
1. Does it work with some previous version of xDrip while Fitbit is connected / Fitbit app is installed?
2. Does it work with the Dexcom App (xDrip completely disabled)?

**Comment by jamorham** [comment] 2021-08-14 09:53
This sounds like an issue in the Fitbit app. There used to be things that could be done regarding intercepting pairing which then got broken by google changing how the pairing works on many versions of android with a security update. Its possible that the fitbit app still does this and doesn't correctly pass on the intercepted pairing request if it isn't for it. That's just a hunch but if someone links the exact app I can take a look and see if it looks likely that is what is happening.

**Comment by bionictom** [comment] 2021-08-14 10:57
The problem I had might be similar to the Op, but I don't use Fitbit, I use a To watch pro with Android wear, no dedicated app on my phone

**Comment by k10xdrip** [comment] 2021-08-19 04:47
@tolot27 Hi, to answer your questions: 1. It did work fine for awhile, maybe a year or so. Then this issue started up, but that also coincided with having to replace my phone. 2. my phone is not compatible with the dexcom app, so I don't know. I do use the dexcom receiver sometimes and that has no issues working when I use it, even when xdrip seems to be failing. 

The biggest issue is that now I don't even get the alert/ notification/ prompt to re-pair the transmitter. Before I at least used to get the re-pair prompt immediately (over and over and over, which is a different issue). But now, I have to keep re-starting my phone/ restart collector 2-10x to get a prompt to pair. It's very time consuming. Also, I have noticed this issue persists even without the fitbit app on my phone, so I don't think it's related to the fitbit app. I have stopped using the fitbit app completely and I have still experienced the no prompt to pair issue, although luckily now that I stop trying to make the fitbit work, I don't need to re-pair very often.

So I guess there are two issues. 1. something about the fitbit app causes xdrip to unpair 2. when xdrip does get un-paired, I don't automatically get the prompt to re-pair without trying many times to force it. 

Side-note: I assume there is no way to easily re-pair the transmitter without getting the prompt/ notification?

**Comment by k10xdrip** [comment] 2021-08-23 23:52
Now the issue is happening without any interference from fitbit app (has not been installed on my phone since I opened this ticket). See logs. I tried restarting collector and restarting my phone several times. No signal for 84 minutes. 
![Screenshot_20210823-160439](https://user-images.githubusercontent.com/87878432/130533951-6f41b941-b8e8-4501-98c7-a2dfdfca60ec.png)
![Screenshot_20210823-164258](https://user-images.githubusercontent.com/87878432/130533954-3ea08dba-4b19-44c4-bb74-3f56d832075b.png)

**Comment by k10xdrip** [comment] 2021-10-02 02:24
update: so I have not paired fitbit with my phone in several months now. I do have xdrip unpairing from my dexcom transmitter daily, or almost daily now. Restarting my phone usually fixes it. Is there a newer nightly build I should try now that it's been a few months or is the July 17 one still the best one?

**Comment by Navid200** [comment] 2021-10-02 02:50
@k10xdrip You are already using a Nightly version.  You have nothing to lose by switching to another, more recent.    

Is adaptive battery disabled on your Moto G?
It's under Settings -> Battery

**Comment by k10xdrip** [comment] 2022-06-10 23:50
Thanks. I just updated. I'll let you know how things go.

**Comment by Navid200** [comment] 2023-01-09 02:16
@k10xdrip What is the status?

**Comment by k10xdrip** [comment] 2023-01-09 19:50
xdrip still does disconnect occasionally, but not hourly/daily like it was
before. Now I'd say it's 1-2x weekly. I stopped trying to use it with my
fitbit since I was pregnant and needed reliable dexcom service, but can try
again now since baby is out!

**Comment by Navid200** [comment] 2023-01-09 19:57
We need to keep updating xDrip to keep it operational for most phones as new phones come to market and as Android gets updated.
This is an ongoing process.

This issue was rather about the interference caused by fitbit.  And it looks like that is something to do with the fitbit app and not xDrip.

I am going to close this issue.  Not because xDrip is perfect.  But, because I don't think we can change anything in xDrip to address any misbehavior caused by fitbit.
And we can reopen this issue if needed.

As far as the intermittent connectivity of xDrip itself with a G6 transmitter goes, please use the discussions (https://github.com/NightscoutFoundation/xDrip/discussions) if you need help.

Thanks

**Closed by Navid200** 2023-01-09 19:57 UTC
Labels: device-dexcom, bluetooth, device-wear
