### ISSUE TITLE
Dexcom G5: Scan Error: Unable to Start scanning (Pixel 4a 5G with Android 12 / S Preview)

### ISSUE THREAD

**Issue by parapenT1sta** [NightscoutFoundation/xDrip#1720] opened 2021-05-09 15:51 UTC
**xDrip Nightly build 5th May 2021**
**Dexcom G5 receiver**
**Mobile:** Google Pixel 4a 5G
**Android Version**: S (12 Preview) build bramble-spp3.210325.010-factory-b282d767

**Issue:** Scan Error: Unable to start scanning
**Error log:**
```
Unable to Start Scanning
com.polidea.rxandroidble2.exceptions.BleScanException: Bluetooth Cannot Start (code 0)
No transmitter mac address!
```

Dexcom G5 works perfectly fine with Dexcom Official App and also working fine with MiaoMiao 2 / Bubble 1 & Mini.
With xDrip+ the scanning is not even starting/working.  

![image](https://user-images.githubusercontent.com/608650/117578480-6ea1db80-b0e6-11eb-9eec-6921043802c7.png)

![image](https://user-images.githubusercontent.com/608650/117578552-d5bf9000-b0e6-11eb-827a-8a5cf80dde0a.png)

![image](https://user-images.githubusercontent.com/608650/117580239-00154b80-b0ef-11eb-9169-48306bd62dd5.png)

**Comment by tolot27** [comment] 2021-05-16 18:52
Please enable verbose logging for Ob1G5CollectionService.

**Comment by parapenT1sta** [comment] 2021-05-16 19:04
@tolot27 I will try it on the next time I update to Android 12.

**Comment by Smip** [comment] 2021-05-19 19:44
@parapenT1sta did you solve the problem? I have pixel 4 and after I updated the system have a problem like you.

**Comment by parapenT1sta** [comment] 2021-05-19 19:49
@Smip I downgraded from Android 12 to 11 and problem solved.

**Comment by Smip** [comment] 2021-05-19 21:19
@tolot27 
![photo_2021-05-19_22-59-07](https://user-images.githubusercontent.com/11481452/118883944-22c91080-b8f6-11eb-84eb-60002e985625.jpg)

**Comment by tolot27** [comment] 2021-05-19 21:27
Looks like either a permission problem or a new security layer. Did xDrip ever ask to bond the transmitter? I assume it is not bonded, yet.

**Comment by Smip** [comment] 2021-05-19 21:38
Probably xDrip didn't ask to bond. I used this transmitter with Android 11 and everything was good. After updating, xDrip worked for a while and after some time I got this error. I tried to change a lot of different settings and nothing helps. The last thing I tried is to reinstall the application. After installation of the app, I didn't see a bond request.

**Comment by tolot27** [comment] 2021-05-19 21:41
@Smip 

> I have pixel 4 and after I updated the system have a problem like you.

You did not mention if you have also upgraded to a preview version. If you did, it is a waste of time discussing unreleased Android versions which likely still have some bugs.

**Comment by parapenT1sta** [comment] 2021-05-19 21:44
@tolot27 Android 12 is now at a beta stage: https://www.google.com/android/beta

**Comment by Smip** [comment] 2021-05-19 21:46
I updated to the beta version 
![photo_2021-05-19_23-43-57](https://user-images.githubusercontent.com/11481452/118888779-61fa6000-b8fc-11eb-9446-e04ee8a50ed2.jpg)

**Comment by tolot27** [comment] 2021-05-19 22:40
A beta version is still an unreleased version which likely contains bugs. We don't have the time to support unreleased versions. If you believe this problem will persist in the final release and if you like to support us, please try to find out whether the Bluetooth stack has changed fundamentally.

As far as I remember, a new Bluetooth stack named "Gabeldorche" was introduced with Android 11 which can be enabled. Maybe, this stack is now the default stack in Android 12? If yes, please investigate if it can be disabled or if the problem is reproducible in Android 11 if Gabeldorche is enabled.
That's currently the only suggestions I have.

**Comment by Smip** [comment] 2021-05-19 23:09
I found this stack in the developer options list and it's disabled by default. I tried to enable it and nothing changed. So probably the reason is different.

I remember a few months ago I have a problem when Android aks to bond every 5 minutes and if I didn't click "bond" I have very similar behavior. How I know, there was some patch to fix this problem. How can I manually bond a transmitter?

**Comment by tolot27** [comment] 2021-05-19 23:12
I've found the reason. As assumed before, it is a permission problem. A12 introduced two new runtime permissions: [New Bluetooth permissions in Android 12](https://developer.android.com/about/versions/12/features/bluetooth-permissions). As soon as we declare this permissions in the manifest, it should work.
I'll provide a PR soon.

**Comment by parapenT1sta** [comment] 2021-05-19 23:14
> I've found the reason. As assumed before, it is a permission problem. A12 introduced two new runtime permissions: [New Bluetooth permissions in Android 12](https://developer.android.com/about/versions/12/features/bluetooth-permissions). As soon as we declare this permissions in the manifest, it should work.
> I'll provide a PR soon.

What great news! :)

**Comment by tolot27** [comment] 2021-05-19 23:43
@parapenT1sta Are you able to build you own apk?

**Comment by parapenT1sta** [comment] 2021-05-20 05:51
> @parapenT1sta Are you able to build you own apk?

I can try to build it and will let you know.

**Comment by taylorfowler** [comment] 2021-05-20 12:02
> > @parapenT1sta Are you able to build you own apk?
> 
> I can try to build it and will let you know.

If either of you could share that apk if you build it, that would be swell. Getting a ton of gradle errors when i try to build your branch (Android studio is to blame, not the branch, almost certainly).

**Comment by parapenT1sta** [comment] 2021-05-20 21:12
> > > @parapenT1sta Are you able to build you own apk?
> > 
> > 
> > I can try to build it and will let you know.
> 
> If either of you could share that apk if you build it, that would be swell. Getting a ton of gradle errors when i try to build your branch (Android studio is to blame, not the branch, almost certainly).
> 
> Edit: got it to build properly.
> 
> Now getting
> 
> > Unable to start scan com.polidea.rxandroidble2. exceptions.BleScanException: Bluetooth cannot start (code 0)

For some reason I am getting this error while compiling the apk:
```
Execution failed for task ':wear:compileFastDebugJavaWithJavac'.
> javax/xml/bind/JAXBException
```

The messsage you are getting is the same I was getting before. Did you check to remove all permissions and then enabling them after?

**Comment by tolot27** [comment] 2021-05-20 22:25
> If either of you could share that apk if you build it, that would be swell. Getting a ton of gradle errors when i try to build your branch (Android studio is to blame, not the branch, almost certainly).

You can get my preview build at https://github.com/tolot27/xDrip/releases/tag/Android12BTPermissions_v0.1.

**Comment by Smip** [comment] 2021-05-23 11:09
@tolot27 I tried your version and nothing changed. Android asked for a "Nearby devices" permission but the error is still there.
![photo_2021-05-23_13-08-29](https://user-images.githubusercontent.com/11481452/119257968-fcda8f00-bbc7-11eb-9315-4c21dfe03b44.jpg)
![photo_2021-05-23_13-08-31](https://user-images.githubusercontent.com/11481452/119257969-fd732580-bbc7-11eb-96c3-1e83fc6b619f.jpg)

**Comment by parapenT1sta** [comment] 2021-05-23 22:26
@Smip Can you check how do you have it on BT Device tab in System Status.

**Comment by Smip** [comment] 2021-05-24 06:57
@tolot27 Sure

![Screenshot_20210524-085639.png](https://user-images.githubusercontent.com/11481452/119308968-fbfc3880-bc6d-11eb-811f-864b3fba4632.png)

**Comment by parapenT1sta** [comment] 2021-05-24 10:28
@Smip Exactly what I was getting :-(

**Comment by Smip** [comment] 2021-05-29 15:37
probably the solution is to wait for update the RxAndroidBle library due to issue https://github.com/Polidea/RxAndroidBle/issues/752

**Comment by parapenT1sta** [comment] 2021-06-12 07:58
> probably the solution is to wait for update the RxAndroidBle library due to issue [Polidea/RxAndroidBle#752](https://github.com/Polidea/RxAndroidBle/issues/752)

The newest version of xDrip already has it. Do you want to try it?

**Comment by parapenT1sta** [comment] 2021-06-12 08:01
> probably the solution is to wait for update the RxAndroidBle library due to issue [Polidea/RxAndroidBle#752](https://github.com/Polidea/RxAndroidBle/issues/752)

The newest version of xDrip includes this commit: https://github.com/NightscoutFoundation/xDrip/pull/1723

Are you able to check if solve the issue?

**Comment by Smip** [comment] 2021-06-12 08:21
> > probably the solution is to wait for update the RxAndroidBle library due to issue [Polidea/RxAndroidBle#752](https://github.com/Polidea/RxAndroidBle/issues/752)
> 
> The newest version of xDrip includes this commit: #1723
> 
> Are you able to check if solve the issue?

I updated Android to beta 2 and luckily it works. I'm not sure that the new version of xDrip helped, but I keep testing.

**Comment by parapenT1sta** [comment] 2021-06-12 08:23
@Smip Can you keep me posted?

**Comment by parapenT1sta** [comment] 2021-06-17 18:30
> > > probably the solution is to wait for update the RxAndroidBle library due to issue [Polidea/RxAndroidBle#752](https://github.com/Polidea/RxAndroidBle/issues/752)
> > 
> > 
> > The newest version of xDrip includes this commit: #1723
> > Are you able to check if solve the issue?
> 
> I updated Android to beta 2 and luckily it works. I'm not sure that the new version of xDrip helped, but I keep testing.

How is it working? Should I leave this topic open or should I close it?

**Comment by Smip** [comment] 2021-06-18 08:40
> > > > probably the solution is to wait for update the RxAndroidBle library due to issue [Polidea/RxAndroidBle#752](https://github.com/Polidea/RxAndroidBle/issues/752)
> > > 
> > > 
> > > The newest version of xDrip includes this commit: #1723
> > > Are you able to check if solve the issue?
> > 
> > 
> > I updated Android to beta 2 and luckily it works. I'm not sure that the new version of xDrip helped, but I keep testing.
> 
> How is it working? Should I leave this topic open or should I close it?

1 week without problems. Probably you can close the issue. If I find a bug I'll reopen the issue. Thanks

**Closed** 2021-06-18 08:46 UTC
Labels: bluetooth, breaking, bug

**Comment by tolot27** [comment] 2021-06-18 08:49
Does it work without applying #1734?

**Comment by parapenT1sta** [comment] 2021-06-18 08:58
@Smip Thank you for your feedback. I am now installing Android 12 beta to try it, I had quite Android 12 when xDrip stopped working.

**Comment by parapenT1sta** [comment] 2021-06-18 09:41
> Does it work without applying #1734?

I installed Android 12 Beta 2 and the latest xDrip works perfectly fine.  I think https://github.com/NightscoutFoundation/xDrip/pull/1723 solved the issue.

**Comment by tolot27** [comment] 2021-06-18 09:59
And were you asked for the additional permissions?

**Comment by parapenT1sta** [comment] 2021-06-18 10:20
I don't remember given permission but I verify that "Nearby Devices" is allowed and was accessed on the last 24 hours.

![image](https://user-images.githubusercontent.com/608650/122546756-3071d300-d027-11eb-9ae6-b7c3e0e1f1ab.png)
