### ISSUE TITLE
Upload basal rates to Tidepool

### ISSUE THREAD

**Issue by akhilshah128** [NightscoutFoundation/xDrip#1877] opened 2021-11-14 14:36 UTC
Hi all

I think this has been raised before but I wondered if it was any closer to happening?

This was response I got from Tidepool 

**Hi Akhil,

Thanks for your message and for reaching out to Tidepool.

xDrip+ uses a community-written integration for Tidepool Web, and as such we do not have influence on what data is being sent from the app. I have heard from others that basal is not sent to Tidepool, which is a bummer. I would raise an issue on the xDrip+ GitHub project page and ask if they can add support for this - https://github.com/NightscoutFoundation/xDrip/issues

Let us know if you have any other questions.**

Thanks in advance

**Comment by tolot27** [comment] 2021-11-14 15:29
Duplicate of #1477

**Comment by tolot27** [comment] 2021-11-14 15:30
Please always use the search function as it is mentioned in the issue template!

**Closed by tolot27** 2021-11-14 15:29 UTC
Labels: duplicate
