### ISSUE TITLE
nightscout follower delayed by 5 to 10 min.

### ISSUE THREAD

**Issue by Kaivish** [NightscoutFoundation/xDrip#929] opened 2019-06-23 23:22 UTC
using xdrip to follow my kids bg. prefer xdrip as follower app because of the prediction display. but the bg data gets delayed by 5 to 10 min. have to restart collector everytime. and gettin error like 'nightscout follower.  woke up early'. is there a way to get xdrip to ping nightscout site si it gets latest bg value always?

**Comment by ahaarrestad** [comment] 2019-07-05 20:58
@Kaivish I have just got my pull-request accepted. Next nightly will contain a status page to see when the data is pulled, how old the readings were etc. 

I am looking further into this issue and will probably add more pull requests to further improve this feature. The tradeoffs are data and cpu usage vs bd delay.

xdrip wakes up about 5 minutes after the previuos reading. the challenge is that the data is arriving late to Nightscout which has a default poll rate of 2.5 minutes without looking at the bg time. Looking into improving that too.

**Comment by tolot27** [comment] 2020-12-21 12:45
@Kaivish Is your problem solved?

**Comment by Navid200** [comment] 2021-02-03 14:06
Someone on facebook experiences the delay.
I am following her child hoping to figure out what the problem is.  The attached image is from my follower.

Her son uses an iPhone 6 and has the Dexcom app on it that uploads to Nightscout.

I see on my follower that Next poll time is 10 minutes past the last BG time.  Why is that?
When I use the same phone and follow myself, those two are always only 5 minutes apart.  My collector is xDrip on an Android uploading to my Nightscout?

Is there a way to reduce the delay she experiences following her child?

Thanks 

![Screenshot_20210203-090034](https://user-images.githubusercontent.com/51497406/106757978-fca98a00-65fe-11eb-8ecb-f911c3f6866c.png)

**Comment by tolot27** [comment] 2021-02-03 16:00
> Her son uses an iPhone 6 and has the Dexcom app on it that uploads to Nightscout.

The Dexcom app cannot upload to Nightscout directly. It can only upload to Clarity or invite followers. Please can you clarify this?

**Comment by Navid200** [comment] 2021-02-03 16:58
Thanks so much.  Will update soon.

**Comment by Navid200** [comment] 2021-02-03 19:14
Can Dexcom app not upload to Nightscout if it has "Bridge username and password"?

**Comment by tolot27** [comment] 2021-02-03 22:19
> Can Dexcom app not upload to Nightscout if it has "Bridge username and password"?

Each user has their own Nightscout instance with an individual URL. This URL and API key cannot configured within the Dexcom app. I've found http://www.nightscout.info/wiki/welcome/nightscout-with-ios-and-dexcom-share but this is ancient and works only with G4/G5.  With this system, latency is "build in".

**Comment by Navid200** [comment] 2021-02-03 22:44
Thanks so much for the tips.
The lady has found an old Android phone and is going to try using xDrip on it as a collector.  This should solve the problem.  
If the approach fails for some reason and she decides to keep using the Dexcom app, I will use your tips.
Thanks so much.

**Comment by tolot27** [comment] 2021-02-04 00:40
She can also use "Dex Share Follower" as hardware data source and just send a share invitation from the Dexcom app. A lot is possible. 😄

**Comment by ahaarrestad** [comment] 2021-02-04 12:59
If you use dexcom share to upload data and then set up nightscoud to get
data from dexcom share you can follow the data in xdrip / nightscout. The
above problem is related to the "delays" caused by trying to save cpu and
battery etc.

* In nightscout you can set the poll-interval for dexcom share. Default is
every 2-3 minutes I think, so if you get "out of sync" you will experience
the above delays. The poll-interval can be reduced down to somewhere
between 1 minute and 10 seconds. This should help.
* xdrip has a "second pass" if it not receive the bg data after 5 minutes,
so the poll interval in nightscout helps.


The "config var" is called "BRIDGE_INTERVAL" and I've set ours to 10000 (10
seconds as milliseconds). Works fine.

[image: image.png]

- asbjørn

tor. 4. feb. 2021 kl. 01:41 skrev Mathias Walter <notifications@github.com>:

**Comment by Navid200** [comment] 2021-02-04 13:11
I asked the individual I was helping to switch the master phone from an iPhone to an Android and use xDrip on it.  After setting up Nightscout on the master and confirming that xDrip had readings and new readings were uploaded to Nightscout, the problem persisted.

I then asked her to switch the follower from a Nightscout follower to an xDrip Sync follower.  The problem persisted.

I then noticed in the last screenshot sent to me that the time on the follower phone was 3 minutes ahead of the correct time!

She synchronized the time and the problem is resolved.
I am not going to ask her to go back to see if the problem under other conditions will be resolved too or not.

**Comment by tolot27** [comment] 2021-02-04 13:19
> I then noticed in the last screenshot sent to me that the time on the follower phone was 3 minutes ahead of the correct time!

Please tell her to enable time synchronization with provider. This ensures that the time never diverges again.

**Comment by Navid200** [comment] 2021-02-04 13:24
Provider?  Please explain.

My phone is always automatically in synch.  I have never done anything special on any of my Android phones to keep them synchronized.  I thought as long my phone had access to the internet, Android would automatically check the time, with respect to a time reference on the internet.  My Windows desktop does the same.

**Comment by Navid200** [comment] 2021-02-04 13:34
Under "Date & time", I see that "Automatic date & time Use network-provided time" is selected.  And having this checked, "Set time" underneath is grayed out.
I am going to ask to her to make sure Automatic data and time is selected on her phone.  
Thanks

**Comment by Navid200** [comment] 2021-02-04 13:42
On her phone, the only option was "Use network-provided time", which was not selected.  So, I asked her to check that.
Thanks

**Comment by Navid200** [comment] 2021-02-25 02:30
@Kaivish Are you still experiencing this problem?
If not, can we close the issue?
Thanks

**Comment by tolot27** [comment] 2021-03-17 06:15
PR #1307 tries to address this.

**Comment by Navid200** [comment] 2023-03-08 17:48
@ahaarrestad How can I recreate this problem.
When I set up a Nightscout follower, I never experience a 5 minute extra delay.

**Comment by ChiSoxDev** [comment] 2023-10-19 19:35
@Navid200 I experience this issue and would be happy to work with you for troubleshooting. Being a nightscout follower, my xDrip updates with about a 10 minutes delay. I believe this is due to the polling time settings. It retries quickly for a few attempts, then after that it waits another 3 minutes. That three minute gap results in 8-10 minute delay.

**Comment by Navid200** [comment] 2023-10-19 19:43
@ChiSoxDev This is not something I experience.  I need to know why.
Can you provide any detail about your findings?

**Comment by ChiSoxDev** [comment] 2023-10-19 19:55
Screenshots here to give more details, but essentially it is polling Nightscout too quickly before a new reading. It retries once after 20 seconds, but then doesn't poll again for 4 minutes. I believe a better logic would be for xDrip to re-poll every minute if there was a successful poll within the past 10 minutes.

1) Here we are about ready to get a reading into Nightscout from Dexcom Share.

![Screenshot_20231019-134633~2](https://github.com/NightscoutFoundation/xDrip/assets/121800704/e3937ebe-58db-49ba-87a8-b2e96923c45c)

2) Here is just after it polls, but you can see it was before Nightscout received the reading. It will try again once 20 seconds later.

![Screenshot_20231019-134722~2](https://github.com/NightscoutFoundation/xDrip/assets/121800704/ae3dec6e-288a-462b-aca2-41930b6d3a7d)

3) After that second poll 20 seconds later, if Nightscout doesn't have the data yet, it is going to wait another 4 minutes before trying again. This results in a 10 minute difference in BG readings.

![Screenshot_20231019-134742~2](https://github.com/NightscoutFoundation/xDrip/assets/121800704/e5a08047-f96b-4ae8-82a6-994e87a7fbb5)

It's probably important to note that it isn't really a 10 minute delay. It's a 5 minute delay. xDrip will just say 10 because a 5 minute delay on a single reading means 10 minutes since the last one.

**Comment by Navid200** [comment] 2023-10-20 00:46
This is what I have:
![1](https://github.com/NightscoutFoundation/xDrip/assets/51497406/1980f2c1-47c8-41bc-9440-b4649b7a4039)
![2](https://github.com/NightscoutFoundation/xDrip/assets/51497406/11d9fd68-b3da-4231-8de2-37fe2439f0c4)
![3](https://github.com/NightscoutFoundation/xDrip/assets/51497406/f6e5cd18-6a03-4a1a-a2da-317ce0e6078b)

When it gets to the point that it shows last reading, 5 minutes ago, a few seconds after, it gets the next reading.  
And this is consistent.


Considering there is no difference in xDrip, I wonder if the difference between us that causes the difference in experience is our Nightscout servers.
Please ignore that you are using the July release and I am using the October release.  There has been no change to anything related to Nightscout follow for such a long time.  You can forget that.

I wonder if you are willing to try to set up an experimental Nightsocut site just to see if that could give us any clues.  
This is how I have set up my Nightscout: https://navid200.github.io/xDrip/docs/Nightscout/GoogleCloud.html

**Comment by ChiSoxDev** [comment] 2023-10-20 00:56
I think you are right in that for some reason my Nightscout is updating slower. I can look into that. But I think there is a solution on xDrip side too. If I am making correct assumptions xDrip polls down to the exact second it thinks there should be new data, then again 20 seconds later. But if Nightscout is late, it waits another cycle to poll. Adding a longer grace period than 20 seconds should solve the problem since I can't control how quick Nightscout gets the data from Dexcom.

I assume you are not using Dexcom bridge?

![Screenshot_20231019-185155~2.png](https://github.com/NightscoutFoundation/xDrip/assets/121800704/b2d20889-82bf-4378-bec2-ca4d1ebf3a02)

**Comment by ChiSoxDev** [comment] 2023-10-20 00:57
To clarify, I think there is closer to a 60 second delay for Dexcom bridge to send data to Nightscout. So it never has a reading within the 20 seconds grace period allowed and always hits 10 minutes.

**Comment by Navid200** [comment] 2023-10-20 00:59
There are many factors.  Yes, the data source is the other parameter.  I use a Dexcom G6 and I collect from it directly with xDrip that uploads to Nightscout.

The only time I can get behind a solution is if I understand the problem.  I see no problem on my side.  As long as I cannot recreate the problem, I cannot consider a solution.  I'm not denying that you are experiencing a problem.  I'm saying I need to know what is causing it before I can consider the solution you are suggesting.

**Comment by Navid200** [comment] 2023-10-20 01:02
If the bridge is the cause of the problem, perhaps the developers of it should fix it.

**Comment by ChiSoxDev** [comment] 2023-10-20 01:03
I feel like I've explained it. Dexcom is not linked to xDrip. Dexcom readings are adding to Nightscout via the Bridge option. xDrip polls exactly when there SHOULD be a reading, but the Dexcom Bridge to Nightscout is NOT instant like yours is where it's linked to xDrip. Instead the reading goes from Dexcom director to Nightscout, but at a slight delay (estimated 30-60 seconds.) 

So when xDrip polls, Nightscout hasn't gotten the next reading yet. xDrip tries again 20 seconds later but that's still too soon. Then it waits a whole additional 5 min cycle to try again and the loop continues of always being one reading behind.

**Comment by ChiSoxDev** [comment] 2023-10-20 01:04
> If the bridge is the cause of the problem, perhaps the developers of it should fix it.

The bridge isn't a problem, it's just a slower API call. So xDrip is polling too fast before it gets data.

**Comment by Navid200** [comment] 2023-10-20 01:13
Let me see if I can create a test xDrip that would extend the wait time if data is delayed for you to try.

**Comment by ChiSoxDev** [comment] 2023-10-20 02:58
Thanks that would be great! I'm happy to test whatever you put together.

**Comment by Navid200** [comment] 2023-10-20 03:07
This is not that simple.
xDrip has been written by people who know what they are doing.  
xDrip wakes up 5 minutes after the previous reading.  If there s slight variation, xDrip already can address it.  So, this would be a variation that is sometimes leading and sometimes lagging.
But, if we need to always delay, that means the frequency is wrong.  That's not a timing problem.  That is a frequency problem.

I will continue to read the code trying to see if there is anything that has been overlooked.
But, there is only so much we can go in addressing variations before we increase phone battery consumption.
If I find anything I can do, I will open a PR.

**Comment by ChiSoxDev** [comment] 2023-10-20 03:14
That makes sense, thank you! Let me know if you'd like me to open a different bug report since after looking it seems unrelated to this old one, just similar symptoms.

**Comment by Navid200** [comment] 2023-11-02 03:35
@ChiSoxDev 
> I assume you are not using Dexcom bridge? 

How can I set up a bridge?  I need to see the problem with my own eyes.
It's not that I don't believe you.  What I need is a test case I can use to verify my solution.  I am looking for a solution that identifies the problem and fixes it.  But, leaves every working situation alone.  And I am not looking for adding a new setting to let the user decide to enable or disable this.

So, please provide a link to instructions for setting up a bridge.

**Comment by Navid200** [comment] 2023-11-02 19:35
I believe I have been able to recreate this problem: https://github.com/NightscoutFoundation/xDrip/discussions/3164
I will open a Pr to address it.

**Closed** 2023-11-21 08:35 UTC
Labels: enhancement, sync-nightscout

**Comment by Navid200** [comment] 2023-11-21 12:30
The latest Nightly release (https://github.com/NightscoutFoundation/xDrip/releases/tag/2023.11.21) has a new setting when you select Nightscout follow as your data source.   You can use it to delay when the follower reads from Nightscout.
Please use it to see if it addresses this issue.

**Comment by ChiSoxDev** [comment] 2023-12-01 02:05
This works, thank you!!

**Comment by Navid200** [comment] 2023-12-01 02:30
@ChiSoxDev 
Great!
Thanks
