### ISSUE TITLE
Android Wear complications display null using native algorithm

### ISSUE THREAD

**Issue by browncoatdave** [NightscoutFoundation/xDrip#517] opened 2018-07-22 23:30 UTC
The watch face displays bg values correctly, and when using xdrip algorithm with g5 values displayed properly on complication.  Now using G6 and native, complication displays null.

**Comment by browncoatdave** [comment] 2018-07-22 23:34
Using 7/21 nightly on wear 2.0, pixel 2 xl 9.0 beta.

**Comment by jamorham** [comment] 2018-07-23 19:51
A fix for this is in the works

**Comment by cwpeterson** [comment] 2018-07-26 16:45
Going to throw a "me too" out there. I had no issues with this until I switched to G6 and the nightly build this week.

**Comment by jamorham** [comment] 2018-07-26 20:11
Please try the July 26th nightly, it should address this and also enable syncing of back-filled data.

If you are using a Wear 2.0 device then remember you need to uninstall and reinstall the wear app because it doesn't automatically update.

**Comment by browncoatdave** [comment] 2018-07-26 20:32
7/26 is working.  Thank you!

**Comment by cwpeterson** [comment] 2018-07-26 21:47
Confirmed, the complication is now working on my Moto 360 2nd Gen. Thanks for your efforts!

**Comment by cwpeterson** [comment] 2018-07-26 21:52
One question, where is the syncing of back-filled data option at?

**Comment by jamorham** [comment] 2018-07-27 09:09
Marking as resolved.

**Closed by jamorham** 2018-07-27 09:09 UTC

**Comment by jamorham** [comment] 2018-07-27 09:13
@cwpeterson its not an option, if you're using the native algorithm then the data will be back-filled and (now) synced properly.
