### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by crazysugarnl** [NightscoutFoundation/xDrip#1558] opened 2020-12-16 23:00 UTC
Latest app from today is not starting up,

Crashes inmediatly after starting the app, 

Build is the 16- december Build

**Comment by tolot27** [comment] 2020-12-16 23:16
@crazysugarnl You missed some environmental information the issue template asked for:

### Your environment
- What type of hardware data source and how do you get your data there (e.g. G6 or Libre with bluecon bridging device, Nightscout Follower, etc.)
- Is your issue specific to a device like and Android phone or a smartwatch? If yes, please provide the exact device name and type as well as the OS version (e.g. Samsung Galaxy S7 running Android 10.1).
- All settings related to the issue, e.g. activated auto calibration.

**Comment by crazysugarnl** [comment] 2020-12-17 04:49
Hardware type is : Samsung galaxy S20 5G
Operating System is Android 10
Data source is Libre Bluetooth.

**Comment by crazysugarnl** [comment] 2020-12-17 04:51
Predictive Simulation is on, Force language is on, extra status line is on

**Comment by crazysugarnl** [comment] 2020-12-20 20:07
New update from 18 december is still crashing, should i reset the Whole app and set it up again?

**Comment by tzachi-dar** [comment] 2020-12-20 20:15
Best if you can connect it to a pc and run
Adb locat


בתאריך יום א׳, 20 בדצמ׳ 2020, 22:07, מאת crazysugarnl ‏<
notifications@github.com>:

**Comment by tolot27** [comment] 2020-12-21 05:10
What is the latest working version?

**Comment by crazysugarnl** [comment] 2020-12-21 05:22
Nightly build 10th Dec 2020 is the latest one working

**Comment by crazysugarnl** [comment] 2020-12-21 08:25
xDrip-plus-20201210-d750cee.apk is the apk file used

**Comment by crazysugarnl** [comment] 2020-12-27 15:04
It looks like it is crashing when starting the sensor or when sensor already has been starter, when i reset everything, everything is working, but when starting a sensor, app crashes, also when on mmol and mm/gl.

**Comment by tolot27** [comment] 2020-12-28 07:20
Please can you provide some logs?

**Comment by crazysugarnl** [comment] 2020-12-29 12:20
I have sent the error logs in xdrip app to @jamorham, looks like there is coming to much data after updating to a newer version then the 10 december build

**Comment by crazysugarnl** [comment] 2020-12-31 06:09
![Screenshot_20201231-070757_xDrip+](https://user-images.githubusercontent.com/76134285/103397100-10149180-4b37-11eb-996c-09010e063f7e.jpg)
![Screenshot_20201231-070748_xDrip+](https://user-images.githubusercontent.com/76134285/103397105-11de5500-4b37-11eb-9f47-526070d61e62.jpg)
![Uploading Screenshot_20201231-070731_xDrip+.jpg…]()

**Comment by crazysugarnl** [comment] 2020-12-31 06:10
![Screenshot_20201231-070731_xDrip+](https://user-images.githubusercontent.com/76134285/103397131-320e1400-4b37-11eb-9a06-065fe2b7f756.jpg)

**Comment by ZandMarc** [comment] 2021-01-04 10:05
I think I have had the same issue. Can't reproduce the logs though, because in the end I deleted xdrip app and installed a previous apk. Built the apk that crashed a week ago; it worked fine for a few days, but after I restarted my G6 sensor it kept crashing in the way crazysugarnl reports. Funny thing was that even though I couldn't open xDrip and Android reported that it kept on crashing, my bg's in AAPS were still updated. I re-installed the apk a couple of times: it then worked for approx 15 minutes before it crashed again. Remarkable was that in that period, it reported in system status: "sensor status: time OK?". After I installed the previous apk, sensor status was reported ok. 

Phone is Nokia 2.2, Android 10
BG source is Dexcom G6
Version that works now for me is b978becc-2020.11.28
Version that crashed was pulled and built on december 29th.

**Comment by tolot27** [comment] 2021-01-06 22:59
Please can you try the latest version? It has an enhanced crash reporter system.

**Comment by crazysugarnl** [comment] 2021-01-06 23:02
I have tried the latest version, it is working now, not crashing, still getting message about received to much data, but now it is working, waiting till tomorrow or friday if app is still working, it crashed last time also after starting a new sensor

**Comment by crazysugarnl** [comment] 2021-01-06 23:07
![Screenshot_20210107-000455_xDrip+](https://user-images.githubusercontent.com/76134285/103831372-3c229c00-507c-11eb-88fd-ecf214a866fc.jpg)
![Screenshot_20210107-000448_xDrip+](https://user-images.githubusercontent.com/76134285/103831374-3d53c900-507c-11eb-9649-e728b094aede.jpg)
![Screenshot_20210107-000439_xDrip+](https://user-images.githubusercontent.com/76134285/103831376-3dec5f80-507c-11eb-9fd3-db1b6ddf619e.jpg)
![Screenshot_20210107-000430_xDrip+](https://user-images.githubusercontent.com/76134285/103831377-3e84f600-507c-11eb-96e0-9456c3562763.jpg)

**Comment by crazysugarnl** [comment] 2021-01-06 23:08
This is Just from now the latest version, everything looks like it is working again now, only need to test if it still is working after starting a new sensor tomorrow

**Comment by crazysugarnl** [comment] 2021-01-13 08:59
All other versions after the break versions are working, I have now the latest build installed and also started a new sensor, still working, last time it did crash when I started a new sensor.

Now looks everything good again, think that the bug has been fixed!

**Comment by tolot27** [comment] 2021-01-13 10:57
Since, it is working now, I'm closing this issue.

**Closed by tolot27** 2021-01-13 10:57 UTC
Labels: breaking, bug, device-libre
