### ISSUE TITLE
Follower receives NS entries download Failed: NumberFormatException - Received Null

### ISSUE THREAD

**Issue by briansealey** [NightscoutFoundation/xDrip#1366] opened 2020-06-14 15:34 UTC
Hi,

I have set up my NightScout account, and xDrip can write to it from the master device, but when setting up a following device, I receive the following -

NS entries download Failed:
com.google.gson.JsonSyntaxException:
java.lang.NumberFormatException: For input string: "Null"

The NightScout account was originally populated with entries by Diabox, but this stopped after a few hours, and I can't find a way of getting the details on a Wear OS watch. Hence why I'm trying xDrip. So there are gaps in the data, but I wouldn't expect that to cause an issue.

Thanks,

Brian

**Comment by greghesp** [comment] 2020-08-16 15:38
Same issue here

**Comment by tolot27** [comment] 2020-08-16 19:19
Which language(s) do you use? Are they identical in Nightscout and xDrip? Do you receive no BG values or no treatment values or neither of them? And last question: please can you enable verbose logging in settings >less common settings > extra tags for logging and then add there: `BgReading:v` and post the result here?

**Comment by greghesp** [comment] 2020-08-16 20:24
> Which language(s) do you use? Are they identical in Nightscout and xDrip? Do you receive no BG values or no treatment values or neither of them? And last question: please can you enable verbose logging in settings >less common settings > extra tags for logging and then add there: `BgReading:v` and post the result here?
> 
> It may help to to post the result of https://your.nightscout.server:port/api/v1/entries.json?find=[dateString][$gte]=2020-08-16&count=5, for instance. You can adjust the date, of course.

Same languages for me.  I can see that its retrieving treatments in NS, just not the BG Values.  Added that tag but nothing additional in the logs

**Comment by tolot27** [comment] 2020-08-16 21:14
Please use `NightscoutFollowEP:v` as an extra logging tag.

**Comment by greghesp** [comment] 2020-08-16 21:16
> Please use `NightscoutFollowEP:v` as an extra logging tag.

No change with that one either I'm afraid

**Comment by tolot27** [comment] 2020-08-16 21:26
What about `NightscoutFollow:v`?

**Comment by greghesp** [comment] 2020-08-16 21:30
Nothing there other than an estimated missed number of readings and the estimated next read date

**Comment by tolot27** [comment] 2020-08-16 21:37
According to the JSON spec, a null value should be written as `null` and not `"null"`.

`A value can be a string in double quotes, or a number, or true or false or null, or an object or an array.`

 That is the cause of the problem.

**Comment by tolot27** [comment] 2020-08-16 21:40
@greghesp Please can you check how the noise values are stored in your NS database?

**Comment by greghesp** [comment] 2020-08-16 21:52
> > Which language(s) do you use? Are they identical in Nightscout and xDrip? Do you receive no BG values or no treatment values or neither of them? And last question: please can you enable verbose logging in settings >less common settings > extra tags for logging and then add there: `BgReading:v` and post the result here?
> > It may help to to post the result of [https://your.nightscout.server:port/api/v1/entries.json?find=[dateString][$gte]=2020-08-16&count=5](https://your.nightscout.server:port/api/v1/entries.json?find=%5BdateString%5D%5B$gte%5D=2020-08-16&count=5), for instance. You can adjust the date, of course.
> 
> Same languages for me. I can see that its retrieving treatments in NS, just not the BG Values. Added that tag but nothing additional in the logs
> 
> Result of that api call. Could it be that its expecting `null` for noise, but instead gets it as a string?
> 
> ```
> [
>    {
>       "_id":"5f399b2d8287432672f2856f",
>       "device":"bubble",
>       "date":1597610794217,
>       "dateString":"2020-08-16T20:46:34.217Z",
>       "sgv":291,
>       "delta":900000,
>       "direction":"SingleUp",
>       "type":"sgv",
>       "filtered":291000,
>       "unfiltered":291000,
>       "rssi":100,
>       "noise":"null",
>       "sysTime":"2020-08-16T20:46:34.217Z",
>       "utcOffset":60
>    },
>    {
>       "_id":"5f399a048287432672f2413f",
>       "device":"bubble",
>       "date":1597610494150,
>       "dateString":"2020-08-16T20:41:34.150Z",
>       "sgv":276,
>       "delta":180000,
>       "direction":"Flat",
>       "type":"sgv",
>       "filtered":276000,
>       "unfiltered":276000,
>       "rssi":100,
>       "noise":"null",
>       "sysTime":"2020-08-16T20:41:34.150Z",
>       "utcOffset":60
>    },
>    {
>       "_id":"5f3998d58287432672f1f7c2",
>       "device":"bubble",
>       "date":1597610193985,
>       "dateString":"2020-08-16T20:36:33.985Z",
>       "sgv":273,
>       "delta":300000,
>       "direction":"Flat",
>       "type":"sgv",
>       "filtered":273000,
>       "unfiltered":273000,
>       "rssi":100,
>       "noise":"null",
>       "sysTime":"2020-08-16T20:36:33.985Z",
>       "utcOffset":60
>    },
>    {
>       "_id":"5f3997a98287432672f13893",
>       "device":"bubble",
>       "date":1597609894220,
>       "dateString":"2020-08-16T20:31:34.220Z",
>       "sgv":269,
>       "delta":300000,
>       "direction":"Flat",
>       "type":"sgv",
>       "filtered":269000,
>       "unfiltered":269000,
>       "rssi":100,
>       "noise":"null",
>       "sysTime":"2020-08-16T20:31:34.220Z",
>       "utcOffset":60
>    },
>    {
>       "_id":"5f39967d8287432672f05aa8",
>       "device":"bubble",
>       "date":1597609594227,
>       "dateString":"2020-08-16T20:26:34.227Z",
>       "sgv":265,
>       "delta":-525000,
>       "direction":"FortyFiveDown",
>       "type":"sgv",
>       "filtered":265000,
>       "unfiltered":265000,
>       "rssi":100,
>       "noise":"null",
>       "sysTime":"2020-08-16T20:26:34.227Z",
>       "utcOffset":60
>    }
> ]
> ```

I've been suggesting this was the issue since I posted the dB values :)

I suspect this is something to do with how Diabox is storing the data. I've raised it with the dev on their Facebook group though

**Comment by tolot27** [comment] 2020-08-16 22:56
I thought you have posted the response of the Nightscout API call.

Anyway, the Diabox PR was merged just about 20 hours ago. Hence you checked out the source code and compiled the app yourself. You may try PR #1408.

**Comment by tolot27** [comment] 2020-08-27 21:25
@greghesp Please can you test the PR #1408?

**Comment by greghesp** [comment] 2020-08-27 21:43
@tolot27 Sorry, only just seen this.  

I also mentioned this as an issue to the Diabox developer, and I can only assume that they deployed a fix as the object schema is now correct so I wont be able to test this:

```
{
"_id": "5f4827f398dfe821bbd5f0e8",
"device": "bubble",
"date": 1598564331916,
"dateString": "2020-08-27T21:38:51.916Z",
"sgv": 199,
"delta": 75000,
"direction": "Flat",
"type": "sgv",
"filtered": 199000,
"unfiltered": 199000,
"rssi": 100,
"noise": 1,
"sysTime": "2020-08-27T21:38:51.916Z",
"utcOffset": 60
},
```

**Comment by tolot27** [comment] 2020-08-28 15:34
@briansealey Do you still have the problem? If not, please close this issue.

**Closed** 2020-09-03 07:47 UTC
