### ISSUE TITLE
Libre2 sensor dont deliver readings

### ISSUE THREAD

**Issue by keencave** [NightscoutFoundation/xDrip#1326] opened 2020-05-02 15:41 UTC
Some user reports that the Libre2 sensor dont connect to the phone via BT. Sometimes this could be solved by simply waiting or they delete the BT cache. In such a case in the xdrip+ system status instead of the serial number a MAC like adress (?) is displayed: 
![94872984_1070961463259962_3337327517571743744_o](https://user-images.githubusercontent.com/23220008/80868594-0aab3280-8c9c-11ea-8d69-31e5885d41ca.jpg)
Where does this number come from?

**Comment by yosepito** [comment] 2020-05-23 16:00
I assume you're running the librelink app patched. Check that you have bluetooth activated and librelink is running in the background. Check also that there are no warnings in librelink app. If there is your first time, you should activate NFC, BT, location services GPS and an alarm in librelink to be able to connect. When librelink has no connection with Libre-2, there won't be readings. 

In the image, it seems you were running with 1% of battery. In this situation, it is likely that android disabled BT so there are no readings coming from librelink.

**Comment by fookatchu** [comment] 2020-05-23 16:12
There are currently faulty libre 2 sensors in the wild. I received an email which explains that the alarms (bluetooth) are not working, but scanning (nfc) is not affected. Since the patched app gets it's data via bluetooth, no data is send to xdrip. This at least is my assumption. I have one of these sensors running right now. I suppose this is somehow related. I only received a german mail from Abbott, but anyone affected should have received that too. If not, here are the affected Lot-numbers:

[https://abbott.emsecure.net/images/B2C/_2020/COS_Oneshot/DE_de/Adhoc_FSL02_Communication/img.png](https://abbott.emsecure.net/images/B2C/_2020/COS_Oneshot/DE_de/Adhoc_FSL02_Communication/img.png)

**Comment by mk886714** [comment] 2020-05-23 16:31
Kann leider praktisch dazu nichts austesten aber liegt dies vielleicht am Datensparen in den neueren Android Versionen?
Ähnliches Problem hatte ich nach einem android Update bei meinen Samsungtelefonen in Verbindung mit Dexcom G6, xdrip hatte keine Werte bis ich Daten im Hintergrund für xdrip und bluetooth erlaubt und beide auscder Energiesparoption nahm, dann hat es wieder funktioniert
Unfortunately, can not test practically anything, but maybe this is due to data saving in the newer Android versions?
 I had a similar problem after an android update on my Samsung phones in connection with Dexcom G6, xdrip had no values ​​until I allowed data in the background for xdrip and bluetooth and took both energy saving options, then it worked again

**Comment by steve8x8** [comment] 2020-05-30 10:48
Since Abbott has confirmed that (a major part of) K sensors are faulty, and most users didn't change anything between the last working and the failing sensor(s), and there are now reports that the replacements (with the "old" LOT numbering scheme) are working again, also without modifications to the smartphone/app/settings -
- can this issue be marked as "unrelated to xDrip" and possibly closed?

**Comment by benfiscal** [comment] 2020-06-14 08:38
#1056

**Comment by benfiscal** [comment] 2020-06-16 09:19
I had the same screen as above, but managed to get it working by allowing the apps to run in the background in the auto run manager in Settings.
#1367

**Comment by corneliusroemer** [comment] 2020-07-20 10:58
> There are currently faulty libre 2 sensors in the wild. I received an email which explains that the alarms (bluetooth) are not working, but scanning (nfc) is not affected. Since the patched app gets it's data via bluetooth, no data is send to xdrip. This at least is my assumption. I have one of these sensors running right now. I suppose this is somehow related. I only received a german mail from Abbott, but anyone affected should have received that too. If not, here are the affected Lot-numbers:
> 
> https://abbott.emsecure.net/images/B2C/_2020/COS_Oneshot/DE_de/Adhoc_FSL02_Communication/img.png

Can you give more details about this manufacturing problem. My lot number looks very different:

More like 5857407, no K, fewer numbers. Maybe mine is also this (10)5857407.

I'm having occasional reception problems, it works over night, but sometimes it doesn't work for 50min, it may be interference from my BT mouse. Not sure yet. Trying to figure it out.
![15952425803274845328075068100317](https://user-images.githubusercontent.com/25161793/87930503-80978c80-ca88-11ea-9fc8-3efaeea1bb94.jpg)

**Comment by fookatchu** [comment] 2020-07-20 11:57
> > There are currently faulty libre 2 sensors in the wild. I received an email which explains that the alarms (bluetooth) are not working, but scanning (nfc) is not affected. Since the patched app gets it's data via bluetooth, no data is send to xdrip. This at least is my assumption. I have one of these sensors running right now. I suppose this is somehow related. I only received a german mail from Abbott, but anyone affected should have received that too. If not, here are the affected Lot-numbers:
> > https://abbott.emsecure.net/images/B2C/_2020/COS_Oneshot/DE_de/Adhoc_FSL02_Communication/img.png
> 
> @fookatchu Can you give more details about this manufacturing problem. My lot number looks very different:
> 
> More like 5857407, no K, fewer numbers. Maybe mine is also this (10)5857407.
> 
> I'm having occasional reception problems, it works over night, but sometimes it doesn't work for 50min, it may be interference from my BT mouse. Not sure yet. Trying to figure it out.
> ![15952425803274845328075068100317](https://user-images.githubusercontent.com/25161793/87930503-80978c80-ca88-11ea-9fc8-3efaeea1bb94.jpg)

I don't have any more infos. All faulty sensors were replaced and everything is working again. If you haven't been contacted, I think you are not affected.

**Comment by tolot27** [comment] 2020-09-21 22:38
The original question is where the globally unique identifier comes from. Is it still of interest or can this issue be closed?

**Comment by Navid200** [comment] 2021-03-15 18:08
Closing due to inactivity.

**Closed by Navid200** 2021-03-15 18:08 UTC
Labels: question
