### ISSUE TITLE
Xdrip i mi band 4

### ISSUE THREAD

**Issue by majamajaa** [NightscoutFoundation/xDrip#1440] opened 2020-09-19 11:44 UTC
Povezali smo xdrip i miao miao 2,sve radi ok,kad smo pokusali da xdrip povezemo sa mi band 4 nismo uspjeli.Xdrip ga pronadje,povezano sve ali na mi band nema ocitavanja,samo se javi alarm ponekad,zna li ko do cega je? Dosta puta smo brisali sve pa inst.ponovo ali na mi band nema ocitavanja osim alarma koji se upali kad i na telefonu.

**Comment by tolot27** [comment] 2020-09-19 17:06
Please change your text to English. Use DeepL or Google Translate, if needed. Otherwise, we cannot provide support.

**Comment by AdrianLxM** [comment] 2020-09-21 06:01
The caveat that is often overlooked:

You must not unpair / repair the watch when switching back to the non-patched version of the app. If you do, it well create a new key and you cannot send data.

**Comment by AdrianLxM** [comment] 2020-09-21 06:09
duplicate of #1441

**Closed** 2020-09-21 06:09 UTC
Labels: question
