### ISSUE TITLE
Connectivity problem reaching Share servers

### ISSUE THREAD

**Issue by iqhu** [NightscoutFoundation/xDrip#1297] opened 2020-04-10 07:31 UTC
Since approximately 8.30am CET on April 9th I get the problem "Connectivity problem reaching Share servers". I use dexcom share/ follow to get readings for my xdrip app and nightscout website. The website didn't get readings since ca. 1am the same day. So both sources have a problem getting share data. Interestingly enough, my dexcom follower through the official app still get readings without any changes.

The exact wording in the event log of xdrip is the following: "Get Share Data Failed: java.io.EOFException: End of input at line 1 column 1 path $" 

Located in Europe, if that has to do with server. Updated to the latest nightly as well. 
Has anyone had the same problem? Any idea how to fix it?

**Comment by Josef-A** [comment] 2020-04-10 09:30
I have the same problem as iqhu. 
Several users in Sweden does have the same problem. But there also users with no problem at all.
Issue in nightscout:
nightscout/cgm-remote-monitor#5608

**Comment by iqhu** [comment] 2020-04-12 15:06
Just to update here as well: I didn't get it fixed but switched to using my Galaxy S10 through xdrip as a collector again (which now actually works again).

**Comment by Josef-A** [comment] 2020-04-24 08:04
It seems that the problem is because of other character then a-z in the user name.
See the discussion in nightscout/cgm-remote-monitor#5608

Unfortunately you can't switch the user name. You have to set up a new account.
I wrote down some instructions how to change the Dexcom account.
https://github.com/Josef-A/sugarmate2nightscout/blob/master/how_to_fix_en.md

The instructions is written for Nightscout users. But it's nearly the same for xDrip.

**Comment by Josef-A** [comment] 2020-04-24 08:11
It would be good if the problem with user Dexcom user name can be mentioned in the documentation for xDrip. 
I do not have that much experience of Github pull request. So if someone can fix that it would be great.
After that I think we can close this issue.

**Comment by Navid200** [comment] 2021-03-14 05:42
@Josef-A refer to the documentation for xDrip.
What do you mean by that?
There are a lot of capabilities that are not documented.  We definitely can improve that and create documentation.
But, I don't think we should have an open issue for every item that has no documentation.

Please let me know if you disagree.
Otherwise, I would like to close this issue.
Thanks

**Comment by Josef-A** [comment] 2021-03-14 09:39
This problem with other character then a-z seems hard to troubleshoot. Some people have the problem some don’t. When this thread opened it seems to be many that had the same problem. After that I haven’t heard so much about it. Maybe one user per month.

I understand that it’s natural in these kind of project that the documentation is lagging behind the features.

In the end it is a tradeoff between the time you spent updating documentation and the time spent troubleshooting for users.
I think you @Navid200 have the best insight in both sides of that.

It’s alright for me if you close it. I guess that people getting the same problem will still be able to find the closed issue and get help from that.

**Comment by Navid200** [comment] 2021-06-21 03:26
Thanks.
I agree

**Comment by fzelins** [comment] 2021-12-03 00:08
I did not have this problem and xdrip was working fine, now suddenly I have this problem and xDrip is not working. Issue should be reopened. I have my dex account linked to Diasend of my clinic and I can not create new, without updating it there...

**Comment by Navid200** [comment] 2021-12-03 00:59
@fzelins Please post here:
https://github.com/Navid200/xDrip/discussions

**Comment by tolot27** [comment] 2021-12-03 07:55
Please add "ShareFollowDL:v,ShareFollowEP:v" to the extra logging tags and report if there are more information in the error logs.

**Comment by tolot27** [comment] 2021-12-08 07:59
Is anyone able to use adb logcat on a computer connected to phone? If yes, I can provide a debug version which collects HTTP responses and sends them to logcat. But since this version is not signed, the currently installed version has to be removed (backup of settings and db is required beforehand).

I'm also trying to get the preference "Store logs for troubleshooting" to work for the phone app. Currently, it works only on Wear OS.

**Comment by samgray85** [comment] 2021-12-19 03:09
Following. Having the same issue
 Username has numbers in it

**Comment by tolot27** [comment] 2021-12-19 13:58
It is very likely that this issue will be fixed together with the fix for #1882.

**Comment by charli144** [comment] 2022-02-07 21:31
i have a similar problem but i get a different error message: ShareFollowCallback
login failed:java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by Josef-A** [comment] 2022-02-07 21:44
Those of you who have had similar problems recently. It may not be the same problem. Both Nightscout and Dexcom share have changed since this issue came up. For example, it was not possible to have an email as a username then.
So I think it's better for you to start a new issue and describe your problems there.

Do also check if your problem is described in https://nightscout.github.io/troubleshoot/troublehoot/

**Comment by Navid200** [comment] 2022-02-07 21:48
@Josef-A No one should open new issues unless directed by developers.  Please don't advise people to open new issues.  Thanks

**Comment by Josef-A** [comment] 2022-02-07 22:04
@Navid200 I'm really sorry. I mixed up this repository  with the one for Nightscout. I delete my comments

**Comment by Navid200** [comment] 2022-02-07 22:07
@Josef-A Your advice was fine as long as you tell people to use the discussions platform initially.

**Comment by tolot27** [comment] 2022-02-08 05:39
Please can you try the apk I've provided in https://github.com/NightscoutFoundation/xDrip/issues/1882#issuecomment-1026294458?
If it still does not work, please follow https://github.com/NightscoutFoundation/xDrip/issues/1882#issuecomment-1026609865 and report it here.

**Comment by tolot27** [comment] 2022-02-09 19:50
The newest [nightly](https://github.com/NightscoutFoundation/xDrip/releases/tag/2022.02.09) contains the fix for #1882. Please try it and report back whether it solves your problem(s) as well.

**Comment by Navid200** [comment] 2022-04-24 23:36
Is anyone still experiencing this issue with the current stable release (January 31, 2022)?

**Closed** 2023-05-30 16:40 UTC
Labels: sync-dexcom, type-documentation
