### ISSUE TITLE
xDrip followers sync feature dead after Google FCM API removed on 22.07.2024

### ISSUE THREAD

**Issue by ireneusz-ptak** [NightscoutFoundation/xDrip#3582] opened 2024-07-23 09:18 UTC
I know, I didn't consult the developers first, but that's not a "bug", just a major f*ck up... so I'm just trying to get @jamorham attention :)

### Subject of the issue
Google FCM old API was removed yesterday causing major issue for all xdrip followers. It seems it was announced a year ago, but nothing was done in this time.
https://firebase.google.com/support/faq#deprecated-api-shutdown

Not an mobile expert but I really hope that Firebase SDK upgrade (15.0.0 -> 24.0.0) in xDrip should be enough to fix the problem.

### Your environment
Doesn't matter - all apps using the FCM messaging API are affected.

### Expected behavior
Followers working like two days ago

### Actual behavior
Communication between master and followers broken using default sync.

**Comment by jamorham** [comment] 2024-07-23 10:58
This is being worked on right now.

**Comment by ireneusz-ptak** [comment] 2024-07-23 11:01
Thanks, can you provide any estimates? Because this time #aLotOfPeopleAreWaiting ;)

**Comment by Navid200** [comment] 2024-07-23 11:08
@ireneusz-ptak jamorham stated already in the discussion that he was working on it.
Yet, you went ahead and opened this issue.
He then stated here that he was working on it.  

Thanks for reporting the underlying root cause.  You have helped us a lot by doing that.
Thank you so much.

Can I ask you to please do us a favor?
Would you please not ask for a schedule?

You don't know how grateful I am to you for having reported the root cause.  But, please remember that jamorham is a volunteer as well.   

If he needs help, I am available to give him a hand.   
I know that this is critical.  I am not denying that.  What we need now is patience on the user part so that we can focus on the problem and fix it.
Thanks

**Comment by ireneusz-ptak** [comment] 2024-07-23 11:20
> @ireneusz-ptak jamorham stated already in the discussion that he was working on it. Yet, you went ahead and opened this issue.

No, I didn't - the issue was opened before. And I did it because you said the issue was on Google side and we just need to wait for it to work.

> Can I ask you to please do us a favor? Would you please not ask for a schedule?

I'm not asking for a schedule, I know how such investigations work, I did at lot of them.
 
> But, please remember that jamorham is a volunteer as well.

Yep, me too.

> If he needs help, I am available to give him a hand. I know that this is critical. I am not denying that. What we need now is patience on the user part so that we can focus on the problem and fix it. Thanks

I know it's an open source project that relies on volunteer work, but there's responsibility with that. A lot of people are using this feature to monitor their kids remotely (especially during vacation time). I think there's nothing wrong to ask if we may expect the release today or next week because this determines which workarounds might be suggested to users.

**Comment by jamorham** [comment] 2024-07-23 11:23
I would like to have something out today but that is a very tight time schedule and needs plenty of things to go right but it is my number 1 priority and I recognise how important the follower feature is.

**Comment by ireneusz-ptak** [comment] 2024-07-23 11:26
> I would like to have something out today but that is a very tight time schedule and needs plenty of things to go right but it is my number 1 priority and I recognise how important the follower feature is.

Thanks, fingers crossed.

**Comment by tloczekt** [comment] 2024-07-23 12:08
maybe this is a temporary (not elegant) solution ?

![obraz](https://github.com/user-attachments/assets/dd457c3d-70c0-465b-bf58-ca42c8d61c53)


FCM deprecation extension request

Firebase can be individually extended for a specific time.
I hope this way we can buy some time for modification.

**Comment by jamorham** [comment] 2024-07-23 12:53
Yes I have already requested an extension but they may not be inclined to help us.

**Comment by jamorham** [comment] 2024-07-23 13:32
I am making good progress and the chance of an update today is increasing.

**Comment by jamorham** [comment] 2024-07-23 16:36
There is a new nightly available which is intended to resolve this issue. Please test. thanks

**Comment by ireneusz-ptak** [comment] 2024-07-23 16:44
Awesome, on it! Could you release the "variants" as well?

**Comment by olorinmaia** [comment] 2024-07-23 16:47
> Awesome, on it! Could you release the "variants" as well?

Also need variants to assist with testing. Let me know when they are out 👍

**Comment by elgrupo123** [comment] 2024-07-23 16:52
Bei mir synct die neue nighty leider nicht.

**Comment by ireneusz-ptak** [comment] 2024-07-23 16:54
@jamorham Works for me :)

Could you drop a link for donations as well? A lot of people found out how xdrip is helpful on daily basis.

**Comment by ireneusz-ptak** [comment] 2024-07-23 16:55
> Bei mir synct die neue nighty leider nicht. Oder muss auf Master die neue Version haben?

Yes, you need to update both the master and followers.

**Comment by richardstock1** [comment] 2024-07-23 17:01
All working again on the new nightly build. Thank you so much for getting this working again. As already mentioned please post up a donation link so we can say thanks 👍👍

**Comment by olorinmaia** [comment] 2024-07-23 17:08
@jamorham our sync group with 4 phones tested ok! Great work! 💙

**Comment by ireneusz-ptak** [comment] 2024-07-23 17:10
1. Variant2 also working great.
2. About the fix - is it a temporary workaround or you're dropping Google services completely?

**Comment by jamorham** [comment] 2024-07-23 17:21
The variants are now also on the release: https://github.com/NightscoutFoundation/xDrip/releases/tag/2024.07.23
I can put up something for donations later. Typically I have only accepted technical items from a wishlist.

Google discontinued the messaging feature that xDrip was using so it is now using infrastructure from the BlueJay project to fill the gap.

**Comment by ireneusz-ptak** [comment] 2024-07-23 17:26
Sure, let's hope it can hold the traffic. I hoped it's only a matter of API migration: https://firebase.google.com/docs/cloud-messaging/migrate-v1

And thanks again :)

**Comment by deival1980** [comment] 2024-07-23 17:42
@jamorham 
Thank you so much for solving this problem so fast!

**Comment by Limitose** [comment] 2024-07-23 18:15
@jamorham Thank you for your help!
For me it was enough to update the master. All followers could receive values ​​again  without update.

**Comment by deival1980** [comment] 2024-07-23 18:19
@Limitose 
I saw the same accidentally, after updating master follower could already receive values. I updated followers as well afterwards and this works as well.

**Comment by wirbel-at-vdr-portal** [comment] 2024-07-23 18:24
Same here, one follower started working after the master was updated.

**Comment by ireneusz-ptak** [comment] 2024-07-23 18:32
> Same here, one follower started working after the master was updated.

In that case I think I don't want to know how it works :)

**Comment by Limitose** [comment] 2024-07-23 18:34
I was happy to not have to update the followers because I have made a special version based on the code from an older xDrip+ version that I use on an Android tablet as an "alarm clock" in the bedroom where I have enlarged the fonts and the dots on the curve on the Widget so I can follow the blood sugar through the night. :-)

**Comment by jonprogers** [comment] 2024-07-23 18:36
> Same here, one follower started working after the master was updated.

All working again here for me too - I have one old phone setup as a follower which is held back on the version from 27th March 2024 as it is an Android 6 device and that has come back to life too.

Many thanks

**Comment by jamorham** [comment] 2024-07-23 18:42
If you don't update the followers then things like remote snoozes from follower back to master or backfill requests wont work.

**Comment by deival1980** [comment] 2024-07-24 04:25
Hello @jamorham,
There are 2 points regarding the Desert sync I do not understand, I'll ask them here because it is in relation with that:

1. I thought Desert sync is directly working through IP addresses. Why was the Desert sync also not working any more when the Google API was shut down? 
2. Having Desert sync active is working again now, but over night I was getting a notification that the Desert Sync was not working any more. It was telling me that the IP address of master was maybe changed... I got only a vibrating notification, while tone was on at the phone. Why? And how can I configure such notifications? Values were not synchronized any more, why doesn't it fall back to use Google API when this is configured?

**Comment by ireneusz-ptak** [comment] 2024-07-24 10:42
@jamorham Not sure if it's temporary, but it seems the new infra might be struggling with the traffic - I'm getting a lot of missing readings today (also saw some other people noticing that too). I'm worried it might be worse with more people switching to the latest version.

**Comment by richardstock1** [comment] 2024-07-24 15:30
> @jamorham Not sure if it's temporary, but it seems the new infra might be struggling with the traffic - I'm getting a lot of missing readings today (also saw some other people noticing that too). I'm worried it might be worse with more people switching to the latest version.
> 
> EDIT: might be related to not getting updates while the phone is locked/stand by

Yes, this may be it.. I have kept my daughters phone from being locked/stand by and I am now getting consistent readings again.

**Comment by njguerra1975** [comment] 2024-07-24 16:56
Thank you to everyone who participates in this solution.
You saved my day and today I'm going to sleep peacefully.

**Comment by wirbel-at-vdr-portal** [comment] 2024-07-24 17:27
Just as a comment, this version of xdrip+ runs perfect on three xiaomi phones, better than previous versions.

master = Redmi Note 7
followers = 11T/11T Pro

**Comment by chrisGIT-ING** [comment] 2024-07-25 10:33
Great work. Thank you! (When) Is it planned to bring this working nightly to the stable branch?

**Comment by direninceoren** [comment] 2024-07-25 11:26
Hello 
We installed this version, but when the master phone is not connected to wifi, the followers do not receive data. I wonder what is the reason for this and how can I solve it?

**Comment by marcinkrawczykzg** [comment] 2024-07-25 21:09
For me, the only solution that worked was installing the April 2023 version on my main phone. My phone and my wife's phone, which are followers, have the latest version of XDRIP. Everything has been working for several hours, and everything is still working as expected. We can see the readings and easily enter values for carbohydrates and insulin. All phones are synchronizing correctly.

**Comment by bordeb** [comment] 2024-07-30 19:58
Just to let know that it seams that sync over Google works again! At this mkment it all works for me: testing using latest stable version 2024.04.19 (same version on master as well as followers). I don't know why it works again, but just to inform here so gurus can maybe use this info.

**Comment by Navid200** [comment] 2024-07-30 20:23
@bordeb As explained in this discussion (https://github.com/NightscoutFoundation/xDrip/discussions/3595), the old setup you are using works only for a while and will eventually go away permanently.  

No one should use that unless they have confirmed the new setup does not work for them.  But, in that case, please tell us what the problem is.

**Comment by bordeb** [comment] 2024-07-30 20:38
> @bordeb As explained in this discussion (#3595), the old setup you are using works only for a while and will eventually go away permanently.
> 
> No one should use that unless they have confirmed the new setup does not work for them. But, in that case, please tell us what the problem is.

Thank you! Haven't noticed this part of the discussion that I am aware of. Apologies for bringing out what was already clear and known! Thank you for being so fast.

**Comment by richardstock1** [comment] 2024-08-13 20:55
Using the current updated version of xdrip but it looks like there are some issues again with sync between master phone and followers. Just thought I'd mention it as a few have reported issues over the last few hours.

**Comment by Lomax007** [comment] 2024-08-14 10:16
> Using the current updated version of xdrip but it looks like there are some issues again with sync between master phone and followers. Just thought I'd mention it as a few have reported issues over the last few hours.

Can someone please confirm this is being investigated? It's a widespread issue, affecting many Sync users as can be seen on the Facebook group

**Comment by Navid200** [comment] 2024-08-14 11:24
Yes, it is known.  You can use Nightscout until this is resolved.

**Comment by cp2113** [comment] 2024-09-13 10:20
Dear Developers! For me, since the development on 07/23/2024, the Companion app setting does not read data from the Guardian (G4) application. I don't think there is a problem with the phone's settings, since the 19.04.2024. version can read in Companion app mode, but xDrip Sync Follower does not work in this mode. this has been fixed in the new version. Thank you in advance for your help!

**Comment by Navid200** [comment] 2024-09-15 12:06
Update to the release of 2024.09.15 or any after that.

Make sure to enable the setting `Use xDrip Cloud` on the xDrip Sync Settings page on the master and followers.
![Screenshot_20240915-080324](https://github.com/user-attachments/assets/f1cfa503-4215-4ac4-887c-8960aaa69911)

**Comment by Navid200** [comment] 2024-09-15 12:23
If everything worked fine for you before and enabling the new setting causes problems, disable the setting on the master and followers.

**Comment by olorinmaia** [comment] 2024-09-15 22:07
Used this on our sync grp with 3 phone since release and no issues so far. Excellent work @jamorham 👏
Its super fast, it sync bg, sensor age and sensor statuses, remote snooze, treatments etc.

**Comment by Navid200** [comment] 2024-09-30 11:48
Well, it's not dead any more.
All the details are here: https://github.com/NightscoutFoundation/xDrip/discussions/3664  

In summary, you need to use the current stable release or any other after that and enable the new setting `Settings > `xDrip Sync Settings` > `Use xDrip Cloud` on the master and all followers.
If you experience any issue, please let us know by opening a discussion.

We can reopen this if needed.

**Closed by Navid200** 2024-09-30 11:48 UTC
Labels: sync
