### ISSUE TITLE
Please support multiple BG sources

### ISSUE THREAD

**Issue by lee-b** [NightscoutFoundation/xDrip#871] opened 2019-05-11 11:43 UTC
Since CGMs aren't entirely accurate, it would be great to be able to at least try multiple BG sources at the same time, like the Libre and G6 together, taking the average.  ESPECIALLY if you could weight those sources according to how accurate they are likely to be.

Doing this might also simplify the code, unifying the bluetooth BG meter sources and the CGM sources, and possibly a newly factored out "manual" source which uses the UI, too.

Essentially, this is a request to change the Hardware Data Source menu's mutually exclusive radio buttons into checkboxes, so that multiple sources can be chosen at once.

Ideally, the menu (or settings within each sources' configuration) would allow weighting/prioritisation of those sources' data, adjusting up/down from 1.0 (or 0.0), or perhaps even just by dragging-and-dropping to re-order sources in the list according to trustworthiness.

I think entering weight numbers would give significantly more control, though, which seems to be XDrip's usual approach to things.

I think this would be an opportunity to improve XDrip's "calibration override" feature too, using the source priorities described above.  It's quite worrying right now, when the libre is far off the mark, and you enter a BG reading, but it doesn't calibrate sufficiently, forcing a "reset calibrations".  Priorities would allow you to say "any time you get a BG reading from my meter over bluetooth, that is 100% the reading you should use.  Adjust everything accordingly, no matter what my CGM thinks."

**Comment by Navid200** [comment] 2021-02-25 02:22
@lee-b How would you enter the settings for each?
For example, Bluetooth Settings.  That settings page may contain a setting that needs to be checked for G6 but unchecked for Libre.  

How will you handle the timing?  xDrip wakes up and searches for the next reading once every 5 minutes.  But, having two different transmitter to deal with, it will have to have two different times.  What happens if they coincide?

This is going to complicate the code dramatically.  
I agree that it can be useful in some cases.  But, how many people do you think are going to gave two sensors attached to them at the same time?

It sounds like an extreme cost to pay (development time and code complexity) to accomplish something that not many are going to benefit from.

If you absolutely need to perform this exercise, you can always install two versions of xDrip (one being a variant) on the same phone.  Or, for the experiment, you can use two phones and accomplish your objective.  

I am going to close this.
But, we can always re-open it.

Please let me know what you think about my questions?
Thanks

**Closed by Navid200** 2021-02-25 02:22 UTC

**Comment by DmitriyShepelev** [comment] 2024-06-09 20:41
I'd appreciate this issue being reopened.

Since this issue was first opened, I think many more people have started using multiple BG sources, and demand for this feature exists. [autoISF](https://github.com/ga-zelle/autoISF/) users (an entire [Discord community for whom](https://discord.gg/Pn4t34TU) exists, with over 800 members) and other DIY AID system users frequently use two CGMs to ensure their BG data are accurate, and this feature would improve the quality of their lives significantly:
* ability to broadcast a weighted average BG datum to AAPS (e.g., one can apply a simple 50/50 weighting to the data from two Dexcom G6 sensor BG sources); a more complex (though potentially more accurate) example would be to apply a function onto the sensor data based on the amount of time since the sensor was inserted. It's widely known that Dexcom G6 sensors have a tendency to be inaccurate the first 24 hours after insertion, as well as decreasing accuracy the last day/few hours of the sensor; a function therefore can be applied to the data from each BG source to maximize data fidelity. This feature in it of itself would:
    * obviate the need for multiple xDrip variant apps and therefore having to manually switch the xDrip variant locally broadcasting to AAPS.
    * lessen the effects of compression lows. (E.g., if a user has a sensor on each arm with one sensor compressed during sleep, then it is guaranteed that the other sensor is not being compressed, which can therefore smooth the compression low noise.)
* potential to notify users of when a BG source has become faulty based on BG delta(s) compared to other BG sources. E.g., notify the user if BG source X has had an average delta > Y for at least Z minutes compared to BG source Y. (A user can then potentially take action by replacing BG source X or having xDrip regress to a simple 50/50 BG weighting until the issue is resolved.) 

---

Given the benefit of this feature for those using multiple BG sources, I think the development cost is well worth it.

**Comment by Navid200** [comment] 2024-06-09 22:26
@DmitriyShepelev This would make xDrip extremely complicated for the xDrip users as well as for the xDrip developers.

I don't believe the majority of those needing a CGM would care to have 2 sensors attached to them.  
xDrip has many users worldwide.  I'd rather not make xDrip something that only experts can use.  I want everyone to be able to use it.

Regardless of my personal opinion, nothing will happen unless a developer chooses to develop it with or without an open issue.
Just look at our open issues.  There are some that have been open for years.
