### ISSUE TITLE
Dexcom Share as source?

### ISSUE THREAD

**Issue by Arakon** [NightscoutFoundation/xDrip#480] opened 2018-06-16 08:48 UTC
Hi.
Is it possible (if not, please consider this a feature request) to grab the entire data of a G5 from Dexcom Share? Reason being, the dexcom app works okay for me, but the watchface stops getting data after a few readings, plus, I'd prefer to have the xdrip nightwatch watchface or complications in the first place. I'd prefer not to use xdrip as my main app simply because my insurance and doctor insist on getting the "official" dexcom data and diagrams.

**Comment by dabear** [comment] 2018-07-04 22:06
Xdrip doesn't support following share.whst you could do (but this gets a bit involved) is to use niggscouts share ridge to get your dexcom data into nightscout. From there you could download the nsclient and make it broadcast values to xdrip. You would also have to enable a setting in xdrip to make it listen to local broadcasts

**Comment by prydin** [comment] 2019-03-18 21:29
I am thinking of implementing this. We could probably forklift the code in Nighwatch that connects directly to share. Any interest?

**Comment by jamorham** [comment] 2019-03-19 17:02
There is some work ongoing regarding this. I assume everyone in this issue is interested in testing when available.

**Comment by Arakon** [comment] 2019-05-02 09:50
Willing to test, of course.
Right now I am trying the way through heroku/nightscout bridge, but this is lagging behind and the watch complications just show "null".

**Comment by tolot27** [comment] 2020-01-19 00:16
Isn't this a duplicate of #220?

**Comment by tolot27** [comment] 2021-02-15 06:00
It is implemented already as Dex Share Follower.

**Closed** 2021-02-15 06:00 UTC
Labels: enhancement, sync-dexcom
