### ISSUE TITLE
Libre-2: no options to save calibrated values neither to upload them to Nightscout. Help needed

### ISSUE THREAD

**Issue by yosepito** [NightscoutFoundation/xDrip#1350] opened 2020-05-23 15:54 UTC
I have searched in the issues, but found no other like this.
The problem is that there is a number of countries in which Abott only sells Libre-2. Spain is an example. We cannot buy Libre-1, although I think it's better than L2 in several ways.

The options to use Libre-2 with Xdrip are essentially 2: use the patched app to capture the native data or use a third party bluetooth connector to send the data to Xdrip with OOP algorithm running in the background. In both cases, we cannot calibrate data.

OOP simply rejects calibrations. It yields the current value calibrated, but when the next read arrives it goes back to the native values. The first solution only allows a calibration by adding/subtracting 20 mg/dl to the native value. Furthermore, the native Libre-2 never will deliver a native value below 39. And the intercept of the calibration can never higher than 40 for that reason.

In my case, this has transformed my life in a nightmare. My current Libre-2 is reading very low values. I read this happens more than often, and even that Libre-2 is very sensitive to any hit or movement, so it will start behaving abnormally. 

Yet this Libre-2, I think, was not affected by that. However, it had been in range with finger pricks the first two days, and then started to change and go down. Sometimes, in the old calibration style of Xdrip the slope can be above 1, and some other moments it was below 1.

The only solution I found is to use L2 paired with MM2, OOP running in the background and activating as a secondary plugin the Xdrip algorithm in calibrations. The data showed on screen is from that plugin. It is the only way to use the sensor under these conditions. The problem is that new calibrations do not soften or adjust previous readings as it does Xdrip with L1. In addition, the data table contains only the native values, which are uploaded to NS.

In my opinion this is useless. I could live with this option I found provided the data uploaded to NS are free of error/bias or incorrections. To put it simply: now I'm 88, but the native reading is 58. And if I'm 70, the native reading is 39. And in case I'm below 70, the Xdrip will not yield an alarm, because in these conditions, the limitations imposed make it impossible to yield a native value below 39. 

My suggestion or question: **how can I tell Xdrip to upload the Xdrip calibrated values to NS instead of the native Libre-2 values?** I activated the option to enable the pluging to override all the other options, but it seems to change nothing. **Shouldn't this save the calibrated value of the plugin to the data table and upload these values to NS?**

I'm afraid that L2 has worsen what L1 yielded. This should serve as a warning for future users, since Abott seems to expand L2 in markets and will stop serving L1. If I don't found a solution for this, I will have to search for other alternatives, although their cost is higher.

Any help will be appreciated, since I believe that many people will suffer from this problem with L2

Thanks!

**Comment by silver77surfer** [comment] 2020-07-06 14:03
I would like to support the suggestion of yosepito. For me there is only Libre 2 available in Germany. I think the other countries will follow, sooner or later. I tried to use Libre 2, Bubble transmitter and OOP algorithm. It is only possible to calibrate with a plugin. And it is not possible, to send the calibrated values to nightscout, Nightscout only receives the non calibrated values, although you choose in seetings that the plugins shall be considered.

**Comment by yosepito** [comment] 2020-07-07 08:45
After using several Libre-2, I confirm the native data is massively lower than finger pricks. The limit of +-20 in the calibration is useless under these conditions. There is no reason for that. Developers: This is a "use at your own risk" project. We know that Libre-2 has a lower threshold of 40. However, there are a number of reasons why this does not hold.

Current sensor: the first 2 days, finger pricks were +20 above the native data. Now it's +35 or +40. I decided to shift from patched Libre app to OOP + MM2 and do activate Xdrip original algorithm to show my BGs. Yet the data table is still wrong with native data.

The plugins should be able to override native data if the user wants to use that. Please, anyone could help with this? Maybe @gregorybel or @jamorham ? Thanks

see also #1371

**Comment by tzachi-dar** [comment] 2020-08-30 11:21
We now have the possibility to calibrate libre 2 (using mm/blucon/bubble).
Should also work on android 10.
If anyone is interested to test this, please write here.

**Comment by silver77surfer** [comment] 2020-08-30 14:15
> We now have the possibility to calibrate libre 2 (using mm/blucon/bubble).
> Should also work on android 10.
> If anyone is interested to test this, please write here.

Hey there! Great news! At the moment I use Libre 2 patched app. But the calibration limit (+ 20 mg/dL) often is not enough for me. I have a MM 1 and a bubble. Both with the latest firmware. I am on Android 10. So I could do some tests. By the way: I hope there is also a smooth algorithm similar to the algorithm of the patched app?!

**Comment by tzachi-dar** [comment] 2020-08-30 17:48
Please see instructions here:
https://gitter.im/LibreOOPAlgorithm/Lobby

**Comment by yosepito** [comment] 2020-08-31 08:49
just to not duplicate this:
see my comments in https://github.com/NightscoutFoundation/xDrip/issues/1371#issuecomment-683652026

I suggest using that link to post comments in a unified way

thanks to @tzachi-dar

**Comment by tolot27** [comment] 2020-10-24 16:04
Isn't this a duplicate of #1335, is it?

**Comment by patanito** [comment] 2020-12-09 11:28
@tolot27 it is. I think it can be closed. See:
https://github.com/NightscoutFoundation/xDrip/issues/1371#issuecomment-741710603

**Comment by tolot27** [comment] 2020-12-09 12:28
@tzachi-dar Will the upload also fixed with your PR #1524?

**Comment by Navid200** [comment] 2021-07-08 03:42
Can we close this if it is a duplicate?

**Comment by tolot27** [comment] 2021-07-08 07:31
Calibrated values will be uploaded to NS if #1090 gets merged.

**Comment by tolot27** [comment] 2021-07-08 07:35
Closing this because Libre2 calibration now possible and sync of calibrated values is requested earlier with #475 and will be merged with #1090.

**Closed by tolot27** 2021-07-08 07:35 UTC
Labels: bug, calibration, device-libre, sync-nightscout
