### ISSUE TITLE
Bug: Connection atempts when phone in Flight Mode and Bluetooth in ON

### ISSUE THREAD

**Issue by jofrep** [NightscoutFoundation/xDrip#287] opened 2018-01-30 19:56 UTC
When the phone is in Flight mode and the Bluetooth is ON, the device stills tries to connects to the cloud generating error warnings periodically.
The expected behavior should be that in this case the cloud uploads should be paused.

Error message: Unable to do a REST API Upload: Unable to resolve host xxxxx.kerokuapp.com ....
Phone: Google Pixel XL
Android 8.1.0
App version: 20a4313-2017.11.13

**Comment by Navid200** [comment] 2021-02-12 01:45
@jofrep This does not interfere with proper operation of xDrip as a CGM, does it?
I also get the error when I don't have WiFi coverage because I have not given data access to xDrip.
I think this is the expected behavior.
Would you pleaser close this issue, or explain why this is necessary?
Thanks

**Comment by Navid200** [comment] 2021-02-23 19:46
Closing due to inactivity

**Closed by Navid200** 2021-02-23 19:46 UTC
