### ISSUE TITLE
All alerts currently disabled

### ISSUE THREAD

**Issue by JayBouch1977** [NightscoutFoundation/xDrip#821] opened 2019-03-08 15:54 UTC
Hi all,

It's been a week now i am trying to fix this issue.  There is a message in the upper left corner of Xdrip plus app saying: ''All alertes currently disabled''.  
So there is no alerts at all, neither for high or low glucose level.
I tried uninstalling and re-installing the application -- nothing happened

Could someone tell me how to re-enable the alerts?

Thank you very much!!!
![screenshot_20190308-105057_xdrip](https://user-images.githubusercontent.com/36271953/54039514-1f239600-4191-11e9-902d-114b94b85b81.jpg)

**Comment by philippebourget** [comment] 2019-03-09 01:00
Hi @JayBouch1977. I was able to reproduce the screenshot. The problem is that you've selected to snooze all alerts somehow. Here are the steps to reactivate the alerts:
1. Menu > Snooze Alert 
1. Select `Re-Enable All Alerts`

Hope this helps!

**Comment by Navid200** [comment] 2021-02-07 20:54
@JayBouch1977 Would you please close this issue if the problem has been resolved?
Thanks

**Comment by Navid200** [comment] 2021-02-18 02:00
Closing due to inactivity

**Closed by Navid200** 2021-02-18 02:00 UTC
