### ISSUE TITLE
Plugin Override ALL setting disabled

### ISSUE THREAD

**Issue by bszabo84** [NightscoutFoundation/xDrip#1390] opened 2020-07-24 17:12 UTC
I was looking at the settings in the app and was trying to turn on the "_Less common settings->Advanced Calibration->Plugin Override ALL_" setting (to solve calibration problem of Libre2+MM2+OOPalgorithm mentioned in #1350 ), but it is disabled and can't change it. I read a discussion from 2 years ago that it wasn't implemented at that time yet. Is there any working implementation since then, can I somehow turn this feature on?

**Comment by silver77surfer** [comment] 2020-07-29 17:42
I would like to support the suggestion of bszabo84. A calibration feature for Libre 2 with OOPalgorithm would be great.

**Comment by Enduser99** [comment] 2020-09-08 21:18
Anything at all on this? I would like to enable this feature very much as I believe it may solve the issue of my watch and nightscout uncalibrated readings being 30 points lower than my calibrated and fingerstick readings. Please help.

**Comment by revolt5150** [comment] 2020-10-12 05:03
I agree with those above. mm2/US14. Cant figure out a workaround for the 30 point difference b/t Datriscae calibration (which matches fingersticks) and OOPalgorithm with only show the raw BG level and sends that to the NS and Wear OS watch.

**Comment by tzachi-dar** [comment] 2021-08-06 13:38
Right now it is possible to calibrate with the oop2. It is not practically possible to calibrate with oop1.
For more information on the oop2 please see: https://www.minimallooper.com/post/how-to-setup-freestyle-libre-2-and-oop2-to-use-a-native-bluetooth-connection-in-xdrip

**Comment by Navid200** [comment] 2021-08-06 13:41
@bszabo84 
Please have a look at what tzachi-dar posted above.
Can we close this issue?

**Comment by Navid200** [comment] 2021-09-21 01:36
Closing due to inactivity

**Closed by Navid200** 2021-09-21 01:36 UTC

**Comment by aptash** [comment] 2023-12-31 17:56
How to enable this "Plugin Override ALL" setting anyway?
Closing the issue doesn't mean we can enable this setting.

**Comment by Navid200** [comment] 2023-12-31 18:20
@aptash 
There are some settings in xDrip that have been added for test only.  Sometimes, developers are not sure how practical or safe something may be on all devices that they have not been able to test yet.  That's just an example scenario.
In that case, the setting is placed behind engineering mode.  That means the setting is not recommended to be used.

Either more testing will prove that it is safe at which point, it will be removed from engineering mode.
Or, it will be confirmed that it will never be dependable enough to be released for use by all.  In that case, it will be removed.
Until either one of those two happens, the setting will be behind engineering mode for more testing only.

**Comment by aptash** [comment] 2024-01-01 09:55
@Navid200 thanks a lot for the detailed explanation!
The thing is I enabled the engineering mode but the setting "Plugin Override ALL" is still disabled.
I'm sorry that I didn't mention that in the first place.

https://github.com/NightscoutFoundation/xDrip/assets/5793551/3eaa8b73-049c-42fd-8125-288d7b4a02f3

**Comment by Navid200** [comment] 2024-01-01 13:55
@aptash 
Issues are not meant for conversations.  Please open a discussions and I will answer your questions.
Engineering mode is to be used by those who know what they are doing, mainly, developers,  
If you need help with using xDrip, it means you should not be enabling it.
