### ISSUE TITLE
Importing data didn't display data and wiped settings

### ISSUE THREAD

**Issue by SimonPhilpott** [NightscoutFoundation/xDrip#1705] opened 2021-04-22 07:54 UTC
I recently wiped the phone app data and cache in order to fix battery drain on my smartwatch SW3, usually this would involve saving all settings to SD card and exporting my database prior to this so that I can restore both. 

However once the app storage was cleared, after restoring settings via the popup message I was prompted with the import database prompt which I accepted. Despite the import data success message, nothing was imported also the settings that were recently restored were wiped. I attempted to import the database again, but again the screen remained blank and no data points were restored - also my settings were once again cleared. 

I'm using the latest stable release, 17cbcf0-2021.03.08.

I'm using Libre > MiaoMiao 1 > Galaxy Note 10+ running the latest Android 11 release.

Looking in the log files for all of the recent data points I can see a lot of errors;

"Bg data was not calculated, working on raw data" followed by
"Error getting data from getLatestBgForXMinutes. Returning", "libreBlock exists but no matching bg record exists"

This might be impacting the import as the data is not in the right format to display?

Steps to reproduce;

1) Save settings to SD card
2) Export database 
3) Wipe app data
4) Restore settings, either manually via Load settings from SD Card, or from the popup message
5) Import database either manually via import database or from the popup message

**Comment by Navid200** [comment] 2021-04-22 12:09
@SimonPhilpott Would you please describe the issue you are experiencing in the following open issue?
https://github.com/NightscoutFoundation/xDrip/issues/1045

**Comment by SimonPhilpott** [comment] 2021-04-22 12:59
@Navid200 No worries, done.

**Comment by pcastelo** [comment] 2021-05-05 15:55
Hi guys , i have the same issue with android 11, i test same version xdrip with older android (10) and work without any problem. 
i have meesage the import was success but i dont have data

Android 11
![b4d83703-aad5-4c44-b4be-c41240cf0764](https://user-images.githubusercontent.com/10425803/117170750-aa643a80-ada0-11eb-9ff6-22e11272b2bf.jpg)
![c2042e97-7b6b-449d-9f44-9f1fff543ae4](https://user-images.githubusercontent.com/10425803/117170765-ad5f2b00-ada0-11eb-90fd-8970b586180c.jpg)

Android 10: 

![a4a73ecc-c67b-4af3-ad85-84b2c715bee9](https://user-images.githubusercontent.com/10425803/117171189-09c24a80-ada1-11eb-9f99-6cd6563cf41d.jpg)
![9ed62320-e1e6-410d-8539-5da02cc7ca25](https://user-images.githubusercontent.com/10425803/117171197-0b8c0e00-ada1-11eb-8a2b-a4be1a0db1f9.jpg)


 i use same import  in both phone as you can see in 11 only i see new ones after config again

**Comment by tolot27** [comment] 2021-05-05 20:24
Does xDrip has storage permission before importing the database?

**Comment by pcastelo** [comment] 2021-05-05 22:10
> Does xDrip has storage permission before importing the database?

yes , i try severals times , in one i delete all folder  , create new  one (export) only to generate folder and copy to xdrip folder the original export and do import only for check permisons and the error persist

![WhatsApp Image 2021-05-05 at 19 01 57](https://user-images.githubusercontent.com/10425803/117215634-df8a8000-add4-11eb-86fd-3752f850aa78.jpeg)

**Comment by pcastelo** [comment] 2021-05-06 12:21
some more info , i was trying to debug with Samsung  Remote Lab (emulating Galaxy S10 with Android 11)
I see the following error in phone logs: 

ERROR|05-05 23:16:30.128|1168|1432||WindowManager|win=Window{9d8798b u0 com.eveningoutpost.dexdrip/com.eveningoutpost.dexdrip.ImportDatabaseActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5227 com.android.server.wm.ActivityRecord.destroySurfaces:5208 com.android.server.wm.WindowState.onExitAnimationDone:5616 com.android.server.wm.WindowStateAnimator.onAnimationFinished:332 com.android.server.wm.WindowState.onAnimationFinished:6081 com.android.server.wm.-$$Lambda$dwJG8BAnLlvKNGuDY9U3-haNY4M.onAnimationFinished:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0$SurfaceAnimator:112 


ERROR|05-05 23:16:30.164|9520|30418||SQLiteLog|(1) Stat of /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db : st_mode (100600) st_uid (10318) st_gid (10318) st_ino(1180777) st_size(11894784)
WARNING|05-05 23:16:30.164|9520|30418||SQLiteLog|(28) file unlinked while open: /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db
ERROR|05-05 23:16:30.164|9520|30418||SQLiteLog|(1) File name of fd(67) : /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db.old (deleted)�����������������������������������������������������������������������������������������������������������������
ERROR|05-05 23:16:30.164|9520|30418||SQLiteLog|(1) Stat of /data/user/0/com.eveningoutpost.dexdrip : st_mode(40751) st_uid(10318) st_gid(10318) st_ino(1179665)
ERROR|05-05 23:16:30.164|9520|30418||SQLiteLog|(1) fileHasMoved : original inode of /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db is (1180510)
ERROR|05-05 23:16:30.164|9520|30418||SQLiteLog|(1) Stat of /data/user/0/com.eveningoutpost.dexdrip/databases : st_mode(40771) st_uid(10318) st_gid(10318) st_ino(1180505)
ERROR|05-05 23:16:30.165|9520|30418||SQLiteLog|(1) Stat of /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db : st_mode (100600) st_uid (10318) st_gid (10318) st_ino(1180777) st_size(11894784)
ERROR|05-05 23:16:30.165|9520|30418||SQLiteLog|(1) fileHasMoved : original inode of /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db is (1180510)
ERROR|05-05 23:16:30.165|9520|30418||SQLiteLog|(1) Stat of /data/user/0/com.eveningoutpost.dexdrip : st_mode(40751) st_uid(10318) st_gid(10318) st_ino(1179665)
WARNING|05-05 23:16:30.165|9520|30418||SQLiteLog|(28) file unlinked while open: /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db
ERROR|05-05 23:16:30.165|9520|30418||SQLiteLog|(1) File name of fd(6) : /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db.old (deleted)������������������������������������������������������������������������������������������������������������������
ERROR|05-05 23:16:30.165|9520|30418||SQLiteLog|(1) Stat of /data/user/0/com.eveningoutpost.dexdrip/databases : st_mode(40771) st_uid(10318) st_gid(10318) st_ino(1180505)

**Comment by Navid200** [comment] 2021-05-07 02:38
I see the same issue in Android Studio virtual device set up as Galaxy Nexus Android 11.
But, not in the same set up as Pixel 4 Android 11.

**Comment by pcastelo** [comment] 2021-05-18 16:20
i can replicate with de import of @SimonPhilpott too , i am trying to solve the issue

**Comment by SimonPhilpott** [comment] 2021-05-19 20:57
@Navid200 sorry had some family things come up. I'll see if I can find a time that's convenient to wipe data and calibrations in order to do some more testing. I've got an endio appointment so I'd like some data there at least to run a report with.

**Comment by Navid200** [comment] 2021-05-19 21:04
@SimonPhilpott 

Please don't do anything that could compromise your diabetes control in order to perform any xDrip tests.

**Comment by Navid200** [comment] 2021-05-30 21:21
@pcastelo Another user has confirmed that importing the file three times worked for them.
Thanks

**Comment by pcastelo** [comment] 2021-06-06 14:36
ty @Navid200 , i have some problem the last week , i will try to solve this  on the next days :D

**Comment by SimonPhilpott** [comment] 2021-06-22 07:56
@Navid200 So I had to flush my data today which gave me the opportunity to test out the import database X3, it didn't work but I did just update to the latest nightly which I'll try again to test import at anbother time soon.

**Comment by Navid200** [comment] 2021-06-26 02:15
I just tried the virtual device in Android Studio.  I set up an Android 11 Pixel 4 XL device.
I attempted to import a database I had exported from xDrip on an Android 9 device.
It shows that everything imported properly.  However, there were no readings.  I imported the same file a second time.  Again, it reported that the import had succeeded.  Yet, there were no readings.
I imported the same file a third time.  All readings showed up.  

So, I can confirm what @pcastelo has suggested.  But, I don't know what causes this behavior.
And I am not sure why it does not work for @SimonPhilpott.

**Comment by Navid200** [comment] 2021-08-28 00:06
I finally have an Android 11 device.
I experienced the exact same problem.
Thanks so much @pcastelo for finding out that importing 3 times solves it.

I wonder why though.
What should we do to xDrip to resolve this so that it would work the first time?

**Comment by thedewi** [comment] 2021-11-09 02:51
I have also found "restore" was empty the first 2 times I run it.

But I have found a solution: after xDrip+ asks for file permission, I "force stop" the app. Then I restore and it works. Maybe the permission takes some time to be granted, and this is causing the problem?

The restore routine should probably check for this condition, and report the problem instead of claiming success.

**Comment by taisatk** [comment] 2021-11-14 19:07
Hi all! I followed @thedewi instructions and it worked fine! I'm on Android 11 - Moto G60 Latin America (XT-2135-1) and I was struggling to get the database restore done before finding this thread.
In addition, I noticed that right after granting file access permission (on that system dialog), xDrip still displays a toast informing I need to grant file permission.

**Comment by capsuleman** [comment] 2022-07-21 15:05
Thanks for the workaround! :-)
I had the same issue, and I had to first restore my database and the restore my settings. Else, it wasn't working.

**Comment by yosepito** [comment] 2022-07-27 12:22
Yesterday I had to perform a backup to clean the app store (it occupied 3 GB and every time I turned on internet/data/wifi a message warning Xdrip stopped appeared). I saved settings and export database, and cleaned the store. After that , Xdrip detected settings and backup and asked for restoring. I did, several times (more than 3 times) and everytime I restored data, I could see the data for some seconds and after that it asked for connecting a device and data dissapeared. Fortunately, I had uploaded previously to NS site, so nothing is lossen. But the backup (import) section requires a review. I think it could be useful to select the date since one wants to backup data.
My setting: only 30 days of retention of data, android 9, Xdrip version e557cba-2022.05.19, working with a libre-2 direct connection BT.

Backup files are fine, the issue is that restoring data does not work (whereas restoring settings works fine). I tried to restore data before settings but it reproduced the problem of disseparing restored data. Now working with a fresh Xdrip with only 50MB of store space used.

**Comment by Navid200** [comment] 2022-07-27 12:45
@yosepito The message you get that xDrip has found a backup is about the settings, not the database.

To restore the database, you need to restore the database manually.
https://navid200.github.io/xDrip/docs/Restore-Database.html

**Comment by Navid200** [comment] 2022-09-09 00:50
A new backup mechanism has been added to xDrip.  Please try it when you get a chance and let us know if its restore has the same issue on Android 11 (and 12?) or not.
https://github.com/NightscoutFoundation/xDrip/discussions/2314

**Comment by pcastelo** [comment] 2022-09-09 01:17
tomorow on morning i wil try  this and let you know

**Comment by nhatier** [comment] 2022-09-15 04:41
The 3-4 imports trick doesn't work for me on Android 12. I just replaced my old Android 9 phone and have been unable to restore my old data on the "new" one (S20).

I tried the Cloud backup, I was hoping to restore my old backup by hacking my way around it but since it uses CipherOutputStream it's probably hopeless from my end.

Is there any hope for me to get my history back on my new phone? Manually merging an old database with a new one is not a problem for me, I did it a few times in the past. But if I can't import, and if cloud backups are encrypted, this skill is useless.

**Comment by Navid200** [comment] 2022-09-15 12:34
@nhatier Are you sure the backup you have created is valid?  I mean have you tried restoring it onto a test phone that is also Android 9 or older?  Does it work there?

Can you explain why backup to Google Cloud is not working for you in more detail?  That is supposed to be the eventual solution for all.  So, if something is wrong with that solution, please let's hear it.

**Comment by nhatier** [comment] 2022-09-15 14:36
Yes, I'm sure the backup is valid. I had several of them, and I even tried with the automatic b4import backup to restore one day worth of data and everything stayed blank, even the alarms list got wiped. I tested my backup on my old phone before wiping it.

Google Cloud backup is likely doing its job properly, I didn't try to restore from it yet. However the fact the database is encrypted prevents me from copying my old database to google drive and restoring it on my phone using that method, or using a modified (merged or cleaned up) database as I could before with the standard zip import. Don't get me wrong, I do not request any additional feature for the cloud backup as it seems to work well for its intended purposes. 

But it would really help if the standard backup restore method was working. And meanwhile, if it can't work, maybe block it on affected devices so people don't completely lose all their data.

I may try reinstalling xdrip on my old phone, import a merged database, save to cloud, and import on my new phone, but that seems a lot of work for my busy days right now.

**Comment by nhatier** [comment] 2022-09-15 16:12
I remembered I have a very old Android 5.5 tablet, but I got all sorts of issues with the cloud backup - full app crash, a "Backup failed" error with "Output IO Error java.io.IOException: write failed: EBADF (Bad file number)" in the logs, file on Drive appearing OK though being corrupted and wiping everything when attempting to restore. Just so you know, maybe the Cloud Backup could be disabled on older Android versions so it don't cause issues in the future.

So I took the long route of reinstalling my Android 8 phone, restored the zip backup containing a merged database, uploaded to cloud, and finally restored on my Android 11 phone, and yes, it did work. I have all my data back, thank you!

Trust me, I really would like to help with xDrip, but Java is not one of the many languages I can write, I can only read java code, and Android is not a platform I know enough to debug such an intricate issue.

**Comment by jamorham** [comment] 2022-09-15 16:24
It may be possible to improve the existing data import to make it more stable based on what I've learned doing the cloud backup work.

**Comment by jwoglom** [comment] 2022-10-15 04:58
I have also experienced this for a long time whenever i reimport my large xDrip database (see #1405) and I tracked down a potential solution in https://github.com/NightscoutFoundation/xDrip/pull/2381. @jamorham PTAL.

**Comment by air-ship** [comment] 2022-10-22 17:30
I can confirm that attempting the following on a Galaxy S10e / A12 is not working:

1. Cloud backup appears to stall with no data written to Google My Drive > xDrip-Backups.
2. The export database > restore database from a local file will not restore the database. I tried the suggested x3 / x4 import method with no success.

Thought I would feed this back because my old Sony Xperia is on its last legs so I have to replace it imminently.

**Comment by air-ship** [comment] 2022-10-23 11:13
Update:

- I managed to get my Sony Xperia L3 to make a Google Drive cloud backup. It just took a long time even thought he database is only 104Mb.
- Then I tried to import the cloud backup (using the Cloud Backup option) into xDrip+ on my Galaxy S10e running Android 12. No joy. xDrip+ can't locate the backup.
- Tried the import database zip file again but x8 times. No joy. No data imported.

**Comment by air-ship** [comment] 2022-10-23 12:50
> The Google Drive backup was never meant to be able to restore backups created with the previous method.
> 
> We have been aware of the original database restore issues, on some Android 11 phones and now Android 12. But, it has not been fixed because no one could come up with a solution. If you have a solution, please open a PR.
> 
> The solution is to switch to the new backup methodology to Google Drive. That means when you buy a new phone, backup the database from the old phone using the new backup methodology, Google Drive Backup. Then, restore it on the new phone using the Google Drive Backup methodology. If you do that and it doesn't work, please let us know.

So I'm pretty persistent, especially when it comes to my diabetes. I've posted notes on how I got the cloud backup from my old phone to import into my new phone. I hope this is useful for others when trying to export / import the database. Thanks for everyones help here.

**Comment by air-ship** [comment] 2022-10-23 14:33
Another update with a successful outcome...

Phones: Old phone > Sony Xperia L3 / Android 8.1. New Phone > Samsung Galaxy S10e / Android 12
Version: xDrip+ nightly build 8th September 2022 / xDrip-plus-20220908-4aeee42.apk

Here's how I managed to restore a cloud backup. Not quite the way I thought it would work. I suggest you read through the steps and comments to get an overview of the process.

1. On my old phone I made a cloud backup in xDrip+ > There dots menu > Import / Export features > Cloud Backup. I tried it with my primary Google account and couldn't get a backup to complete. No idea why so I can't advise on troubleshooting this. I then tried another Google account and managed to successfully create a backup: xDrip-Backups/xdrip-backup-I3312-Xperia-L3.xdrip
2. On the new phone I tried the standard cloud backup restore but this didn't work because xDrip+ writes an empty file with the name of the new phone (xdrip-backup-SM-G970U1-Rees's-S10e.xdrip). The xdrip-backup-I3312-Xperia-L3.xdrip is never found by xDrip+. No idea why even though the file exists. Read on.
3. So I downloaded the backup file > xdrip-backup-I3312-Xperia-L3.xdrip. Next I There dots menu > Import / Export features > Cloud Backup > SELECT BACKUP LOCATION grey button. I had uploaded xdrip-backup-I3312-Xperia-L3.xdrip to my S10e's Download directory (could be whatever directory you want). Next, in SELECT BACKUP LOCATION I chose USE ALTERNATE FILE. Navigated to my S10e's Download directory and chose the file xdrip-backup-I3312-Xperia-L3.xdrip.
4. Once I completed step 4 xDrip+ then recognised the backup and listed in the info about the backup above the three grey buttons in Cloud Backup. At this stage you know you have your backup selected for restore. Now tap the RESTORE FROM BACKUP grey button. Choose "YES" in the "Backup Source Confirm", "Are you really sure?" > YES. The restore now runs and in my case it was successful. xDrip+ restarts and (hopefully) your data is imported.
5. My final test was to forget my MiaoMiao on my old phone (in xDrip+ > System Status) and my new automatically connected to the MiaoMiao because I had tested this previously.
6. I then went back to the step 1 and tested it again. Success!

Notes:
1. When you perform your cloud backup it's worth setting your screen display timeout to 30 minutes (if possible). I found if my phone slept then the backup didn't complete. Could just be my old phone's eccentricity.
3. Be patient when xDrip+ makes the cloud backup. My phone took about 15 minutes to upload 110MB.
4. The cloud backup file is overwritten each time when you backup. Keep this in mind if you are testing everything before a full commit. It might be worth backing up each cloud file either in your Google Drive or locally on your computer.
5. I understand that the xDrip+ versions should match on each phone. I guess this is because additional data may be written to the database file which means that a newer version of xDrip+ is expecting additional data (which may make the database incompatible).
6. Be patient. It's not a quick process. After all, the data in xDrip+ is valuable, especially when it goes back over three years as it does in my case.
7. Unrelated to databases but you will find if switching manufacturers phones that your alert settings for low bg / high bg / calibration etc will lose their sound files. In y case I used the Sony alerts and my Samsung doesn't have these. I had to go Google hunting to find them. This took ages. I'm 54 so I'm a creature of habit and my brain is subconsciously trained to the alert sounds, especially at night.

I hope this helps.

**Closed** 2023-01-18 16:36 UTC
Labels: bug, database, android11+

**Comment by Navid200** [comment] 2023-01-18 17:56
As of the release of January 18, 2023, there should be no need to import three times. It should work the first time.
