### ISSUE TITLE
Latest nightly still not working with my Gear 2 watch

### ISSUE THREAD

**Issue by dave1812** [NightscoutFoundation/xDrip#787] opened 2019-02-19 21:06 UTC
**I complained August 13, 2018 about this issue**.   There have been about 190 nightly builds (give or take) and yet this problem persists.   Do you developers not understand how USEFUL it is to have CGM data on a watch instead of a phone????   WHY won't you fix this?  I told you back in August that the 7/15/18 build works fine and shortly after that build, ALL subsequent builds don't send data to my watch via Android Notifications.  Same watch; same phone: Gear 2 and Samsung S7.  The newer builds also don't work with my wife's phone/watch, so she too, is stuck on the 7/15/18 version.

  Can't you look at the code that is involved with android notifications, to fix this?  I don't want to be stuck for the forseeable future with a very old version of xDrip+.  for gawds, sakes, how about somebody take a look at the code that involves android notifications and see what changed between 7/15/18 and a week or two later.

**Comment by dave1812** [comment] 2019-04-13 22:40
actually, the 8/5/18 version still works, and the 8/9/18 version broke the code for sending data thru android notifications, to my Tizen watch (Gear 2).

**Comment by Navid200** [comment] 2021-02-07 20:33
@dave1812 If the problem is resolved, would you please close the issue?
Thanks

**Comment by Navid200** [comment] 2021-02-18 01:33
Closing due to inactivity

**Closed by Navid200** 2021-02-18 01:33 UTC
