### ISSUE TITLE
Problem adding treatment with more than 2 decimal 

### ISSUE THREAD

**Issue by filipedanunes** [NightscoutFoundation/xDrip#918] opened 2019-06-18 08:05 UTC
**Problem:**
When adding a treatment with 3 or more decimal places, the last 2 or 3 are considered as units of insulin:
 + 3.125 » 25 units
 + 0.148 » 48 units
 + 1.2563 » 563 units
(the same for carbs with specific differences)

<img src="https://user-images.githubusercontent.com/16206915/59666375-99aa7b80-91ac-11e9-8e2e-a6d032a56333.png" width="300"/><img src="https://user-images.githubusercontent.com/16206915/59666377-99aa7b80-91ac-11e9-990e-4c8e5dbdac18.png" width="300"/><img src="https://user-images.githubusercontent.com/16206915/59666378-9a431200-91ac-11e9-9371-04f79ca9b2c3.png" width="300"/><img src="https://user-images.githubusercontent.com/16206915/59666379-9a431200-91ac-11e9-85c4-5ede0d1cde62.png" width="300"/>

Not a major problem, but a user reported his son was instroducing values like this taking a huge imapact in what he was receiving as a follower

I think the problem is at Simulation.class
  `private void createTreatment(String allWords) {
   allWords = allWords.replaceAll("([0-9].[0-9])([0-9][0-9])", "$1 $2");   
 }`

**Suggestions:**
 + Assuming we want a maximum of 2 decimal places (truncate)
  `allWords = allWords.replaceAll("([0-9].[0-9]^{0,2})([0-9]?)([0-9]?)","$1")`
  _or_
  `allWords = allWords.replaceAll("([0-9].[0-9][0-9])([0-9]?)([0-9]?)", "$1");`
  + Accepting all decimal places
    `allWords = allWords.replaceAll("([0-9].[0-9])([0-9]))", "$1");`

All help and suggestions will be more than welcome.
Thank you

**Comment by Navid200** [comment] 2021-02-10 18:18
@filipedanunes Is this still the case?
Thanks

**Comment by tolot27** [comment] 2021-02-11 06:31
I could not reproduce this behavior with insulin units but with carbs.

**Comment by filipedanunes** [comment] 2021-02-11 16:04
hello, just tested on versionb978bec-2020.11.27 and it seems solved for units. Could also reproduce this behavior for carbs

**Comment by Navid200** [comment] 2021-02-19 19:36
Duplicate: https://github.com/NightscoutFoundation/xDrip/issues/565

**Comment by Navid200** [comment] 2021-03-15 16:39
I am closing this because it represents the same bug reported in https://github.com/NightscoutFoundation/xDrip/issues/565.
If I  am mistaken, please let me know.

You can post in that existing issue if you like.

**Closed by Navid200** 2021-03-15 16:39 UTC
Labels: bug, carbs, duplicate, ui
