### ISSUE TITLE
Tidepool Upload Duplication

### ISSUE THREAD

**Issue by DunePlodder** [NightscoutFoundation/xDrip#865] opened 2019-04-26 20:02 UTC
I usethe xDrip+ upload to Tidepool.
I now have a a t:slim x2 pump & upload from it.
The only problem is that data gets duplicated - carbs & boluses.
I want to upload CGM data & notes from xDrip, especially as the x2 is not yet integrated with the Dexcom G6.
Would it be possible to choose whether to upload carbs & boluses?

**Comment by PaperT1D** [comment] 2019-05-01 10:02
I have a similar problem (using Medtronic's 723), except only boluses seem to be duplicated. The only reason I manually upload  the pump to Tidepool at all is because xDrip doesn't upload basal data but, when I upload from the pump, my bolus amounts are duplicated and this makes my reported daily insulin doses way more than it is. I'd like to be able to select what information is uploaded to Tidepool as well if it's at all possible.

**Comment by psonnera** [comment] 2019-11-16 13:15
Same problem with manual uploading from the PDM (Omnipod). I guess we need a flag to choose treatments upload for those of us who use xDrip+ to log them. Either this or get it done directly from Nightscout the same way Dexcom is integrated with Dex Share.

**Comment by Navid200** [comment] 2021-08-07 18:42
@psonnera Is there anything we can change in xDrip to remedy this?
I'm not 100% understanding the problem.
If the cause of duplication is that two apps upload the same data, can we not disable uploading in one of them so that only one uploads?

**Comment by psonnera** [comment] 2021-08-07 19:27
It's been fixed. This is a duplicate. You can now select to upload only BG if you upload pump treatments manually.

**Comment by Navid200** [comment] 2021-08-07 19:30
@DunePlodder Considering what @psonnera has stated, is your issue resolved now?
If yes, would you please close it, or let me know and I will.

Otherwise, would you please explain why what has been explained does not work for you?

**Comment by Navid200** [comment] 2021-08-11 14:14
We can reopen if/when more data is provided.

**Closed by Navid200** 2021-08-11 14:14 UTC
Labels: sync-tidepool
