### ISSUE TITLE
Workaround for android 10 BT issues

### ISSUE THREAD

**Issue by 17gubbar** [NightscoutFoundation/xDrip#1067] opened 2019-10-23 19:02 UTC
Found workaround for android 10 connection issues. Still getting wierd error msg every reading in the log BUT , managed to solv the reconnecting issues when it looses connection and cant connect back. Problem seems to be the bluetooth getting stuck in scanning mode since it cant close bt connection properly for some reason in android 10.. Tick this box and it should work for now.. It's not ideal and draws some more battery but only thing i found working fiddling in xdtrip
![Screenshot_20191023-204148__01](https://user-images.githubusercontent.com/34807314/67425476-59369080-f5d8-11e9-86e7-6ce1321ee284.jpg)

**Comment by edisiENt** [comment] 2019-11-03 19:11
These options have no positive effect on OnePlus 7Pro running Android 10.0.1.

**Comment by borijess** [comment] 2019-11-03 19:16
> These options have no positive effect on OnePlus 7Pro running Android 10.0.1.

Same for me did not fix anything on my OnePlus 7 pro. Android 10 beta 4

**Comment by 17gubbar** [comment] 2019-11-04 20:12
I'm on oneplus 7t and im back to having problems again 🤪

**Comment by edisiENt** [comment] 2019-11-04 20:40
Try staying connected to power & see if Xdrip stays connected to your G6.


On Mon, Nov 4, 2019, 12:12 PM 17gubbar <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm on oneplus 7t and im back to having problems again 🤪

**Comment by borijess** [comment] 2019-11-12 01:04
So I don't know if it's fixed for sure. But for the last 24hrs I have not had a missed reading.  This is what I did. I uninstalled the stable version I was using. I installed the nightly Nov. 2nd nightly. I cleared the data for the Bluetooth in system apps. I am using these settings. Also I am on the OnePlus 7 pro Android 10 beta 5. I have tried xdrip on all the beta version up to 4 and nothing worked to fix the Bluetooth issue. So maybe beta 5 fixed for me. So I am posting this so you guys can check if it's the Nov 2nd nightly or did OnePlus fix the issue with the latest beta version. 
![Screenshot_20191111-172406](https://user-images.githubusercontent.com/18737358/68633052-14ef2f80-04b6-11ea-8b92-cbd91128a437.jpg)
![Screenshot_20191111-172425](https://user-images.githubusercontent.com/18737358/68633062-1a4c7a00-04b6-11ea-896c-a7249e2532ab.jpg)

**Comment by borijess** [comment] 2019-11-12 11:19
> So I don't know if it's fixed for sure. But for the last 24hrs I have not had a missed reading. This is what I did. I uninstalled the stable version I was using. I installed the nightly Nov. 2nd nightly. I cleared the data for the Bluetooth in system apps. I am using these settings. Also I am on the OnePlus 7 pro Android 10 beta 5. I have tried xdrip on all the beta version up to 4 and nothing worked to fix the Bluetooth issue. So maybe beta 5 fixed for me. So I am posting this so you guys can check if it's the Nov 2nd nightly or did OnePlus fix the issue with the latest beta version.
> ![Screenshot_20191111-172406](https://user-images.githubusercontent.com/18737358/68633052-14ef2f80-04b6-11ea-8b92-cbd91128a437.jpg)
> ![Screenshot_20191111-172425](https://user-images.githubusercontent.com/18737358/68633062-1a4c7a00-04b6-11ea-896c-a7249e2532ab.jpg)

I think I might of spoke to soon. The watch was 💯 capture rate while next to watch. Today I tried walking away from watch for more than 10 minutes. It has been 36 minutes and it has not reconnected. So upset thought the issue was fixed. I will let you know if it reconnects on its own. 
![Screenshot_20191112-051047](https://user-images.githubusercontent.com/18737358/68667579-f3209780-050b-11ea-8b02-568381abb5a4.jpg)

**Comment by borijess** [comment] 2019-11-12 11:31
It reconnected after 45 minutes. I did nothing just sat there and waited.

**Comment by borijess** [comment] 2019-11-12 17:42
> It reconnected after 45 minutes. I did nothing just sat there and waited.

It disconnected again 50 minutes later I did the forget and restart collector. So it is not fixed.

**Comment by Ferdinandoz** [comment] 2020-01-10 15:50
Are there any news? Got the same problem with my xiaomi mi 9 on android 10; now with Huawei P30Pro and dont wanna update to Android 10 because of this problem

**Comment by edisiENt** [comment] 2020-01-10 16:24
Yes, there is what appears to be a solution for Dexcom/G6 BT connectivity problems to several different Android-10 devices.  Nightly & Beta releases after 22-December seem to have solved the problem for me & several others.  See Issue https://github.com/NightscoutFoundation/xDrip/issues/1061# for details.

**Comment by Ferdinandoz** [comment] 2020-01-11 18:19
@edisiENt okay, thank you! Can anyone confirm running xdrip+, Dexcom G6 (with 8G.. transmitter) on Huawei P30 Pro / Android 10?

**Comment by Pamalosebi** [comment] 2020-01-13 10:41
@Ferdinandoz I am having a Mate 20 Pro with (now) Android 10 / EMUI 10. Immediately Update to Android 10 the [DexcomAPP2.4](https://github.com/dexcomapp/dexcomapp/tree/master/2.4) basically stopped working. So I tried xDrip-plus nightly and it didn't work either. To make it work I had to do exactly as [here] (https://github.com/NightscoutFoundation/xDrip/issues/1061#issuecomment-573432564) written.
Additionally, I had to **uncheck** the "Authenticate G5 before each read" and **check** "scan for G5 Constantly".

Till now its running fine.

**Comment by Ferdinandoz** [comment] 2020-01-18 09:08
@Pamalosebi Thanks for your advice, I will have a look at the other thread!

**Comment by Pamalosebi** [comment] 2020-01-18 09:42
Hey @Ferdinandoz ,
I had do go rollback to Android 9. With those settings above it might work on Android 10. But all in all it's way too unstable. It is also dangerous if you don't have valid measurements for over 6 hours at nights.
I guess it is some problem with the Bluetooth stack in Android 10. I had authorization errors before every single read of the Dexcom G6 in Android 10. While there are none errors within Android 9 procedures.

**Comment by Ferdinandoz** [comment] 2020-01-18 10:04
@Pamalosebi Okay, thank you very much for telling this right before my update 👍 I  remember such problems from back then when I owned a Xiaomi Mi 9 and updated to Android 10. Thats the reason for my concerns. I think I'll wait, can't have something like this right now. 😄

**Comment by VKostikov** [comment] 2020-01-25 20:21
Have the same issue with connection and read attempts :/
Samsung S10, Android 10.
First 3 hours I was playing with app settings and Android settings, as mentioned above and in the related topics. Nothing helped.
Half an hour ago I downloaded pre release night build 24.01.2020... Started praying

**Comment by VKostikov** [comment] 2020-01-29 11:05
It works. My proposal for those, who have the connection issue: use night build 24.01
No problems where found

**Comment by borijess** [comment] 2020-01-29 11:40
For some reason every update after the Dec 22nd version gives me the issue where I can select the check mark to input the amount of units I just injected. I have to use the voice to input that info. Has anyone else experience this? OnePlus 7 pro Android 10 beta 8.

**Comment by charding99** [comment] 2020-03-24 15:16
I was having issues with OnePlus 10.3.1  (7 Pro phone) where I would get overnight disconnects. If I left it plugged in, then I would not have disconnects. Two days ago, I decided to move to the Open Beta 11 version. For two nights, I have not had any disconnects and I am not plugging it in. Maybe I will be back to normal with Xdrip and Android 10.

**Comment by borijess** [comment] 2020-03-24 15:33
> I was having issues with OnePlus 10.3.1 (7 Pro phone) where I would get overnight disconnects. If I left it plugged in, then I would not have disconnects. Two days ago, I decided to move to the Open Beta 11 version. For two nights, I have not had any disconnects and I am not plugging it in. Maybe I will be back to normal with Xdrip and Android 10.

What version of xdrip are you using? What's your settings on xdrip?

**Comment by charding99** [comment] 2020-03-24 23:17
I am on version 2020.03.11 
![Screenshot_20200324-161316](https://user-images.githubusercontent.com/46679124/77485646-e16ccc00-6dea-11ea-9df8-9c244e2641a6.jpg)
![Screenshot_20200324-161359](https://user-images.githubusercontent.com/46679124/77485668-f47f9c00-6dea-11ea-8e29-eb59fd653291.jpg)

**Comment by charding99** [comment] 2020-03-26 04:02
Well, I spoke to soon. Last night, I had the same disconnect issues that I previously had with Android 10 and Xdrip.

**Comment by BradleyPJ** [comment] 2020-04-26 04:55
@charding99 is that with "sleep standby optimization" off and or "adaptive battery"?

Just got new phone with this issue so wondering if this will help

**Comment by charding99** [comment] 2020-04-27 14:47
I never did get it to work correctly. I can tell you that it makes it
through the night if the phone is plugged in.

Craig

**Comment by Ferdinandoz** [comment] 2020-04-28 09:26
maybe this helps https://github.com/NightscoutFoundation/xDrip/issues/1061#issuecomment-618056705

**Comment by sweetafro** [comment] 2020-07-21 18:41
Same issue running Moto G7 Android 10, Dexcom G6 and xdrip build from 2020.07.13 

It seems to disconnect when I'm away from the phone and not reconnect OR if my phone connects to another blue tooth device (e.g. my cars bluetooth or headset bluetooth). So far none of the workarounds have helped.

**Comment by DerZauberer** [comment] 2020-10-28 13:17
It's the same with LG G8s since Android 10 Update.

> Same issue running Moto G7 Android 10, Dexcom G6 and xdrip build from 2020.07.13
> 
> It seems to disconnect when I'm away from the phone and not reconnect OR if my phone connects to another blue tooth device (e.g. my cars bluetooth or headset bluetooth). So far none of the workarounds have helped.

**Comment by Navid200** [comment] 2021-02-21 03:01
Since the November 27, 2020 release, the recommended settings have been working reliably for almost all devices.
The recommended settings can be found here:
https://www.facebook.com/groups/xDripG5/permalink/4603084736431652

If you don't want to use facebook, you can ask in the Gitter room.

I would like to close this issue.
Please let me know if there are any reasons not to.

**Comment by charding99** [comment] 2021-02-22 16:40
I am no longer experiencing this issue. From my standpoint, it can be closed.

**Comment by dhermanns** [comment] 2021-03-03 10:43
Looks like this case has already been reopened. Just as a feedback to you: I had this problem once again with the latest xDrip nightly. After reading this ticket I switched back to the above November Build. After that I was able to connect just fine from my Redmi 7a to the Dexcom G6 Sensor.

So looks to me we have a regression here?

**Comment by Navid200** [comment] 2021-03-03 13:23
There are no reports of this issue any longer as long as you use an xDrip release of November 27, 2020 or after, and as long as your xDrip settings are correct.

**Closed by Navid200** 2021-03-03 13:23 UTC
Labels: android10+, bluetooth, bug

**Comment by dhermanns** [comment] 2021-03-03 14:01
Now you have one ;-). But maybe you are right and I simply have wrong settings. Cu

**Comment by Navid200** [comment] 2021-03-03 14:11
You can ask, using the support channels, for the recommended settings.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
