### ISSUE TITLE
InPen Authorizing Issue

### ISSUE THREAD

**Issue by usmc03** [NightscoutFoundation/xDrip#1295] opened 2020-04-09 16:27 UTC
I'm having the same issue as the other two posts dealing with authorization problems.

I'm able to get the pairing dosage from the inpen app but when switching over to xdrip it's not pairing. After discharging the pairing dose, i get the toast about not seeing the pairing dose in xdrip. It repeats  3 or 4 times until, i assume, it times out. The inpen status page in xdrip reports the pairing dose not having been issued.

Was a solution found for this?

**Comment by tolot27** [comment] 2020-10-29 14:42
Duplicate of #1176.

**Closed by tolot27** 2020-10-29 14:42 UTC
Labels: device-inpen, duplicate
