### ISSUE TITLE
Delete items in Dexcom communication queue

### ISSUE THREAD

**Issue by vguttmann** [NightscoutFoundation/xDrip#1376] opened 2020-06-29 14:02 UTC
I would like if it were possible to remove all queue items, because I had a system update today, which restarted my phone while my sensor (Dexcom G6) was warming up. I left it, and came back after warmup was completed, after which my phone was unable to connect to the transmitter properly, and the system status page always said there was one queue item, "Starting sensor" or such.

**Comment by tolot27** [comment] 2020-10-25 14:48
Likely a duplicate of #1118

**Comment by tolot27** [comment] 2020-11-06 19:56
Closing in favour of #1118.

**Closed by tolot27** 2020-11-06 19:56 UTC
Labels: device-dexcom, enhancement
