### ISSUE TITLE
Google Pixel 3a, Dexcom G5

### ISSUE THREAD

**Issue by Webifi** [NightscoutFoundation/xDrip#1009] opened 2019-09-11 00:46 UTC
Anyone have any luck with xDrip on a Google Pixel 3a running android 10 connecting to Dexcom G5?

My logs show continuous "No valid timestamp stored for transmitter: 41U5BR", and Classic Status Page says "Bluetooth Device: None Set".  Was working with a Moto G6 before.

**Comment by Webifi** [comment] 2019-09-11 15:00
Not exactly sure what fixed it, but it's working now on my Pixel 3a.

Things I did:
1. Disabled collection in xdrip.
2. Installed Dexcom G5 Mobile app (modified version that allows use on unsupported devices), restarted phone, and wasn't able to get the transmitter working with the dexcom app either.
3. Changed the device name of my phone's Bluetooth to something shorter, without spaces, apostrophes, etc.
4. Restarted phone again.  Dexcom G5 app started to be able to communicate with transmitter.
5. Uninstalled Dexcom G5, re-enabled G5 collection in xdrip. xdrip was now able to communicate with the transmitter.

**Comment by IsaacRoitman** [comment] 2019-09-14 17:08
Having the exact same issue on my Pixel 3a XL ever since changing the sensor yesterday; no Bluetooth connection and seeing "No valid timestamp stored for transmitter".  

Still not working after changing the phone / BT name.

**Comment by Webifi** [comment] 2019-09-14 20:05
I ran into the issue again after closing this issue, but fumbling for a bit was able to clear it up.  Still not exactly sure what fixed it as my "fix" was more analogous to a monkey pounding on the keyboard.

Things I did, in random order while flailing about:
1. Set scan for G5 constantly.
2. Removed any G5 pairings in the phone's Bluetooth settings.
3. Restarted phone. (both restart, and power of,f power on.)
4. Opened up the phone's bluetooth pairing screen and Xdrip in split screen mode.  Keeping the phone awake, waited for the G5 to pop up on the phone's Bluetooth list (didn't pair it there), and hit "RESTART COLLECTOR" in Xdrip's "Classic Status Page", then switched to "G5/G6 Status" and waited for a successful connection.  (Probably did 3 & 4 a half dozen times before it started to work again.)

Been working for about 2 days now without issue.  Really not sure what's going on.

**Comment by IsaacRoitman** [comment] 2019-09-14 20:20
Glad it's working for you!

In an effort to troubleshoot I tried going back to the G6 receiver... It also couldn't find or pair with the transmitter.

So I'm assuming the transmitter is defective, just spoke to Dexcom support and they are sending a replacement.
________________________________

**Comment by nsghub** [comment] 2019-09-18 08:51
Do you still having errors? I am also using a Pixel 3a, but did not upgrade to Android 10 yet.

**Comment by Webifi** [comment] 2019-09-18 16:13
Working so far.   Not sure if/when I'll run in to issues again, nor am I exactly sure what I did to fix it.

**Comment by nsghub** [comment] 2019-09-28 14:52
I've also upgraded my Pixel 3a to Android 10. Missed the first reading but that was probably because the setup was still running afert the first reboot. Since then no issues, runs as fine as with Android 9.

**Comment by IsaacRoitman** [comment] 2019-09-29 02:16
Looks good now!  Was actually a defective Dexcom transmitter and not the Android 10 upgrade, just weird timing.
________________________________

**Comment by nshtg** [comment] 2019-10-03 18:55
My transmitter was working perfectly until I upgraded to Android 10; Now the brainstate is caught in "scanning" forever and no values are received.

My Dexcom receiver worked for an hour and then it died.

Maybe XDrip+ in combination with Android 10 is killing the transmitters?!

**Comment by gregorybel** [comment] 2019-10-03 19:16
it looks like android 10 has some strange/new behaviours with BLE bonding.

**Comment by nshtg** [comment] 2019-10-03 20:33
@gregorybel 
Downgrading to Android 9 fixed all issues. Receiver started to work again after 30min too.

**Comment by gregorybel** [comment] 2019-10-04 08:29
then it confirms it has something to do with Android 10. thanks for info.

let's hope google provides a fix soon.

**Comment by nshtg** [comment] 2019-10-04 08:38
@gregorybel 
Maybe the new privacy changes have something to do with it? I read you need new permissions in the manifest to allow BLE scans.

https://developer.android.com/about/versions/10/privacy/changes#methods-fine-location

**Comment by nathanac2013** [comment] 2019-10-06 08:39
I got it to work , it was being difficult untill I 

Adb shell pm grant com.eveningoutpost.dexdrip Android.permissions.WRITE_SECURE_SETTINGS

I'm typing that off the top of my head so if it doesn't work make sure the package name is right 

Adb shell pm list packages | grep -i xdrip;
That will give you the package name and make sure the android.permisions.WRITE_SECURE_SETTINGS is the right one a few other apps use the same work around so a quick Google search or a navbar app will tell you

**Comment by nshtg** [comment] 2019-10-06 08:45
@jamorham 
Maybe this could fix some of the problems seen on Android 10?

**Comment by nathanac2013** [comment] 2019-10-06 09:30
That is on Android 10 sorry I should have clarified

**Comment by nathanac2013** [comment] 2019-10-06 09:33
https://photos.app.goo.gl/nXF7vRs3kkF6sWPYA

Google pixel 3a xl

**Comment by nathanac2013** [comment] 2019-10-06 09:35
https://photos.app.goo.gl/9BMq3uJgXp25bXW19

**Comment by nathanac2013** [comment] 2019-10-06 09:45
I executed the command opened the app and then it asked if I wanted to whitelist it I hit ok and it worked and had all the other permissions in settings enabled already

**Comment by jcostaIO** [comment] 2019-10-13 02:55
@Webifi solution worked for me. My Bluetooth name was "Pixel 3a" I changed it to "Pixel3a" (without the space) and immediately I could connect to the Dexcom G6 app

**Comment by nshtg** [comment] 2019-10-18 15:31
On Android 10 you need to enable an additional permission/setting:

![ezgif-6-a1d2ceeab7be](https://user-images.githubusercontent.com/5219415/67107607-11c19600-f1cd-11e9-8d6d-5083d55a19f5.gif)

After I added this permission it started working on Android 10.

**Comment by spencertollefson** [comment] 2019-10-23 15:30
For what it's worth, I turned off OB1 Collector last night in the G5/G6 Debug Settings and it's been night and day better since then. I have a Pixel 3a running Android 10.

**Comment by jtargoff** [comment] 2019-11-03 22:06
I struggled for 24 hours with new transmitter on what had been working on my 3a with prior transmitter, and then appinfo suggestion (above, 10/18/19) from nshtg solved the issue.  Thank you!
I have always had OB1 collector on.

**Comment by BenMc19** [comment] 2019-11-05 18:14
I've tried enabling that permission, as well as the unbounding option.  Granted this transmitter is way past its expiration date.  I'll give it a day or so fiddling with the settings.  If I can't get it to work I'll just use an old Android phone as a receiver until it dies, then maybe move to the Dexcom receiver until there's a permanent solution.  

I know these major updates are a pain, but thank you again @jamorham for all the hard work.  I mentioned it in another thread, but if you are interested in purchasing a Pixel 3a (assuming thats the most affordable reference device for these updates) I'm sure many of us would love to help.  You have single handedly saved me so much money over the past 3 years or so.

**Comment by Webifi** [comment] 2019-11-05 19:02
I have the following set, though I'm not sure if they're all required for things to work:

https://photos.google.com/share/AF1QipO15kMPamJZbbxzYT9Gxawl8BZlVc_WaW0EHkfFNj4P7f7RE-ma8rJGDa0beJn8CA/photo/AF1QipOb81eby_5XNvmCPkhv6pi4lVoUCGtEBCvnRAnk?key=WnItUlNXbVBmakJyaE5tTjRueTBUOHNfakJtdUN3

https://photos.google.com/share/AF1QipO15kMPamJZbbxzYT9Gxawl8BZlVc_WaW0EHkfFNj4P7f7RE-ma8rJGDa0beJn8CA/photo/AF1QipM1X35KGO2tRca4DTggENIZ1VDqhgSLfDSYcMhF?key=WnItUlNXbVBmakJyaE5tTjRueTBUOHNfakJtdUN3

The steps that seem to most reliably fix the issue for me are:
1. Forgetting the DexcomAM devices(s) in you Bluetooth Settings -> Connected Devices.
2. Select "Pair a new devices" in your phone's Bluetooth settings (but don't actually select or pair the device here.  Just let it scan...)
3. Get split screen going so you can see both the Bluetooth scanning and x-drip at the same time.
4. In x-drip, go to system status -> classic status page.  Click restart collector.  switch to G5/G6 Status.    Keep your phone awake.  Wait for the dexcom device to show up in your Bluetooth settings scanner, (Could take up to five minutes, depending on the last time your transmitter woke up to send data).
5. If xdrip does authorize and connect,  try restarting the collector. 
6. May take a few tries for it to work.

**Comment by BenMc19** [comment] 2019-11-05 19:07
@Webifi  With all of those steps and settings, you have had good result?  Does it stick after a reboot or is it a temporary fix?

**Comment by Webifi** [comment] 2019-11-05 19:08
Seems to have stuck so far.

**Comment by spencertollefson** [comment] 2019-11-05 19:14
I'll share my settings as well. My coverage has been fantastic since I turned off OB1 and used these (few) settings with my G5 and Pixel 3a.

After rebooting my device this morning for the newest security patch, I did need to `RESTART COLLECTOR` and `FORGET DEVICE`. It picked up the signal immediately afterward.

![image](https://user-images.githubusercontent.com/22157182/68238081-67bc7900-ffd6-11e9-9b88-95241a619b17.png)

![image](https://user-images.githubusercontent.com/22157182/68238091-6c812d00-ffd6-11e9-8a39-500f2a07ebc0.png)

![image](https://user-images.githubusercontent.com/22157182/68238116-7efb6680-ffd6-11e9-9394-5b0fccc0fccb.png)

**Comment by Webifi** [comment] 2019-11-05 19:22
I've noticed that not using the native algorithm kills the battery on my G5 transmitters petty quickly, so I recommend using it.   If the native algorithm is disable from being too old, you can reset the transmitter's timer:
https://github.com/NightscoutFoundation/xDrip/issues/386

**Comment by BenMc19** [comment] 2019-11-05 21:16
> I have the following set, though I'm not sure if they're all required for things to work:
> 
> ![Screenshot_20191105-125616](https://user-images.githubusercontent.com/5082671/68237523-e14f6980-ffcc-11e9-9a98-30527af129e7.png)
> 
> ![Screenshot_20191105-125630](https://user-images.githubusercontent.com/5082671/68237533-e6141d80-ffcc-11e9-8566-298f35a45ba1.png)
> 
> The steps that seem to most reliably fix the issue for me are:
> 
> 1. Forgetting the DexcomAM devices(s) in you Bluetooth Settings -> Connected Devices.
> 2. Select "Pair a new devices" in your phone's Bluetooth settings (but don't actually select or pair the device here.  Just let it scan...)
> 3. Get split screen going so you can see both the Bluetooth scanning and x-drip at the same time.
> 4. In x-drip, go to system status -> classic status page.  Click restart collector.  switch to G5/G6 Status.    Keep your phone awake.  Wait for the dexcom device to show up in your Bluetooth settings scanner, (Could take up to five minutes, depending on the last time your transmitter woke up to send data).
> 5. If xdrip doesn't authorize and connect,  try restarting the collector.
> 6. May take a few tries for it to work.

Whatever voodoo magic this is, has made mine work properly for the past 2 hours.  I have commented on a few other threads with these issues, so after a day or so I will copy your solution over.

**Comment by spencertollefson** [comment] 2019-11-05 21:25
@Webifi - thanks for the battery tip. I had no idea! I just switched to trying out the settings you shared. I'll give it another go.

**Comment by BenMc19** [comment] 2019-11-05 22:13
@Webifi Was out of range for one reading, and then it went back to failing to read and scanning.  Something you did definitely made it work better, but still must be something off.  I'm going to keep messing with settiings and hopefully I'll get something to click.

**Comment by Webifi** [comment] 2019-11-06 00:00
Post a screenshot of your G5/G6 Status page if you can.

**Comment by BenMc19** [comment] 2019-11-06 02:10
First picture is a screenshot before i purposefully got out of range. Second screenshot is 15 minutes or so after it lost connection. As of right now the phone has been in range and it is 47 minutes since last reading. 

I can fix by "forgetting device" in xdrip app, and it works great until next time it missed a reading. 

![Screenshot_20191105-193404](https://user-images.githubusercontent.com/57396167/68262228-41afcc80-0008-11ea-90e1-b26a55e50a20.jpg)

![Screenshot_20191105-195305](https://user-images.githubusercontent.com/57396167/68262244-4d02f800-0008-11ea-8bfe-2934847df18b.jpg)

**Comment by BenMc19** [comment] 2019-11-06 02:13
Here was the screenshot of it before it lost connection. 
![Screenshot_20191105-182821](https://user-images.githubusercontent.com/57396167/68262374-bd117e00-0008-11ea-939c-6a82fd206bcd.jpg)

**Comment by Webifi** [comment] 2019-11-06 14:20
Battery is getting kinda low there.  Could be the transmitter isn't waking up exactly at its predicted 5 min intervals.  How long has that transmitter been active?

You could try [resetting the timer](https://github.com/NightscoutFoundation/xDrip/issues/386) on the transmitter to get its native  algorithm going again.

**Comment by BenMc19** [comment] 2019-11-06 15:57
@Webifi   Yes I have those settings.  I let it continue to go and usually within an hour it did pick back up, and then filled in the missing data, without me having to forget the device.  Definitely is an old transmitter, so that could be the issue.  I am glad to see that it does eventually resolve itself, even if it takes a bit longer.  Thanks for all your help!

**Comment by BenMc19** [comment] 2019-11-06 20:23
Lost connection this morning and it failed to regain signal.  Thought I would do a test, as I have an old android phone here at work running Android 8 (LG G6).  I reconnected my Dexcom to the old phone, force closed the xdrip app on my current phone, to see if I could deduce the problem. 

I purposefully took the phone a distance away to make it miss a reading, and after 15 minutes or so, I went to retrieve it, and it reconnected on the next available opportunity.  Considering that my OnePlus 6T worked flawlessly on Android 9, and the fact that this transmitter works perfectly with the LG G6 device, there has to be something in my Android 10 update that is causing connection issues.  

Also, there aren't many phones with Android 10 on it (may just be Pixels and OnePlus phones).  So it is possible that it is just OnePlus Android 10 that is the culprit, which is why it doesn't reproduce this on the Pixels.  Who knows.

This is the screenshot of the LG G6 status screen for comparison to my OnePlus 6T screenshot if that is helpful.
![Screenshot_2019-11-06-13-50-34](https://user-images.githubusercontent.com/57396167/68334839-03b2b700-00a1-11ea-99be-715c6f22dcec.png)

**Comment by BenMc19** [comment] 2019-11-07 03:35
Update:

Tried something this afternoon when i experienced the inability for xdrip to automatically reconnect. I deleted the app, and downloaded the latest nightly (November 2nd). Going on 6 hours with multiple walk away disconnects and everything is working great so far. 

Not sure if it was the fact of just redownloading any xdrip app, or if specifically getting the newer nightlies made the difference, either way so far it is working great.

**Comment by Webifi** [comment] 2019-11-07 16:38
Sorry, should have asked what version x-drip you're running.  I've been running on the alpha update channel for awhile now.

**Comment by jedduff123** [comment] 2019-11-09 22:30
Thought I would jump in - got a new OnePlus 7T last night - received some initial readings then during the evening dropped and have not been able to connect.  Was on my way to the store to get another phone and saw this thread.  Really appreciate everyone taking the time to look.  What I did was the following, as above:  Unchecked the "Use the OB1 Collector" - I was immediately asked to provide a calibration.  I also through Android - went into Apps & Notifications - xDrip - Advanced - Modify System Settings and enabled Allow modifying system settings.  As stated above.  Since doing this, I have been able to reboot, walk-away from my phone and haven't dropped.  Will keep everyone posted but so far so good.  Again appreciate the info above, it is greatly appreciated!!

**Comment by Webifi** [comment] 2019-12-09 14:42
Made the mistake of updating to the most recent nightly of x-drip.  Now, even after reverting to the previous version, X-Drip stops getting data from my G5, requiring me to jump though my aforementioned hoops to get it going again -- which will only last a couple hours or less. 

Can't seem to get my x-drip back in to the magic state it was in before.

**Comment by dougboss** [comment] 2019-12-12 12:05
Webifi, I'm having same issue, since recent nightly update I can't maintain a decent connection to g5 on pixel 3 w Android 10.  I downgraded Xdrip to last version that worked but no change ....

**Comment by Webifi** [comment] 2019-12-13 16:54
Not sure if it's just a coincidence or if it will actually last, but since doing the following, xdrip has not lost connection with my G5:

1. Settings -> Less common settings -> Bluetooth Settings
2. Enable "G5 Bluetooth Watchdog"
3. Enable "Always discover services"
4. Enable "Allow blucon unbonding"
5. Settings -> Less common settings
6. Enable "Aggressive service restarts"
7. Restart phone
8. Follow steps from https://github.com/NightscoutFoundation/xDrip/issues/1009#issuecomment-549970505

**Comment by Webifi** [comment] 2019-12-13 16:55
Not sure if it's just a coincidence or if it will actually last, but since doing the following, xdrip has not lost connection with my G5:

1. Settings -> Less common settings -> Bluetooth Settings
2. Enable "G5 Bluetooth Watchdog"
3. Enable "Always discover services"
4. Enable "Allow blucon unbonding"
5. Settings -> Less common settings
6. Enable "Aggressive service restarts"
7. Restart phone
8. Follow steps from https://github.com/NightscoutFoundation/xDrip/issues/1009#issuecomment-549970505

**Comment by Webifi** [comment] 2019-12-17 16:37
Must have been a coincidence, since it finally broke again.

Uninstalled x-drip, and re-installed x-drip (lost my history and settings), then re-configured.  Seems to be working so far.

**Comment by Navid200** [comment] 2021-02-18 18:04
@Webifi Would you please close this issue?
We are working on improving documentation.
There are already two support channels with some documentation provided on each.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

These issues are supposed to be used for reporting bugs and feature requests.
Would you please help us accomplish that?
Thanks

**Comment by Webifi** [comment] 2021-02-18 18:44
I'll close this issue, but documentation that require you create an account to read, as is often the case with facebook, or require you to sift through an endless thread of messages and/or create an account to be one of the many that re-ask the same questions over and over, as is the case with gitter, is a non-starter for me, and likely many others.

**Closed** 2021-02-18 18:44 UTC

**Comment by Navid200** [comment] 2021-02-18 18:47
That's a valid point.  Needs to be addressed.   We are aware.  
Thanks
