### ISSUE TITLE
Freestyle Libre1 + Miaomiao1 + xDrip Connection problem

### ISSUE THREAD

**Issue by aquinohugo** [NightscoutFoundation/xDrip#1489] opened 2020-10-28 19:52 UTC
Hello everyone.

I recent acquired a miaomiao1 and I've been using it with xDrip+. The setup is the following: Freestyle Libre 1 --> Miaomiao1 --> xDrip+ (in my Huawei p20 smartphone) --> Nighscout, herokuapp.

The first ever Libre1 sensor that I use when I got the miaomiao1, worked like a charm with no disconnections in all the 14days. Just worked perfectly. The second Libre1 had about 4 our 5 disconnections in is 14days life span. After that, all the others Libres1 are disconnecting 4/5 times a day!

I don't think that is a problem in the Bluetooth connection between the smartphone and miaomiao1 but rather the Libre1 and miaomiao1 it self.  Some times the connection reestablish by it self after 3 or 4 hours and the values of that disconnected period appears in the xDrip graph. Other times, the way I can make it work again is by stopping sensor and start it again. But that some times doesn't work and I have to manually reset miaomiao1 by physically pressing the reset bottom.

On the Error and Event List there is this "No sensor has been found" message. On the system status, the miaomiao1 appears "connected" and only appear "disconnected" when the system as not been working for a long time. 

![xdrip-error event](https://user-images.githubusercontent.com/73556027/97486153-f8603780-1952-11eb-9f40-e2c460e5f838.jpg)

Does anyone have an idea of where the problem might be or is suffering the same struggle? In the past I had a miaomiao2 (which lost) and the connections problems were much less common.

Thanks in advance!

**Comment by aquinohugo** [comment] 2020-10-28 20:01
The xDrip+version that I'm currently using is the 18th May 2019. I have already tested with the last one (1st Oct 2020) and the problem persisted. So I downgraded back to the 18th May 2019 version.

**Comment by psonnera** [comment] 2020-10-29 12:14
This should not be logged as an issue: you can see No sensor has been found in the logs. That's a transmitter issue, either positioning is bad or the device is defective.

**Comment by aquinohugo** [comment] 2020-10-29 14:40
Thank you for the keep response! @psonnera 

I don't think that this is a positioning issue. I attached the miaomiao perfectly on the libre.
When you say "device is defective" you are referring to the libre 1 or the miaomiao?

**Comment by Marcio261** [comment] 2020-11-01 23:17
I am having the SAME problem too... I am sure that the sensor is well placed, but the app cannot find it...
I have tried also the "tomato" app, and shows the same results "sensor not found"... 
I'm waiting to switch the sensor in a few days, and try again(because it could be a sensor problem. If it keep not finding it, it is a miao miao problem).
Well, i hope its just the sensor..

**Comment by aquinohugo** [comment] 2020-11-03 16:00
@Marcio261 Its not a Libre1 problem, in my opinion. Im having this "sensor not found" problem, but i can scan the Libre1 with xDrip NFC and Libre NFC with no problem...

Yesterday I had to updated MiaoMiao1 firmware to v39 but it doesn't seem to helped. The problem persists.

**Comment by psonnera** [comment] 2020-11-03 16:24
If Tomato doesn't work neither it's a device issue to be addressed by the vendor. Not here.

**Comment by tolot27** [comment] 2020-11-04 07:09
I'll keep this issue open for one more week. @Marcio261 and @aquinohugo Please report back if the problem is solved with a new sensor.

**Comment by aquinohugo** [comment] 2020-11-04 08:12
Unfortunately no. Changing the Libre1 to a new one did not solved the problem. 
I'm getting in touch with the retailer where I bought the miaomiao to address the problem. Like @psonnera said. It might be a miaomiao problem. It might be defected.

**Comment by Marcio261** [comment] 2020-11-04 10:39
> I'll keep this issue open for one more week. @Marcio261 and @aquinohugo Please report back if the problem is solved with a new sensor.

Thanks, but i think you can close it... I'm talking with the vendors of miaomiao, for the same reason that @aquinohugo . I don't think the problem is on the sensor, or the app... but thanks for the help anyway 👍

**Closed** 2020-11-04 10:54 UTC
Labels: device-libre, device-miaomiao, invalid, question

**Comment by VVbolotov09** [comment] 2022-08-21 10:37
Hi, I had same problem with miao2 after swimming. I use miao1 everything is ok
