### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by jsPl** [NightscoutFoundation/xDrip#1012] opened 2019-09-14 06:44 UTC
Can someone please update the project setup so that it builds?
I tried that myself for the past 2 days with Andorid Studio 3.5, and incrementally fixing errors that occured and causing other errors, updating gradle dependencies - to no avail....
Would really like test some of my ideas with this wonderful project.

**Comment by MasterPlexus** [comment] 2019-09-14 08:31
At the moment, please stay at Android studio 3.4, there are several projects which have problems with the newest version. With 3.4 everything works smooth.

**Comment by jsPl** [comment] 2019-09-14 18:36
Ok, tried with 3.4.
Cloned the project, first build failure is that the dependencies in wear:
```
    compileOnly 'com.google.android.wearable:wearable:2.0.1'
    implementation 'com.google.android.support:wearable:2.0.1'
```
no longer exist in any declared repository. So I changed it to 2.1.0.
Then there's another build error in wear manifest:

```
Execution failed for task ':wear:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.2) from [com.android.support:support-v4:26.0.2] AndroidManifest.xml:28:13-35 is also present at [com.android.support:support-core-utils:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.
```
This suggestion doesn't really help... Is something wrong with the manifest file?

**Comment by jamorham** [comment] 2019-09-15 19:46
It isn't a problem with manifest file. It is regressions introduced by Android Studio and poor stewardship of the maven repositories by google.

**Comment by jamorham** [comment] 2019-09-15 21:58
There are a couple of ways to work around this. I will see if I can integrate one of them.

**Comment by RudieKat** [comment] 2019-09-30 20:00
Managed to get things working (Note, below info is related to OS X so locations will vary)

Uninstall previous versions and remove all related stuff in 
~/Library/Application Support/AndroidStudio3.*
~/Library/Preferences/AndroidStudio3.*
~/Library/Caches/AndroidStudio3.*
~/Library/Logs/AndroidStudio3.*

also rm -rf ~/.android for good measure.
3.4.2 didn't work, 3.4.1 did so there is that too.

**Comment by wkochFPV** [comment] 2019-11-10 17:05
These are my first steps in android development... I managed to build the app using the current android studio version, based on tipps found on various  pages on the internet. This is what I have done:

1. I did not update  Gradle Plugin

2. File -> Settings -> Experimental -> UNCHECK "Only sync the active variant"

2. Add

<meta-data
            tools:replace="android:value"
            android:name="android.support.VERSION"
            android:value="26.0.2" />
			
to file wear/manifests/AndroidManifest.xml directly below the existing text
<uses-library
            android:name="com.google.android.wearable"
            android:required="false" />
			
3. Gradle Script/build.gradle(Project: xDrip)
	Change classpath line for google-services to
	classpath 'com.google.gms:google-services:3.2.0'

With these changes, the apk builds without errors.

Hope this helps.

Best regards, Walter

**Comment by stephencmorton** [comment] 2019-12-27 06:16
I can't get xDrip to build. I tried with the Android Studio 3.5, and then with 3.4 based on the above comments.

I wanted to build xDrip based on the `insulin-types-merge` branch.

I keep getting the gradle error for `app/build.gradle`

> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: app

Which _looks_ completely easy to fix: just replace 'compile' with 'implemetation' or 'api', and that's what googling indicates. The problem is there is no 'compile' anywhere that I can find, so I'm stumped.  

```
$master >
git describe --tags
2019.12.22
$ insulin-types-merge > 
git describe --tags
2019.11.02-1-g62157698

````

_(I am not an Android developer and am not familiar with Android Studio and Gradle and all this business, but I have previously successfully built AndroidAPS and am a programmer by trade.)_

**Comment by MasterPlexus** [comment] 2019-12-27 06:48
Normally you could ignore a warning, the apks should build anyway. Are there other messages with errors?

**Comment by stephencmorton** [comment] 2019-12-27 19:35
@MasterPlexus  After more retries from scratch I got it working. I think it was a combination of needing to download some `wear` dependencies (that were necessary even though I only wanted to build `app`) and a keystore problem that was just my mistake. 

If you want I can delete my questions, to reduce the noise on this issue.

**Comment by MasterPlexus** [comment] 2019-12-27 22:55
I would say, let it be, as it could help others, even that it does not link to the main topic directly.

Anyhow not sure if this issue could be closed. @jsPl : is there still a problem? Otherwise I would think it is a good idea to close it.

**Comment by jeromecc** [comment] 2020-01-09 23:40
This PR introduces minimal changes that allow xDrip to be built with Android Studio 3.5 (after commenting out one line about signingConfig, see my comment on the PR), which is the current stable version of Android Studio.
It would be great to merge it.
Having to download stale versions of an IDE to start working on a project could prevent contributions.
https://github.com/NightscoutFoundation/xDrip/pull/1160
Thanks!

**Comment by asavageiv** [comment] 2020-03-26 21:01
I was able to build the most recent master today from a clean clone using Android Studio 3.6.1 as long as I didn't upgrade the Android Gradle Plugin (AGP). It would be nice to be able to upgrade the plugin because builds are currently non-incremental due to the use of android.databinding and the age of the plugin. Per [this issue](https://issuetracker.google.com/issues/110061530) 3.6+ has incremental builds enabled by default.

Should we close this issue and open a new one?

**Comment by tolot27** [comment] 2020-12-14 21:52
The project builds now and there is a new issue addressing code review and incremental builds: #1522. Hence, closing this issue.

**Closed by tolot27** 2020-12-14 21:52 UTC
Labels: bug, code

**Comment by nareshvr** [comment] 2023-02-28 07:41
i am facing one issue past 2 days 

A problem occurred evaluating project ':continuousglucosemonitoring'.
> Could not read script 'C:\Users\...\token-replace.gradle' as it does not exist.

can you please help how to achieve this issue

**Comment by tolot27** [comment] 2023-02-28 08:19
I recommend to checkout xDrip to a new location not below `C:\Users...` and using git command line tools. `token-replace.gradle` is definitively part of the repository (see https://github.com/NightscoutFoundation/xDrip/tree/master/app).
