### ISSUE TITLE
Integrate rewrite history BG values into other calcs and functions

### ISSUE THREAD

**Issue by old-square-eyes** [NightscoutFoundation/xDrip#366] opened 2018-03-26 00:03 UTC
Rewrite history does not flow through to the following calcs and functions gracefully (there may be more)

1. xDrip+ followers
2. Nightscout
3. Historical stats
4. Noise calcs and downstream derivatives - takes time for noise to age-off
5. Predictive simulation & Trend momentum - takes time for skewed predicted plot to settle. E.g. a calibration before dinner, resulting in a slope change will interfere with the accuracy of the predictive simulation, making dose calculation for the meal difficult (since this feature is used to visualise dose stacking by some).
6. Undo button does not undo history rewrite.
7. Auto calibration evaluates back 24hrs (soon to be 8). If a valid calibration is found in this window it is applied, and history rewrite does not match the calibrated timestamp. Instead it is applied for the current timestamp.
8. Filtered plot does not follow re-write, instead it jumps with the newly calibrated plot. Awkward for those viewing filtered plot primarily.

Rewrite history is a coarse approximation - I know, but applying the 25 odd rewritten BGs to the above seems more logical to me than utilising incorrect data with a big jump in it. I understand completely there is creative license here.

The main scenario is where a calibration pulls the plot in a direction, and is interpreted by the above features as being a big BG jump which is being interpreted as verbatim by the down stream processes.

**Comment by old-square-eyes** [comment] 2018-03-26 00:09
Example of #5 above

![screenshot_20180324-224150](https://user-images.githubusercontent.com/25760491/37881575-de3ac588-30f6-11e8-8db7-49c89d2cbc5f.png)

**Comment by Navid200** [comment] 2021-07-14 03:51
@old-square-eyes Rewrite history is a graphics setting.
Correct me if I am wrong in that respect.
If I am correct, the BG data table is never modified.
So, no other analysis or database should be affected by the setting.

As an example, you can use the graphics settings to, for example, smooth noise.  But, why should that affect the Nightscout database?

**Comment by Navid200** [comment] 2021-08-06 14:38
@old-square-eyes 
Rewrite history capability exists in xDrip.  But, I don't think we will add any more to it or expend it to any other platforms or calculations etc.

This is my view:
The only justification I have heard for "Rewrite history" is the case of a user going to see their doctor and the doctor complaining about a low in their records.  But, the low is due to a CGM inaccuracy that can be proven by a calibration shortly after.
So, one may prefer to rewrite history in that case to raise the readings prior to the calibration in order to avoid the lows.

The problem is that we have no idea what the result would have been if the blood glucose reading had been done earlier. 
 We are just speculating.
Even if it is true that the reading is obviously is in error based on the calibration shortly after, that can be explained to the doctor as well.

I would like to close this issue as I said I don't believe we will make any changes to xDrip to enhance/expand the rewrite history concept.

Anyone who likes to present an opposing opinion can always post here, and we can always reopen a closed issue.

**Closed by Navid200** 2021-08-06 14:38 UTC
