### ISSUE TITLE
G6 values discarded after transmitter change and warmup due to small time sync difference

### ISSUE THREAD

**Issue by t1dast** [NightscoutFoundation/xDrip#1575] opened 2020-12-25 17:38 UTC
### G6 values discarded after transmitter change and warmup
After changing the transmitter and starting a new sensor using my hardware receiver, after the warmup my hardware receiver started getting results but xdrip+ showed me no readings. I checked the logs and saw some entries about values being received but discarded as invalid.

### My environment
- The nightly build from 16th December 2020
- G6 with a new transmitter (8N..) and a new sensor.
- G6 settings enabled: OB1 collector, native algorithm, minimize scanning, G6, allow OB1 initiate bonding

### Expected behavior
Since the hardware receiver started getting values, I expected to get values in xdrip+. The log shows that values were received ("Got usable glucose data from G5") thus I'd expect this even more so.

### Actual behavior
The values didn't show up in the graph. Instead the status was something about not having received any readings yet. The log shows that the "Got usable glucose data from G5" is followed by "invalid timestamp comparison for transmitter id: 8N..."  and then by "No sensor, ignoring this bg reading" and "New bg reading was null in processGlucoseRxMessage". I then noticed a time difference between hardware receiver and smartphone of 3 minutes. I updated the time on the hardware receiver and soon started getting results.

### Steps to reproduce the behavior:
1. End the sensor session (or wait for it to end)
2. Have a time difference between receiver and mobile phone of 3+ minutes (phone 3 minutes ahead).
3. Use the hardware receiver to pair a new transmitter, provide sensor code, provide transmitter S/N, start the sensor.
4. Change to the new transmitter S/N in xdrip+.
5. Confirm pairing worked by waiting for status message similar to "Warming up 1.9 hrs"
6. Wait for the warm up to finish.
7. Notice the first reading on the HW receiver.

Just changing the receiver's time in the middle of a session seems not to produce any issues of this type.

### Considerations
I'm not sure if the protocol prevents xdrip+ from getting usable data if its time stamp on the phone is not within the expected range of the transmitter's. But the log indicates that values have been received and discarded. The conclusion "no sensor" seems wrong and the values should be used in my opinion.

**Comment by Navid200** [comment] 2021-02-05 16:26
Can you explain step 2?
Why would you knowingly have a time difference between the two?  Why would you not correct the one that is incorrect?

**Comment by t1dast** [comment] 2021-02-05 22:13
You would knowingly have the difference in order to reproduce the issue. I for one only realised the difference in hindsight by investigating the log messages.

But to be more precise: the phone was three minutes ahead of the clock on the hardware receiver but actually it was the hardware receiver that was behind the actual time (since its clock is not permanently synchronising as opposed to my phone).

So what you would do is set a wrong time on the receiver and later on correct it. That fixed the issue for me.

**Comment by Navid200** [comment] 2021-02-05 22:16
Thank,
So, if I understand correctly, as long as both the phone and the receiver have correct time, this issue never happens.  Is that correct?
If that is correct, do you agree that there is nothing wrong, with respect to this issue, with the xDrip code?

**Comment by t1dast** [comment] 2021-02-05 22:26
You're right that this hasn't happened to me while the time difference was small enough.

I wouldn't draw any conclusions myself about the correctness. I don't know the protocol. Why are, say, 90 seconds of difference fine but 3+ minutes is an issue? If the transmitter refuses to send data in that case, I'd say sure, nothing wrong. But there was data coming in according to the log, it just appears to have been discarded. The message "No sensor, ignoring this data" looks wrong, given that I had a sensor that was sending data.

**Comment by Navid200** [comment] 2021-02-05 22:30
I agree with you that xDrip can improve.
The problem is that we have limited resources (developers).  We have to choose our battles.  
If we tell the developers that there are thousands of issues, we may not get as much attention from them as opposed to telling them that there are 5 serious issues.
So, I am looking for serious issues with the code that cause grief for us, the users.

If you believe that this issue is a serious issue and absolutely needs to be fixed, then fine.  
Otherwise, I respectfully suggest that you close it.

**Comment by t1dast** [comment] 2021-02-05 23:15
I'm not sure if I understand where this is coming from. I appreciate prioritisation. And I'm being clear: this is low prio in my opinion. But I will not blur the lines between "low prio" and "no issue". This is not a bidding platform. It's an issue tracker.

**Comment by tolot27** [comment] 2021-02-07 00:44
It is likely that we cannot fix this in the near future. Since there exists a workaround which also acts as a suitable fix, it is better to document this. IMHO, having the correct time at the receiver is useful as well.

**Comment by Navid200** [comment] 2021-05-22 03:41
@t1dast 
I don't have a receiver to test this.  I wish I did.  
  
I don't see why a wrong time on the receiver could cause an issue with xDrip receiving data from the transmitter.
The active timeslot of the transmitter is defined by the transmitter internal clock and is not affected by the receiver.
xDrip adjusts its time and scans when it expects the next transmitter cycle.  

I wonder if this was caused by some other issue we are overlooking.
Firefly G6 connectivity can be challenging.  In order to help users, I created some guides.
There are logs that are not correct because we still have not completely updated the code to perfectly deal with Firefly.

Can you still recreate this problem?
Are you willing to work with me to see if we can connect properly with xDrip after having caused the issue?

**Comment by Navid200** [comment] 2021-05-23 15:18
Please follow the guidelines for bringing up xDrip with a session already in progress.
https://github.com/Navid200/xDrip/wiki/Receiver-or-t:slim  

Closing due to inactivity.

**Comment by t1dast** [comment] 2021-05-23 16:00
Thanks for getting back on this issue. I have no knowledge about the details, so I can't explain what the time would have to do about this. It's just that the log contained a message concerning an invalid timestamp comparison. I agree that the actual reason might in fact be something else.
I haven't observed the exact issue again. But it happened at least twice that I wouldn't get any readings after warmup until restarting the collector.
Since the messages are the same (no sensor, ignoring reading), I'm considering to use this issue instead of opening a new one. Would you be okay with this?
I am very much willing to work on this. What would you need to get as much support from my side as possible? 
It is just happening pretty unregularly. However it's quite annoying, since my sensor changes are around bed time and I wake up to missed readings.

**Comment by Navid200** [comment] 2021-05-23 16:06
If you are open to it, it will be much more productive if we communicate using a forum.  If we conclude that it is an issue, we can come back here, or we can open a new issue.  
If you agree, please post here:
https://github.com/Navid200/xDrip/discussions

If you prefer to use an issue instead, we can continue here.
But, I suggest the forum.

**Closed** 2021-05-23 16:11 UTC
Labels: device-dexcom-transmitter, type-documentation, wontfix

**Comment by Navid200** [comment] 2021-05-23 16:17
Start by making sure your xDrip and Android settings are correct:
https://github.com/Navid200/xDrip/wiki/G6-Recommended-Settings
