### ISSUE TITLE
Send Collected Watch Data to Phone via Wifi, if watch and the phone are on the same Wifi network?

### ISSUE THREAD

**Issue by roco5** [NightscoutFoundation/xDrip#534] opened 2018-08-04 21:04 UTC
If the watch and phone are on the same wifi network, can the watch collect and send readings over wifi to the phone, even if the phone is far away from the watch (school campus? or big house? etc.)

**Comment by kskandispersonal** [comment] 2018-08-04 22:05
Yes, I tested the Cloud feature of Android Wear several months and confirmed it worked as expected.  Doesn't matter the distance between phone and watch, could be different cities!  The phone, of course, must be turned on and have Wi-Fi enabled.  Of course, the watch must be paired with that phone and be set as the xDrip+ collector, also.

**Comment by roco5** [comment] 2018-08-05 16:12
This sounds amazing if it works. I'll have the SW3 this week and can test.  Thanks for your reply.  I was not aware this feature was implemented.

**Comment by jamorham** [comment] 2018-08-05 18:16
This works fine. I have used a Huawei Watch 2 with 4G as a collector hundreds of miles away from the phone which it is paired with. Any combination of mobile data / wifi / bluetooth connectivity appears to work in my tests.

**Comment by roco5** [comment] 2018-08-07 01:59
Are there any special settings on the watch or phone that I need to enable
to make this work?

**Comment by gonz01d** [comment] 2019-05-01 10:59
I to am interested in this, as @roco5 queried - are there any special settings needed to enable this?

**Comment by Navid200** [comment] 2021-02-16 14:34
@roco5 Would you please close this issue if you have found an answer?
If not, you can use the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment] 2021-02-26 17:11
Closing due to inactivity

**Closed by Navid200** 2021-02-26 17:11 UTC
