### ISSUE TITLE
Feature request: read historic BZ measurements of FreeStyle Libre App into xDrip

### ISSUE THREAD

**Issue by 01erster** [NightscoutFoundation/xDrip#1283] opened 2020-03-26 21:10 UTC
Situation: Freestyle App does not collect sensor data, eg. mobile device is out of range. Manual read by NFC with Freestyle does not only read actual BZ Value, also historic data of last 8hrs, too. Those mesaurements should also be transfered into xDrip

**Comment by MasterPlexus** [comment] 2020-03-27 05:34
this is not (initial)  a topic of xDrip. The problem is, that the patch for
the librelink app does not contain the ability to send the historic data.
So before xDrip could handle this historic data, someone needs to
enhance the patch to make them available. But at the moment I see nobody
who will dive into the mashinecode of librelinkl to make that possible...


Am Do., 26. März 2020 um 22:10 Uhr schrieb 01erster <
notifications@github.com>:

**Comment by Navid200** [comment] 2021-03-02 03:39
@01erster Would you please close this issue if it has been resolved?
Otherwise, please update.
Thanks

**Comment by Navid200** [comment] 2021-07-08 03:29
As described by MasterPlexus, this does not seem to be an xDrip issue that can be addressed by modifying xDrip.

**Closed by Navid200** 2021-07-08 03:29 UTC
