### ISSUE TITLE
NS follower update 10 minutes late

### ISSUE THREAD

**Issue by Pogman** [NightscoutFoundation/xDrip#1088] opened 2019-11-12 15:30 UTC
It's been reported by Medtronic 600 Series users that xDrip follower is updating every 10 minutes.

When using the Nightscout follower mode it syncs it's update time to the last glucose entry + 5 minutes. This will mean that xDrip checks NS before the most current reading is available, if it's not there it checks again in 5 minutes.

The 600 uploader posts the time of the reading as on the pump and this will be posted to NS at least 30+ seconds after that. This means that xDrip is syncing to the pump reading time and not the nightscout update time and causes xDrip to be up to 10 minutes behind.

**Comment by psit** [comment] 2021-03-16 00:03
I think this could easily be fixed by adding a (possibly customizable) delay to xdrips poll time. 
E.g: If the last BG value has a timestamp of `00:52:23`, the next poll should be at `00:57:53`, (+5:30) not at `00:57:23`, because at that time the value is read from the sensor by the pump. It has not been processed by the uploader or NS by then.

**Comment by Navid200** [comment] 2021-03-17 01:28
@Pogman Do I understand correctly that the uploader creates a discrepancy between the real upload time to Nightscout and the time value it gives it?

How can we fix this in xDrip?

xDrip can be used as a follower of Nightscout.  And it works perfectly fine for example if the uploader is another xDrip collecting from a G6 transmitter.

If we add a delay to when xDrip collects data from Nightscout, we will be delaying every follower even if they are working fine right now.

Shouldn't this problem be addressed at the uploader side?

**Comment by Pogman** [comment] 2021-03-17 02:21
The uploader reads sg data from the pump at around 30 secs after the pump has received them from the sensor. The entry sent to NS contains the time of the sg reading i.e. a reading at 12:00:10 will contain this timestamp while it may have been sent to NS at 12:00:40 (or even later).

I don't know what xDrip is doing precisely but it looks to be using the actual timestamp of the sg reading to base it's next check in time on causing this reporting delay.

Due to the nature of error handling and backfill etc, sg data may be sent at variable times but mostly at the usual 5 min cadence but always with the exact sg timestamp.

I don't see what the uploader can do about how a follower reads the data back from NS?

A suggestion would be to read NS at the current 5 min interval and if no new reading then at 1 min intervals until available.

**Comment by Navid200** [comment] 2021-03-17 02:27
I wonder how this is done when the collector is xDrip directly from a G6.
In that case, this problem does not occur.

@tolot27 Do you know what makes the difference in behavior between the two cases?

**Comment by tolot27** [comment] 2021-03-17 06:15
Likely a duplicate of #929 and PR #1307 tries to address this.

**Comment by psit** [comment] 2021-03-17 07:40
If someone can provide me an APK, I would happily test the PR. Just drop me a link.

**Comment by Navid200** [comment] 2021-03-17 14:11
@tolot27 Are there instructions somewhere for compiling an apk from a pull request?

**Comment by tolot27** [comment] 2021-03-17 14:28
> @tolot27 Are there instructions somewhere for compiling an apk from a pull request?

Google?

I do not recommend applying #1307 because it introduces another settings variable. The underlying problem should be solved in `Anticipate.java`.

**Comment by Navid200** [comment] 2021-07-19 12:08
There is an existing issue regarding this: https://github.com/NightscoutFoundation/xDrip/issues/929

Would you please refer to that and add comments there if/when needed?

**Closed by Navid200** 2021-07-19 12:08 UTC
Labels: duplicate
