### ISSUE TITLE
Won't stay connected to g6 transmitter

### ISSUE THREAD

**Issue by juliamyren** [NightscoutFoundation/xDrip#1501] opened 2020-11-08 21:46 UTC
Since the new update on my samsung galaxy s20+ the transmitter won't stay connected to the xDrip+ app. I keep getting a pop upp window to agree that the app should work with the g6 transmitter.

**Comment by tolot27** [comment] 2020-11-08 23:01
Duplicate of #1494.

**Closed by tolot27** 2020-11-08 23:01 UTC
Labels: duplicate
