### ISSUE TITLE
Issues with nightly build 2021.08.01

### ISSUE THREAD

**Issue by nathan990315** [NightscoutFoundation/xDrip#1796] opened 2021-08-02 07:17 UTC
The glycemic value is not shown on the main screen; and in the system notification. Even if the sensor is active. However you can see the sensor readings from the graph.
The nightly build is that of August 1st.
<img width="400" src="https://user-images.githubusercontent.com/17655407/127819483-45b797a0-4eb9-4442-b445-79f864316dfc.png" /><img width="400" src="https://user-images.githubusercontent.com/17655407/127819498-783f3d50-a7ab-4c11-a493-7061bf0375e9.png" />

**Comment by tolot27** [comment] 2021-08-02 07:48
Please try to revert to [2021.07.17](https://github.com/NightscoutFoundation/xDrip/releases/tag/2021.07.17) and report if the problem went away.

**Comment by nathan990315** [comment] 2021-08-02 09:04
I tried the 2021.07.31 and in this version I do not have this problem

**Comment by jamorham** [comment] 2021-08-02 09:29
@nathan990315 Can you let me know which handset model and android version this is with? thanks

**Comment by nathan990315** [comment] 2021-08-02 09:33
Nokia X20 and Android 11

**Comment by parapenT1sta** [comment] 2021-08-02 09:49
The same issue for me, Dexcom G5, Google Pixel 4a 5G with Android 12.

The numeric value wasn't updated but the graph was and for a while AndroidAPS was receiving the readings from xDrip matching with the graph dots values.

**Comment by jamorham** [comment] 2021-08-02 10:06
@parapenT1sta The main glucose value wasn't updated or it wasn't showing at all?

I'm preparing a new version I would like you both to try to see if you get the same issue.

**Comment by parapenT1sta** [comment] 2021-08-02 10:11
@jamorham The graph dots were being updated and working fine, only the value on the top right was stuck to the value I had before the update.

**Comment by parapenT1sta** [comment] 2021-08-02 10:12
@jamorham I will test the new version as soon you release it.

**Comment by jamorham** [comment] 2021-08-02 11:40
@parapenT1sta @nathan990315 Please try the latest nightly, it is also available here: https://github.com/NightscoutFoundation/xDrip/releases/download/2021.08.02/xDrip-plus-20210802-0af3ba0.apk
If it doesn't work just roll back to the 31st July version by simply installing that over the top.

**Comment by nathan990315** [comment] 2021-08-02 12:37
In the new version this problem has been solved for me

**Comment by parapenT1sta** [comment] 2021-08-02 12:48
Working fine here. Thank you!

**Comment by Thomas-Wolff** [comment] 2021-08-02 13:17
Hat leider nicht funktioniert, habe wieder auf den Bau vom 31.07 zurück gesetzt.

**Comment by tolot27** [comment] 2021-08-02 13:18
@Thomas-Wolff Which problem do you have? You did not posted in this issue before. Please report your complete environment and potential log entries.

**Comment by Thomas-Wolff** [comment] 2021-08-02 13:23
Blutzuckerdaten-Tabelle und Kalibrierungs-Tabelle waren nicht aufrufbar. Habe dann sofort auf den Bau vom 31.07 zurück gesetzt ohne noch weitere Tests durchzuführen sah für mich nach dem gleichem Problem wie vom Bau vom 02.08 aus.

**Comment by tolot27** [comment] 2021-08-02 13:27
@Thomas-Wolff Please write in English! If you don't speak English, use https://www.deepl.com/de/translator. It is much simpler if the creator of the comment translates the text just once instead of every issue worker.

**Comment by Thomas-Wolff** [comment] 2021-08-02 13:35
Sorry, The blood glucose data table and calibration table could not be called up. I then immediately reset to the build from 31.07 without carrying out any further tests - looked to me like the same problem as the build from 01.08.

**Comment by jamorham** [comment] 2021-08-02 13:47
@Thomas-Wolff Thanks, this is a separate but related issue which I can reproduce and will correct immediately.

**Comment by Thomas-Wolff** [comment] 2021-08-02 13:51
Thanks for the information, I will now continue with the construction from 31.07 as it is going very well.
Greetings Thomas

**Comment by Navid200** [comment] 2021-08-02 15:23
@doc77
>2021.08.02 seems to have wiped out the tasker plugin. Reinstalling 2021.07.31 restores the plugin.

**Comment by Navid200** [comment] 2021-08-02 15:27
@tolot27 @nathan990315 Would you please change the title of this issue to something, more general, representing the ongoing issues with the current Nightly releases?

May be:  Issues with the Nightly release August 1, 2021 and the ongoing work in progress

**Comment by jamorham** [comment] 2021-08-02 15:46
@Thomas-Wolff Can you try this latest version to see if it resolves the issue you reported: https://github.com/NightscoutFoundation/xDrip/releases/download/2021.08.02b/xDrip-plus-20210802-a8bca99.apk

**Comment by tolot27** [comment] 2021-08-02 15:54
@jamorham Opening BG and calibration data tables is now possible again.

**Comment by Navid200** [comment] 2021-08-03 15:25
I would like to close this issue as it seems to have been resolved.

**Comment by tolot27** [comment] 2021-08-03 19:13
Agree.

**Closed by tolot27** 2021-08-03 19:13 UTC
Labels: build-nightly

**Comment by bigdigital** [comment] 2021-08-22 14:01
Hi. I'm trying to compile the latest xdrip nightly build (18.08.2021) , the compilation completes successfully, but when i open data table or calibration table menu, the application crashes with an error `android.content.ActivityNotFoundException: Unable to find explicit activity class {com.eveningoutpost.dexdrip/com.eveningoutpost.dexdrip.tables.BgReadingTable}; have you declared this activity in your AndroidManifest.xml?
 at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2020)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1679)
 at android.app.Activity.startActivityForResult(Activity.java:4651)
 at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
 at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
 at android.app.Activity.startActivityForResult(Activity.java:4609)
 at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
 at android.app.Activity.startActivity(Activity.java:4970)
 at android.app.Activity.startActivity(Activity.java:4938)
 at com.eveningoutpost.dexdrip.utils.ActivityWithMenu.onNavigationDrawerItemSelected(ActivityWithMenu.java:54)
 at com.eveningoutpost.dexdrip.NavigationDrawerFragment.selectItem(NavigationDrawerFragment.java:218)
 at com.eveningoutpost.dexdrip.NavigationDrawerFragment.access$000(NavigationDrawerFragment.java:29)
 at com.eveningoutpost.dexdrip.NavigationDrawerFragment$1.onItemClick(NavigationDrawerFragment.java:77)
 at android.widget.AdapterView.performItemClick(AdapterView.java:318)
 at android.widget.AbsListView.performItemClick(AbsListView.java:1198)
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3178)
 at android.widget.AbsListView$3.run(AbsListView.java:4132)
 at android.os.Handler.handleCallback(Handler.java:873)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:201)
 at android.app.ActivityThread.main(ActivityThread.java:6810)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)`

It looks like there are some problems with the token preprocessor and it seems only on my end. I'm not sure how to fix this, do you have any advice? The problem appears after commit dated 02.08.2021
