### ISSUE TITLE
Guardian Connect

### ISSUE THREAD

**Issue by Schoggiweggli** [NightscoutFoundation/xDrip#215] opened 2017-11-14 23:09 UTC
Since Medtronic is reaaaaally slow at releasing an Android App or even update the iOS one to be considered a competition for Dexcom, is it possible to get it to work with xDrip?

I i am stuck with an iPhone because of it and i would love to change the device.

**Comment by hartlijn** [comment] 2018-02-17 19:13
For now only in combination with android uploader phone with the BG Meyer attached via OTG cable.

**Comment by Schoggiweggli** [comment] 2018-02-18 08:06
@hartlijn that's for the Pump combination. Guardian Connect is a standalone bluetooth transmitter.

**Comment by shtefanilie** [comment] 2020-10-17 19:30
@Schoggiweggli any news? Did you try with xdip? Does it work?

**Comment by Schoggiweggli** [comment] 2020-10-17 20:20
> @Schoggiweggli any news? Did you try with xdip? Does it work?

I don't know, sorry. Changed to Dexcom G6 a year ago and gave up on Medtronic entirely.

**Comment by tolot27** [comment] 2021-02-17 19:24
Duplicate of #131

**Closed by tolot27** 2021-02-17 19:24 UTC
Labels: device-guardian, enhancement
