### ISSUE TITLE
Unable to start crash reporter as app is restarting too frequently

### ISSUE THREAD

**Issue by Abdallahhjm** [NightscoutFoundation/xDrip#1836] opened 2021-09-24 18:20 UTC
Hi,
I installed Xdrip September 2021 nightly on my Samsung S21 phone to read from miao miao Libre. I received readings perfectly but each time I try to go to settings xdrip keeps shutting do. This is the first time I use xdrip. I deleted and then reinstalled, again I managed to complete the configuration process and stated receiving data but same issue again, xdrip is closing when i press settings. Can you please help to fix the issue.

**Comment by Navid200** [comment] 2021-09-24 19:29
Please don't open an issue as soon as you experience a problem.
As you were asked, please use the support channels.
https://github.com/NightscoutFoundation/xDrip/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

If there is a need to open an issue, we will ask you to open one.

**Comment by Navid200** [comment] 2021-09-25 21:33
![242815908_235704588509028_8506317682365584397_n](https://user-images.githubusercontent.com/51497406/134786412-89f82cea-3b67-486a-9e51-178ab8420dbf.jpg)

![242832484_235704655175688_876916528790871861_n](https://user-images.githubusercontent.com/51497406/134786427-e2d2ff4a-094e-4ad7-b9ed-5b070199945b.jpg)
![242804044_235704721842348_2012087851398896112_n](https://user-images.githubusercontent.com/51497406/134786453-1c8af8b5-84a6-4d55-8423-8873137b2a9d.jpg)

**Comment by Abdallahhjm** [comment] 2021-09-26 06:38
I'm still facing the same issue. I noticed even if i press on HISTORY xdrip crashes. Other items in the menie are ok. I installed "https://github.com/NightscoutFoundation/xDrip/releases/download/2021.01.02/xDrip-plus-20210102-51d003c.apk" as per Navid advice as an update but this time xdrip did not open and kept crashing immidiately.

**Comment by tolot27** [comment] 2021-09-27 05:25
@Abdallahhjm We still don't know you Android version.
Does it work with a previous xDrip version?

**Comment by Navid200** [comment] 2021-09-27 12:22
It's a very recent phone.  I think it came to the market in January of 2021.  I think it comes with Android 11.
@Abdallahhjm Please correct me if I am wrong.

As he has explained in his second post in this thread, after installing January 2, 2021 version of xDrip, xDrip keeps crashing without even opening.
He originally had September 2, 2021 and after setting up everything and getting readings, xDrip would crash if he attempted to open settings.
So, going back to Jan. 2, 2021 made things even worse.

**Comment by Abdallahhjm** [comment] 2021-09-27 18:35
Yes it is Android 11, One UI version 3.1

**Comment by Abdallahhjm** [comment] 2021-09-27 18:37
![20210927_223141](https://user-images.githubusercontent.com/91137859/134966052-e776d1b1-8fea-4ef3-8aec-4da81f6cb39b.jpg)

**Comment by Abdallahhjm** [comment] 2021-09-27 18:38
![Uploading 20210927_223210.jpg…]()

**Comment by Abdallahhjm** [comment] 2021-09-28 11:39
Please help me to fix this issue so I can utilize xDrip functions fully. I use xDrip (mm2/libre) for my 7 years old son who is T1D. I urgently need to set up followers account to enable me and my wife to monitor his readings while he is at school or playing around with his friends. I'm not even getting high & low alrams. Thanks.

**Comment by Navid200** [comment] 2021-09-28 12:53
@Abdallahhjm Is S21 your son's phone, the master?  Or, is it your phone, a follower?

**Comment by Navid200** [comment] 2021-09-28 13:01
@Abdallahhjm Would you please list the steps you take, in the order you took them, after a fresh install, which result in not being able to access the xDrip settings any longer?  I hope you can create a short list so that we can see if there is any unnecessary step that could be the cause, which we can ask you to avoid.
Also, please clarify if S21 is not the master, in which case, please state what is.

**Comment by Abdallahhjm** [comment] 2021-09-28 13:43
S21 is the master used by my son. I followed the normal steps to set up xdrip, installed it, then it requested 2 callobration test results which I did provide and i started getting readings. When I tried to access settings to set up follower phones and set other functions, xDrip kept crashing the moment i press in settings.

**Comment by Abdallahhjm** [comment] 2021-09-28 14:05
I dont remember any specific step during installation, i just installed and opened, next xdrip was obtaining readings, then it asked for the two calibration tests. Please remind me if anything else. I dont want to uninstall and reinstall at this stage unless you ask me to do so in order to find out if i missed something or did something wrong.

**Comment by Navid200** [comment] 2021-09-28 14:11
@Abdallahhjm Is there any security apps you have installed on your son's phone that may be enforcing any restrictions?

**Comment by Abdallahhjm** [comment] 2021-09-28 14:54
No, the phone comes with samsung kids mode so there was no need to install something extra. The kids mode is off when i'm facing xdrip crashing so i dont think it is related. I'm not sure though if there are phone default settings that are causing this. Please let me know of any specific place I need to check?

**Comment by Navid200** [comment] 2021-09-28 15:00
@Abdallahhjm Is there an older phone in the house your son is willing to take with him until we can figure out what's going on?  I have asked the developers to look at this.  But, it may take a while.
If you have a different phone in the house, you can set it up as the collector and have your son carry it with him.

After we figure out what the problem is and resolve it, you can switch back to S21.
There is no way I can guarantee to fix this right away.  The developers are all volunteers.

**Comment by Abdallahhjm** [comment] 2021-09-28 15:41
It was originally set to Arabic, I changed it later to English. I can send you fresh one if you like. Yes I can access logs. Not sure how to export settings to system file?

**Comment by Abdallahhjm** [comment] 2021-09-28 15:42
Meant phone language.

**Comment by Abdallahhjm** [comment] 2021-09-28 15:45
Item snooze alert works yes. I mean I can open it and change the snooze frequency. Yes, the crash only occurs when I tap on history or settings.

**Comment by Navid200** [comment] 2021-09-28 17:25
@Abdallahhjm When you set up everything, after installing xDrip, did you enter any user ID or password in xDrip?
For example, did you enter your Nightscout ID and password?

**Comment by Abdallahhjm** [comment] 2021-09-28 18:31
No, I did not enter any password. I managed to export settings to system file, how do you want me to share?

**Comment by Abdallahhjm** [comment] 2021-09-28 19:58
![Screenshot_20210928-235042_HTML Viewer](https://user-images.githubusercontent.com/91137859/135156882-65792749-df34-47e1-a363-8d418f3ea4a3.jpg)

**Comment by Abdallahhjm** [comment] 2021-09-28 19:59
![Screenshot_20210928-235108_HTML Viewer](https://user-images.githubusercontent.com/91137859/135157012-810ecc3b-5f3d-487e-bd82-9e1140607f8a.jpg)

**Comment by Abdallahhjm** [comment] 2021-09-28 19:59
![Screenshot_20210928-235356_HTML Viewer](https://user-images.githubusercontent.com/91137859/135157158-7004467f-765d-4ce6-b1b7-cddc9f1e58c2.jpg)

**Comment by Abdallahhjm** [comment] 2021-09-28 20:04
![Screenshot_20210928-235412_HTML Viewer](https://user-images.githubusercontent.com/91137859/135157740-93fc3002-d5e0-47ff-8c9a-d65e3834e7fb.jpg)

**Comment by Abdallahhjm** [comment] 2021-09-28 20:06
![Screenshot_20210928-235412_HTML Viewer](https://user-images.githubusercontent.com/91137859/135157914-9ea9d2ec-3211-462e-ab16-656699b0e12d.jpg)

**Comment by Abdallahhjm** [comment] 2021-09-28 20:09
![Screenshot_20210928-235445_HTML Viewer](https://user-images.githubusercontent.com/91137859/135158228-236ed516-8542-4bcb-aee6-b13caf48fed3.jpg)

**Comment by Abdallahhjm** [comment] 2021-09-28 20:12
![Screenshot_20210928-235506_HTML Viewer](https://user-images.githubusercontent.com/91137859/135158773-384cc846-2b3f-423e-b0fc-2572d07ec1de.jpg)

**Comment by Abdallahhjm** [comment] 2021-09-28 20:17
![Uploading Screens٢hot_20210928-235506_HTML Viewer.jpg…]()

**Comment by Abdallahhjm** [comment] 2021-09-29 03:42
![Screenshot_20210928-235356_HTML Viewer](https://user-images.githubusercontent.com/91137859/135199442-b1cc998d-29e9-4b8e-865f-f43f53c65d61.jpg)

**Comment by tolot27** [comment] 2021-09-29 05:16
@Abdallahhjm I just need the xml file. Please send me a private message or contact me at https://gitter.im/tolot27. I'll delete the screenshots in this issue to keep it clean.

**Comment by Abdallahhjm** [comment] 2021-09-29 07:14
Sorry can't find my way to private messages. I'm new to github. Please direct me. Thanks.

**Comment by tolot27** [comment] 2021-09-30 19:10
As @Navid200 pointed out in the dev group, this issue is likely related to #1630.

**Comment by Abdallahhjm** [comment] 2021-10-05 14:10
@tolot27 I have sent you history settings file as requested. Please have a look.

**Comment by tolot27** [comment] 2021-10-05 20:11
@Abdallahhjm What does the hamburger menu show regarding the sensor: start sensor or stop sensor? If it says "start sensor" please press it and try to start the sensor, even if you are just a follower. After that please try to open history and report if the error persists.

**Comment by Abdallahhjm** [comment] 2021-10-13 14:20
Any solution yet?

**Comment by Navid200** [comment] 2021-10-13 14:34
I have seen people using your exact same setup, MiaoMiao with S21, without crashes.
That doesn't prove anything.  It's just a piece of info to keep in mind.

**Comment by Navid200** [comment] 2024-03-10 21:20
What is the status?
Have you been able to use xDrip?

**Comment by Navid200** [comment] 2024-03-21 21:59
I am closing this because we have not heard enough to be able to recreate the problem.
We can always reopen if experienced again.

**Closed by Navid200** 2024-03-21 21:59 UTC
Labels: bug
