### ISSUE TITLE
Starting G6 sensor and Xdrip not asking for code

### ISSUE THREAD

**Issue by Gonzmdv** [NightscoutFoundation/xDrip#746] opened 2019-01-15 11:53 UTC
It's the second time I start a  G6 sensor and Xdrip doesn't ask for the sensor code, directly gives blood glucose values.
Should I have "Go on without calibrations" checked or unchecked?
Should I calibrate it?
How can Xdrip give glucose values without code or calibration?
For the first time, I also remember Xdrip asking for the insertion time.
Could you please give me some help?
Thank you.

**Comment by jamorham** [comment] 2019-01-15 13:07
It sounds like your sensor wasn't in a stopped state. If it is a new sensor then make sure to use the `Stop Sensor` menu item and the `Start Sensor` menu item to start a new sensor. With G6 it will then ask you for the code.

**Comment by Gonzmdv** [comment] 2019-02-01 15:14
Today I started a new sensor. To avoid the same problems I did it using the phone as collector. Same result. Last nightly update installed.
I stopped the sensor and removed the old sensor. Then Xdrip asked for calibration. I don't know why. I answered "No, thanks". Then, immediately, it was asking for a new sensor. As soon I connected the transmitter to the new sensor, without doing anything, Xdrip was showing "2 Hours warm-up", so I couldn't press "Start new sensor". Two hours later I was having a glucose reading that was completely wrong. Then I added calibration pressing "Initial calibration" (there shouldn't be initial calibration, true?). Although the calibration worked, I received the message "Calibration rejected: unknown code 17" .

I would appreciate some help or your experiences starting a G6 sensor. Thank you.

**Comment by gitanO0** [comment] 2019-02-01 15:17
I got this as well... Not sure what the proper procedure is to make sure these transitions go smoothly.

**Comment by Gonzmdv** [comment] 2019-02-01 15:23
I was having a look at Settings again.
What is this for? "Restart Sensor: Automatically restart a sensor when it stops"
I have it checked, but I thought It was used in case the sensor was stopped by fail. 
Could it be my problem?

**Comment by Flori3000** [comment] 2019-02-01 22:51
Automatically restart is used when you reach day 9 of your sensor session.

**Comment by Gonzmdv** [comment] 2019-02-21 22:02
This time I unchecked "Restart Sensor" and kept checked "Preemptive restarts" and "Go on without calibrations".
I had to "Stop sensor" two or three times  because I got several "Please enter two calibrations to get started" and one "Calibrate Sensor? We have some readings" but then I stopped sensor again and could press "Start sensor". Then Xdrip asked for G6 Sensor code and could start normally.

**Comment by Gonzmdv** [comment] 2019-03-15 12:32
Changed sensor today.  Version c549ee5-2019.03.14 Code 1903142206.
Everything ran smooth for the first time since my first G6 sensor start in December. Not a single problem.
Only the watch (Sony Smartwatch 3) said "G6 Start Failed: Session Start Failed : Unknown Code 6". Ignored and no problem.
Settings:
Restart Sensor: unchecked
Preemptive restarts: checked:
Go on without calibration: checked
We are in the correct way, thank you jamorham.

**Comment by jlecount** [comment] 2019-06-04 17:19
I am also noticing that I'm no longer prompted for a code -- I'm using g6 sensors and am on build 14a03a7-2019.05.18 Code 1905181006, g6 native.  

The calibration code being shown is incorrect, though I have not been prompted (for at least a month or so) for a new one.  Every time I replace my sensor, I do 'stop sensor', then take it off, then put a new one on and 'start sensor'

What other information might be helpful to diagnose?

Thanks!

**Comment by Gonzmdv** [comment] 2019-06-04 18:26
Everything has been working correctly for me lately. Not a single problem changing the sensor. I'm asked for the calibration code and the sensor position. Anyway, I usually do a blood test after the warm up because the resulting glucose value sometimes is not very accurate.

**Comment by jlecount** [comment] 2019-06-04 18:33
Does anybody have insight into what settings might be related?   I can post the QR code for my entire settings if that's useful.

**Comment by Gonzmdv** [comment] 2019-06-04 18:42
My main settings are:

Use the OB1 Collector - Yes
Native Algorithm - Yes
RESTART SENSOR - NO
Preemtive restarts - Yes
Go on without calibrations - Yes
Fallback to xDrip - No
Minimize Scanning - No
G6 Support - Yes
Allow OB1 unbonding - Yes
Allow OB1 initiate bonding - Yes

I hope it helps.

**Comment by jlecount** [comment] 2019-06-04 18:51
Thanks @Gonzmdv -- My settings were identical except for preemptive restarts and go on without calibrations.  I'd be skeptical if those are the cause, since they seem pretty unrelated, but I've enabled those anyway just to see.

Cheers,
Jason

**Comment by jamorham** [comment] 2019-06-04 20:46
@jlecount If you are using the OB1 collector and have G6 option enabled then it should ask you for a code when starting a sensor.

**Comment by jlecount** [comment] 2019-06-04 21:13
Aha, I _just_ turned that on last night.  I had it turned off previously.    This is undoubtably the issue!

If I wanted to force it to update the code, can i stop and start the sensor harmlessly?

**Comment by jamorham** [comment] 2019-06-04 22:19
@jlecount yes you can stop and start the sensor. The only harm will be that the internal algorithm may be slightly confused because the sensor has already been in for a while but you should be able to correct this by applying a calibration.

**Comment by jlecount** [comment] 2019-06-04 22:30
Great, thanks again.  Can you tell me what the purpose of the "when did you insert" prompt is?  What does it affect?

**Comment by jamorham** [comment] 2019-06-05 21:42
@jlecount It affects the "wound healing" adjustment of the raw value which is an exponential fall off curve over the first 1.9 days. It only applies when using internal xDrip calibration algorithms. Not the native algorithm, but we still ask so that it is possible to switch between algorithms if anyone wanted to do that.

**Comment by jlecount** [comment] 2019-06-05 21:47
@jamorham Thanks for the insight!  BTW, I love this project -- it's made a HUGE difference in my quality of live, as somebody with T1D.  Thank you!

**Comment by Navid200** [comment] 2021-02-16 19:41
Please use the support channels for asking questions about how to use xDrip.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

I am closing this issue.
Please open an issue only if you have discovered a bug, or you believe there is a need for a new feature, which cannot be accomplished with xDrip as is.

**Closed by Navid200** 2021-02-16 19:41 UTC
