### ISSUE TITLE
Unable to select sounds for Extra Alerts features

### ISSUE THREAD

**Issue by cybernissart** [NightscoutFoundation/xDrip#1862] opened 2021-10-26 07:12 UTC
### Environment
Xdrip+ c98a3c4 2021.10.17

Xiaomi Redmi Note 9 pro running Android 11 Miui 12
Xiaomi Redmi Note 10 pro running Android 11 Miui 12

Issue exists for quite long time so applies to old release as well.

### Actual behavior
When clicking on 'Persistent High Sound' and 'Predicted Low Sound' menus, application hangs and returns to main graph menu without presenting the list for selecting a system sound.

This seems to be related to the Android function allowing access to file system, as it works correctly on a Samsung S7 device running Android 7

### Expected behaviour
Application unable then to play sound for preventive low and persistent high alerts

### Steps to reproduce the behavior:
Go to Settings > Extra Alerts (xDrip+)
Select "Persistent High Sound" or
Select "Predictive Low Sound"

This seems to be related to the Android function allowing access to file system, as it works correctly on a Samsung S7 device running Android 7

**Comment by Navid200** [comment] 2021-10-29 21:46
https://user-images.githubusercontent.com/51497406/139505112-bdccbbd6-f2ad-4b4d-b1cf-0871c567252c.mp4

**Comment by LTorrao** [comment] 2021-10-31 11:46
Same issue here with:

Xiaomi Redmi 7A, Android 10
Xiaomi Pocophone F1, Android 10
Xiaomi 11T Pro, Android 11

Worked previously on Samsung S7 Android8.

Could this be a MIUI issue?

**Comment by Navid200** [comment] 2022-04-24 23:21
@tzachi-dar Any idea what could be causing this?

**Comment by tolot27** [comment] 2022-04-25 04:41
I've an Xiaomi Mi A1 and can try to reproduce it but it has an older Android version.
Is there anything shown in the logs?
Maybe it is related to #1781?

**Comment by Navid200** [comment] 2022-05-12 04:22
@cybernissart Are you still experiencing this problem with the latest Nightly?
If yes, please respond to the questions posed here by a developer.
Or, we can close the issue.

**Comment by jamorham** [comment] 2022-05-26 21:11
Not able to reproduce on Redmi Note 8 pro MIUI version 12.0.5 Android 10 or MIUI 12.5.5 Android 11. I get to a screen to select a notification sound. I haven't checked whether it actually selects that sound but it doesn't fail to display that page.

**Comment by Navid200** [comment] 2022-05-26 21:21
@cybernissart Thanks.  I'm closing then.

If you find out which version was the last that still had this problem, please let us know, which would be useful to have here for the records.  

We can always reopen if anyone experiences this again.

**Closed by Navid200** 2022-05-26 21:21 UTC
Labels: bug, ux-alarm
