### ISSUE TITLE
xdrip+ not synchronising all glucose data points from Nightscout when the measurement insert rate is > 1/5 minutes (libre)

### ISSUE THREAD

**Issue by jeremystringer** [NightscoutFoundation/xDrip#1518] opened 2020-11-20 23:36 UTC
Two setups:
1) Using glimp as an NFC scanner and uploader from a Libre 1 sensor, inserting to Nightscout (14.0.6)
2) Using glimp + Miao Miao as an uploader from a Libre 1 sensor, inserting to Nightscout.

Xdrip+ (current master branch, as of 13/11/2020) was set to act as a Nightscout follower for a primary data source.

The issue that I saw was that I had missing data points in the BG graph - so in case 1) I would scan after a couple of hours, and I would have good recent data, but also a big gap since I had last scanned.

In case 1), looking at what happened more closely, I noted that glimp would upload all of the readings from the Libre.  This meant ~ 15 readings one minute apart, followed by readings every 15 minutes from the older data.

In case 2), I noted that glimp was doing readings 1/minute - I would assume from the behaviour that it is reading every 5 minutes, and getting data by the minute.  This tallies with what I see on the Nightscout website.

Looking through the code, I noted the following in app/src/main/java/com/eveningoutpost/dexdrip/cgm/nsfollow/NightscoutFollow.java:

In function 'work', it uses the MissedReadingsEstimator to estimate a count of missed readings, which it then passes as count parameter on the REST query to limit the number of results returned.

The line is:
int count = Math.min(MissedReadingsEstimator.estimate() + 1, (int) (Constants.DAY_IN_MS / DEXCOM_PERIOD));

This is then followed by another line that ensures that you get at least 10 readings:
count = Math.max(10, count);

In app/src/main/java/com/eveningoutpost/dexdrip/evaluators/MissedReadingsEstimator.java it appears to estimate missed readings as being the number of 5 minutely readings that would fit within the time period since the last BG reading.

(I am not particularly familiar with javascript BTW - so this is the best I could make of it).

So - it looks to me like this method of estimating missed readings and using this count to limit the web query is probably the source of the behaviour.

I tried an experiment, and modified the value to 23 (This is roughly where 15 x 1 minute updates + 1 update / 15 minutes crosses over with a flat 1 update / 5 minutes).
count = Math.max(23, count);

I noted that the synchronisation didn't have gaps in case 1), under the specific conditions that xdrip was syncing more often than the Libra was being scanned.

In case 2) however, I still see gaps if I sync after a while (say, an hour) - which would be consistent with the behaviour above, as I can see on the Nightscount website that the data is being inserted once per minute (Increasing the minimum count is really just band-aiding the issue for some specific usage patterns).

One thing I haven't tried yet is to modify the query to be date-based - for example, something like:
https://your.nightscout.site/api/v1/entries?find[date][$gte]=1605904430000@count=<pick a large value for count>

There are also a couple of potential implications I was wondering about though:
* This will increase the number of results returned, at least under this scenario.  How does this affect Heroku resource limits?  Any potential issues with increased handset data?
* How does this affect local DB storage on the handset?
* Is there any variation in the Nightscout API, where this might not work with older versions?
* Would it potentially run into server-imposed limits on counts in the future?  (Requiring multiple requests if not enough data is returned).

**Comment by tolot27** [comment] 2020-11-21 21:19
The problem is caused by the `MissedReadingsEstimator` which assumes one reading every five minutes (`DEXCOM_PERIOD`).

**Comment by jeremystringer** [comment] 2020-11-25 08:44
Had a go at modifying the query.  

The original query had a rr=<timestamp> on the end, but I couldn't find this parameter in the nightscout source code, and didn't see it do too much when trying the queries directly with a web browser.

Modified the query to use the find parameter, based on the timestamp from the last BG reading.
        Call<List<Entry>> getEntries(@Header("api-secret") String secret, @Query("count") int count, @Query("find[date][$gte]") String rr);

Note that this changes the behaviour from querying the current time and retrieving a fixed number of samples to querying the most recent <count> samples since the given start time.  (A better change might be to take the most recent of (-24 hours, last BG reading timestamp).

Patched in this to adjust:
BgReading bgReading = BgReading.last(); 
long searchDate = bgReading != null ? bgReading.timestamp : (JoH.tsl() - (1000*60*60*24));
		
getService().getEntries(session.url.getHashedSecret(), count, searchDate + "").enqueue(session.entriesCallback);

(Basing this off MissedReadingEstimator - there will be a tidier way to do it)

Also, increased the count to a static count of (60*24), given that the date now bounds the search.

Net result of these changes was that I could see all of the data in the range being downloaded at startup (Checked with adb logcat), but only a reduced amount of data begin displayed on the graph.

Had a quick look at app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/BgGraphBuilder.java, and tried changing this line:

    private static final int NUM_VALUES = (60 / 5) * 24;

to:

    private static final int NUM_VALUES = (60) * 24;

After this, the full graph showed up.

Will give these changes a try for a few days, see if anything else shows up.

**Comment by Navid200** [comment] 2021-08-07 14:47
@jeremystringer Thanks for sharing.
What is the status of this?

**Comment by jeremystringer** [comment] 2021-08-08 08:41
Hey @Navid200, I trialed the change above and it worked well for me.  The only caveat I found is that after a number of months, it did get less responsive (At which point I cleared data for the app, and this issue went away).  That said, I don't know if it would have become less responsive anyway.

I've attached some diffs of my changes - I can't regression test though (with the original scenario), as we've since moved from libre to dexcom to get pump integration.

[diffs.zip](https://github.com/NightscoutFoundation/xDrip/files/6950427/diffs.zip)

The changes aren't completely clean (Comments need a little cleanup), nor do they consider all scenarios - I've attached the files as-is, rather than editing, as they have at least been tested as-is.  Note that the EntryProcessor.java change is purely for debug.

My tree was based on hash a91b660ec68809418a7904fa8f710beb3c8ab937 (Tag 2020.10.01).

Happy to put them somewhere if it helps - with the caveat, as mentioned above, that I'm not particularly familiar with the language, or the xdrip code.

**Comment by Navid200** [comment] 2021-09-23 12:20
@jeremystringer Is this not related to the following?
https://github.com/NightscoutFoundation/xDrip/issues/929

**Comment by jeremystringer** [comment] 2021-09-25 23:52
> @jeremystringer Is this not related to the following?
> #929

I don't believe so, at least looking at the behaviour and the proposed fix for #929.  #929 appears to be about delays getting data from system to system accumulating, causing data not to be available for a while on a follower handset (Complicated, perhaps, by lack of time synchronisation).

This is different - this is essentially that with a libre + glimp as an uploader, more data than expected (> 1 point / 5 minutes) gets inserted into nightscout from the master handset, and the follower handset (with xdrip+) doesn't query enough data to build a full graph, as it bases how much data to query on an estimate of 1 point / 5 minutes.

One big difference with libre + glimp as an uploader is that with the libre you get 15 minutes worth of 1 minute values each time you read (1 point / 1 minute) + historical data (15 minutely, from memory).  Glimp just uploads it all (or did when I raised the bug, at least)

**Comment by AidasK** [comment] 2022-07-19 12:41
Seeing similar results. My setup:
1. Libre v3 Uploads glocose every minute to Nightscout
2. XDrip uses nighscout follower source.

My setup is correct and all data is seen in history. [Image attached] Though on the main screen same data is not available, only some of it. I can see only last 6 hours, which is 1/4 of all data.

I can confirm that this is xdrip only issue with these images:
History (full day is available)
![history](https://user-images.githubusercontent.com/2088484/179752137-765b7a12-e9af-40d8-8eae-eae2328b506b.png)
Current main view (not all data is shown as in history):
![current](https://user-images.githubusercontent.com/2088484/179752262-e34bc8e0-8b44-4dff-bddb-1a05db0e3a00.png)

One additional issue, which I don't see here, what on my garmin watch venu 2s, also only part of the graph is available (picture was taken a bit later, so graph does not match)
![image](https://user-images.githubusercontent.com/2088484/179752641-4f9af845-51dc-4e5a-ae23-87bb3f8afdef.png)

**Comment by jakobheyman** [comment] 2022-07-19 20:21
This issue can perhaps be fixed by changing NUM_VALUES (not dividing by 5) here:
https://github.com/NightscoutFoundation/xDrip/blob/9fcaafeb729c0eb0e0988fbd96322d292649efd4/app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/BgGraphBuilder.java#L114

**Comment by AidasK** [comment] 2022-07-20 06:37
The better change probably would be to calculate num values dynamically based on how many data points we have in the past 24 hours.

**Comment by jamorham** [comment] 2022-07-20 07:52
@jakobheyman yes this is correct, I have been testing this.

**Comment by Navid200** [comment] 2022-07-21 20:09
Can everyone try the following release and provide feedback if the problem has been resolved or not?
https://github.com/NightscoutFoundation/xDrip/releases/tag/2022.07.21

**Comment by AidasK** [comment] 2022-07-22 06:43
On the phone, looks great! Thank you a lot! On the watch, not so great. Same issue :/

Watchface I am using is(not sure who is responsible for displaying all data points here):
https://apps.garmin.com/en-US/apps/8fab3746-f56f-4b41-b3c7-5f4aaeaed6c9

![watch](https://user-images.githubusercontent.com/2088484/180379278-63963bc0-42d7-4f79-9d05-183230470a5f.jpeg)
![phone](https://user-images.githubusercontent.com/2088484/180379282-a694ba1d-fee4-4ed6-b38d-94bf5ea0388c.png)

**Comment by swissalpine** [comment] 2022-07-26 08:36
The problem does not only affect the output in xDrip+, but, as the images of the clocks show, also the display on end devices that rely on the web service.
Especially with Garmin watches, the problem is that the amount of the query is very limited to 8 kb, but also the background process itself by which the data is processed is not much larger. Therefore, no more than 24 values should be queried (count=24) to be on the safe side.
Therefore, it is not a solution to query more data and evaluate only every 5th value.
The web service should therefore provide a way to output only one value every 5 minutes.
My watchfaces uses the following query:
http://127.0.0.1:17580/sgv.json?brief_mode=Y&count=24&all_data=Y
Thanks a lot!

**Comment by Navid200** [comment] 2022-07-26 12:12
@AidasK Would you please try the version that was just released and let us know how it works?
https://github.com/NightscoutFoundation/xDrip/releases/tag/2022.07.26

**Comment by swissalpine** [comment] 2022-07-26 14:09
Thank you for your efforts. I hope I'm not completely off the mark. But after looking at the PR, I suspect that can't be the solution. @AidasK is not using an Android Wear device, but a Garmin watch with a non Android firmware. This can only query bg values via the web service. Here, in the json response of the web service, the output would have to be reduced (and not extended).
For example, by changing line 164 in WebServiceSgv.java so that for minutely readings (Libre3) only every 5th value is returned:
```
                // for each reading produce a json record
                for (BgReading reading : readings) {
```

**Comment by AidasK** [comment] 2022-07-26 18:09
![image](https://user-images.githubusercontent.com/2088484/181079845-b486b19b-0aa7-4a43-a73e-6023e8abb972.png)
Right on spot @swissalpine. I have tried given release and that's what I've got, data points are still missing.

**Comment by Navid200** [comment] 2022-07-26 18:28
@swissalpine Can you compile what you are suggesting and test it?

**Comment by jamorham** [comment] 2022-07-26 18:58
The issue is mostly because of the bug in the nightscout follower code which allows records to be stored at a higher frequency than the collector would typically allow. 

I think the best way to address this is a de-duplicator in BgReading which I will work on.

**Comment by swissalpine** [comment] 2022-07-28 08:44
> @swissalpine Can you compile what you are suggesting and test it?
@Navid200 Thanks for coming back! I can compile it, but since I don't use a Libre sensor myself, a test is relatively useless.

But many thanks to @jamorham, a filtering or a data reduction during import would also be a possibility.

**Comment by swissalpine** [comment] 2022-08-01 15:43
@jamorham Thanks a lot! Unfortunately I can't test this fix (as written above, I'm not a Libre 3 user).

**Comment by jamorham** [comment] 2022-08-01 15:45
@swissalpine you can check this change doesn't break the collector you are using ;)

**Comment by swissalpine** [comment] 2022-08-01 15:50
No, it doesn't. My Garmin Watchface, Datafield und Widget show values at 5 minute intervals.

**Comment by AidasK** [comment] 2022-08-01 17:19
Unfortunately libre 3 patch has dropped of my arm since it's using less adhesive than libre2 so I can not test it out at the moment. I will be using libre 2 for a month or more before retrying this test again. Hope to test it out once more as its' form factor is really appealing.

**Comment by Navid200** [comment] 2023-05-30 16:58
@AidasK Have you been able to test?

**Comment by AidasK** [comment] 2023-05-30 17:13
Unfortunately no, I have moved to dexcom g6 sensor for now since it is covered by insurance. No plans to get back for now.

**Closed** 2023-05-30 17:19 UTC
Labels: bug, sync-nightscout
