### ISSUE TITLE
xdrip LibreAlarm interprets the values ​​of DiaBox incorrectly

### ISSUE THREAD

**Issue by RainerTischnet** [NightscoutFoundation/xDrip#1369] opened 2020-06-19 18:08 UTC
diabox sends the value 68 and xdrip calibrate with value 8

**Comment by RainerTischnet** [comment] 2020-06-19 18:22
![Screenshot_20200619-183740](https://user-images.githubusercontent.com/49461374/85168371-938d2600-b26a-11ea-9fb5-6b51c821c232.jpg)

**Comment by Navid200** [comment] 2021-03-15 18:14
@RainerTischnet Would you please close this issue if it has been resolved?
Otherwise, you can get a lot of useful information from the support channels.  You can post and ask questions and even developers frequent them and will answer questions.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by jjosten001** [comment] 2021-04-06 09:58
Hello,

getting nearly similar message:

"Could not process data structure from LibreAlarm:
java.lang.NullPointerExeption. Attempting to read from 
filed 'com.eveningoutpost.dexdrip.Models Readingdata
com.eveningoutpost.dexdrip.Models.ReadingData$ TransferObject date' on a
null object reference"

Any idea how to get the cause?

Versions:
xdrip+ nightly 38fee03-2021.03.31
DiaBox V:2021.04.02.1

Thx, Joerg

**Comment by Navid200** [comment] 2021-07-08 03:57
@RainerTischnet I read your first post, which talks about values 68 and 8.  Then, I look at the logs you have attached an image of.  I see neither 8 nor 68 in the logs.  So, I have no idea what the purpose of the image is.

Would you please add more detail and we can reopen the issue if needed?
But, youc an get a lot of information if you consult with other users using the support channels I provided above.

**Closed by Navid200** 2021-07-08 03:57 UTC

**Comment by tolot27** [comment] 2021-07-08 07:39
@RainerTischnet This issue should be addressed by the @bubbledevteam. Did you contact them, already?
