### ISSUE TITLE
xdrip on oneplus 5 with ticwatch pro

### ISSUE THREAD

**Issue by paaascal** [NightscoutFoundation/xDrip#1079] opened 2019-11-04 03:40 UTC
lately i tried using stand alone, didnt work anymore, tried few things unistalled reinstalled, now nothing works except NFC.  looking in the log i get continual "got null pointer trying to set cccd descriptor".  miao manages to get connected but shortly after (minutes), its noted as "not connected".  i click restart connector and its connected again...

in running nov 2 nightly

what should i dooooo? :)

thanks!

**Comment by paaascal** [comment] 2020-10-29 18:58
got ticwatch pro 3 still not working as standalone... xdrip latest version + libre 1 on miaomiao 2

could anyone help me set it to run standalone?

**Comment by tolot27** [comment] 2020-11-04 07:02
Please go through the other [ticwatch related issues](https://github.com/NightscoutFoundation/xDrip/issues?q=is%3Aissue+ticwatch). Maybe, there is any hint to get it working.

**Comment by tolot27** [comment] 2020-11-04 07:06
@paaascal As you mentioned in the other issue that it worked about two years ago, please report back the latest working version. That will help narrowing down the issue.

**Comment by tolot27** [comment] 2020-11-04 07:34
Isn't this issue a duplicate of #1048 as well, is it? The only exception is the different phone in use. But this is unrelated to the standalone functionality.
Hence, closing it in favor of #1048.

**Closed by tolot27** 2020-11-04 07:34 UTC
Labels: bug, device-libre, device-miaomiao, device-ticwatch, duplicate
