### ISSUE TITLE
xDrip Does not send local broadcast

### ISSUE THREAD

**Issue by Moshikol** [NightscoutFoundation/xDrip#661] opened 2018-11-01 15:50 UTC
Hello all,
After the latest update for some reason, the app stopped sending local broadcasts.
I'm following the logs (Recent Errors/Warnings) and there is no mention of broadcast sent even though the local broadcast setting is enabled.
I also tried to  update to the latest nightly build and still nothing .
I'm using Android 8.0.0 on Samsung Galaxy A5(2017).
Does Anyone have a clue why it's happening?
Thanks in advance!
Here is ScreenShot of the settings
![screenshot_20181101-174818_xdrip](https://user-images.githubusercontent.com/19548879/47862723-776f1380-ddfe-11e8-90d7-5d3e2943c261.jpg)

**Comment by classchneider** [comment] 2020-11-15 08:08
I see this same problem from time to time, it works for some hours then it stops working without any notification. Has set up a workaround in AndroidAPS to fill the gaps with data from NS, as xDrip uploads data to NS without any problem.
But doing this makes the loop rely on internet access and the NS database.

**Comment by Navid200** [comment] 2021-09-11 15:04
@Moshikol You say "After the latest update".

Would you please identify the last xDrip release that worked?

**Comment by classchneider** [comment] 2021-09-13 06:20
Sorry if I haven't closed the report. All is working fine presently.

lør. 11. sep. 2021 17.04 skrev Navid ***@***.***>:

**Comment by Navid200** [comment] 2021-09-13 12:40
@classchneider Are you saying the local broadcast is working fine now?
If that's what you are saying, can I close the issue then?

**Comment by Navid200** [comment] 2021-09-13 12:41
@classchneider This is not your issue.  So, you cannot close it.
But, can you please confirm that it is working fine now?

**Comment by classchneider** [comment] 2021-09-18 14:35
Yes, I am saying you can close the issue.

man. 13. sep. 2021 14.40 skrev Navid ***@***.***>:

**Comment by Navid200** [comment] 2021-09-18 15:07
@classchneider I know I can close it.  But, I prefer to hear that from the person who opened the issue.

@Moshikol opened this issue and my question was for him/her.  And that's why I quoted @Moshikol .
You, @classchneider , have responded in this issue and we appreciate your contributions.  Because you have responded, you have automatically subscribed to this thread.
If you like, you can unsubscribe from this thread and  you will not get a notification every time someone makes a post.

**Comment by Navid200** [comment] 2021-09-23 14:01
@Moshikol Please respond and we can reopen if the problem has not been resolved.

**Closed by Navid200** 2021-09-23 14:01 UTC
Labels: bug, sync-local

**Comment by fredricko94** [comment] 2024-05-09 01:25
I also found same issue where it says the xDrip+ is sending broadcast data but my customized apps that were supposed to read the BG broadcast from xDrip+ couldn't find the broadcast. I tested with fake data and I confirmed my apps can already listen to the broadcast from action : "com.eveningoutpost.dexdrip.BgEstimate" correctly so I have no idea why it seems like the broadcast is not going through.
