### ISSUE TITLE
Number wall pops when notifications arrive

### ISSUE THREAD

**Issue by Hexonium** [NightscoutFoundation/xDrip#2029] opened 2022-03-02 19:43 UTC
I've tried the "Number wall on lock screen" option recently and disabled it soon after. Since then, I'm still having the number wall popping (with a black background) when the phone is locked and a new notification arrives (which wakes up the phone for a few seconds). I've updated my wallpapers (both for home and lock screens) in the android options but it didn't change anything.

My phone is a Pixel 5a with Android 12 and I'm using the latest xDrip from the Nightly update channel.

**Comment by Navid200** [comment] 2022-03-02 21:24
Did a developer ask you to open an issue?
If yes, please state who/where/when, and I will reopen.

Otherwise, please follow the request we have for everyone, unless you are a developer yourself, to open a [discussion](https://github.com/NightscoutFoundation/xDrip/discussions) first.
I am including a screenshot of the request (below), which was presented to you when you opened this.
![Screenshot 2022-03-02 162018](https://user-images.githubusercontent.com/51497406/156451818-d53c2236-93e6-47f5-9a94-3ec64c6efb39.png)

**Comment by Navid200** [comment] 2022-03-02 23:27
I can see the same thing.

**Comment by Navid200** [comment] 2022-03-02 23:29
@tolot27 This is display-related.  What label should I use?

**Comment by Navid200** [comment] 2022-03-02 23:30
@jamorham How can one remove the image so that the phone behaves as it did before?

**Comment by Navid200** [comment] 2022-03-05 02:57
Please enable the Number wall on lock screen again.
Click on Configure Number wall and delete the image.
Then, disable the number wall again.
The image should not show up any longer when screen locked.

Please explain if you still see unexpected behavior.

**Comment by Hexonium** [comment] 2022-03-05 06:11
There was no image to delete. I tried to enable/disable and it didn't change anything either.

**Comment by Navid200** [comment] 2022-03-05 14:06
I may have misunderstood the problem then.
What did you mean by the following?

> I'm still having the number wall popping

**Comment by Hexonium** [comment] 2022-03-15 01:38
Here is a gif showing what happens when I receive an email notification for instance. You can see a black screen with the number wall on it, which turns into my normal background after a few seconds.

![gif](https://user-images.githubusercontent.com/34622676/158288619-4b50628e-878d-479d-943a-f7e0f82d278b.gif)

**Comment by Navid200** [comment] 2022-03-15 02:56
> with the number wall on it

What is "number wall" in that?

The number 54?  
The arrow?
You don't mean the time or temperature, do you?
Or, do you mean the email notification itself?

**Comment by Hexonium** [comment] 2022-03-15 03:16
It's the number 54 and the arrow, the other data are not related to xdrip+...

**Comment by Navid200** [comment] 2022-03-15 03:39
@marciogranzotto Any idea what could be happening here?

**Comment by yassine-hamoudi** [comment] 2022-05-26 22:21
I disabled "Use xDrip+" under the menu Accessibility > xDrip+ and the problem seems to be solved!

![Screenshot_20220526-151933](https://user-images.githubusercontent.com/93363198/170589092-9ea13c14-0d3e-475e-90e8-c7e4104efbe7.png)

**Comment by Hexonium** [comment] 2022-05-26 22:23
I disabled "Use xDrip+" under the menu Accessibility > xDrip+ and the problem seems to be solved!
![Screenshot_20220526-151933](https://user-images.githubusercontent.com/34622676/170589329-b2baa886-fad1-405f-84f6-c49bb2d1f6dc.png)

**Comment by Navid200** [comment] 2022-05-26 22:30
@Hexonium Awesome

@jamorham Thanks a lot.  I will add to documentation in the next hour.

Closing

**Closed by Navid200** 2022-05-26 22:30 UTC
Labels: ui
