### ISSUE TITLE
Excessive bluetooth pairing requests Pixel 5, latest build

### ISSUE THREAD

**Issue by ddellspe** [NightscoutFoundation/xDrip#1520] opened 2020-11-21 20:33 UTC
Been using XDrip for a while, upgraded phone and had no issues, but with my latest transmitter (changed about 7 days ago) I've got non-stop bluetooth pairing requests (might be from an Android Security patch that was recently installed too).  

Device: G6
App Version `7154791-2020.11.15`
G6 Firmware: `2.18.2.98`
Other Version: `0.48.69`
Transmitter is a 8L transmitter
The most frequent error message I see in the logs is talking about needing "BLUETOOTH_PRIVILEGED".  I've tried disabling OB1 unbonding, but then it just never connects. I have Android 10 setting flipped on. See messages like "Pairing failed so removing pairing automation"
Also see:
```
Could not read reply to auth challenge: 
com.polidea.rxandroidble2.exceptions.BleGattCannotStartException: 
GATT exception from MAC address [REDACTED], with type 
BleGattOperation(description='CHARACTERISTIC_READ')
```

**Comment by jakobsandberg** [comment] 2020-11-21 21:01
I've experienced the same issue with my Pixel 5. It worked fine for 7 days, and then I started getting BT pairing requests every few minutes.

I wasn't able to find a proper solution; however, uninstalling xdrip and installing the latest nightly build resolved the issue. That was 6 days ago, and I'm anticipating the BT pairing requests returning in the next 24 hours or so

**Comment by ddellspe** [comment] 2020-11-21 21:08
> I've experienced the same issue with my Pixel 5. It worked fine for 7 days, and then I started getting BT pairing requests every few minutes.
> 
> I wasn't able to find a proper solution; however, uninstalling xdrip and installing the latest nightly build resolved the issue. That was 6 days ago, and I'm anticipating the BT pairing requests returning in the next 24 hours or so

Hmm, I tried going back a version and the returning to the current, but I'll try that again.  I'll keep an eye on it, but it seems most times restarting my phone TENDS to help.

**Comment by 28MAG** [comment] 2020-11-21 21:12
I also have the problem since today. I have a Samsung S9+ with a Dexcom D6 GSM. After today's Samsung update I get every 5 minutes the Bluetooth connection question. If I answer it with ok I can see the values.

**Comment by ddellspe** [comment] 2020-11-21 21:20
Man, the reinstall would be easier if it preserved my alerts in the settings, but we'll see if this works or not.  My PREVIOUS sensor was also bad after 6 days, so I thought that could be the problem.  I'll keep tracking this, but I'll be sure to bring some extra supplies for my week-long trip.

**Comment by tolot27** [comment] 2020-11-21 21:38
@ddellspe You may have not enabled/disabled the correct options. Please follow https://github.com/NightscoutFoundation/xDrip/issues/1494#issuecomment-728202441

Closing it because it's a duplicate of #1494.

**Closed by tolot27** 2020-11-21 21:38 UTC
Labels: duplicate

**Comment by ddellspe** [comment] 2020-11-21 21:44
> @ddellspe You may have not enabled/disabled the correct options. Please follow [#1494 (comment)](https://github.com/NightscoutFoundation/xDrip/issues/1494#issuecomment-728202441)
> 
> Closing it because it's a duplicate of #1494.

It might be worth noting the need for those options on the "Android 10" option.  not that it's a full solution, but it seems that this is a pretty widely known issue (at least based on issues)

**Comment by 28MAG** [comment] 2020-11-21 22:34
thx - these options have solved the issue - https://github.com/NightscoutFoundation/xDrip/issues/1494#issuecomment-728202441
