### ISSUE TITLE
Android 10 notification trend arrow points in wrong direction

### ISSUE THREAD

**Issue by jamespaulley** [NightscoutFoundation/xDrip#1242] opened 2020-02-16 11:00 UTC
The downwards trend arrow icon in the persistent notification is pointing in the wrong direction on Android 10. I'm using a Google Pixel XL.

https://photos.app.goo.gl/bPSJRJ6TntrdqGBm7

**Comment by duncanbarnes** [comment] 2020-03-21 11:28
Think this is a duplicate of my issue here:

https://github.com/NightscoutFoundation/xDrip/issues/1016

Might get a chance to delve into some of the xdrip code and have a look with all this down time although Android isn't something I develop on frequently.

**Comment by Navid200** [comment] 2021-02-27 17:56
Duplicate: https://github.com/NightscoutFoundation/xDrip/issues/1016

**Closed by Navid200** 2021-02-27 17:56 UTC
Labels: duplicate
