### ISSUE TITLE
G6 app \ xDrip app difference - need help

### ISSUE THREAD

**Issue by ben098765** [NightscoutFoundation/xDrip#1582] opened 2020-12-29 16:54 UTC
<img width="87" alt="2020-12-29 (2)" src="https://user-images.githubusercontent.com/74791337/103300333-51a61f00-4a07-11eb-8b31-03d7ccf57abc.png">
Hey, has a question, but first some background:
Got my g6 first one month ago, used it for 3 weeks.
For the past 3 weeks of those my connection was very bad, night i lose connection alot, but very much... 120 to 140 each time till wake and then again.
Also at daytime there was a huge delay between it and receiver. ( xdrip each 8 9 min, receiver each 5min), got back in connection after 5 6 min. 
Now, for the past week i used g6 app and all of it disappeared.
Connection very good ( 6 min at g6app, 5min at receiver), i get back to connection very fast, about 2min to 1min.
Night never had even once lost connection or in daytime also, only when was 6 plus meter apart (, while in xDrip after 2m lost signal).
Is there any reason why g6 app and xdrip app are so different? They both use bluetooth, and i really prefer xdrip, but the connection are very annoying... Its the only reason i use g6 app cus night is very problematic...
Mention i never use both at same time, only xdrip or only g6.

**Comment by ben098765** [comment] 2020-12-29 17:15
<img width="236" alt="2020-12-29 (5)" src="https://user-images.githubusercontent.com/74791337/103301436-1bb66a00-4a0a-11eb-88a9-75cca1306ab0.png">
<img width="252" alt="2020-12-29 (6)" src="https://user-images.githubusercontent.com/74791337/103301439-1ce79700-4a0a-11eb-8091-64a68199e162.png">

pictures for example, if it was on g6 app, i wouldnt have got those connection issues, as said, never got it at this week.
but on xdrip i keep getting it although it is 15cm from me :(

By the way, its the 23 dec version, but i keep downloading every new version, but still the same :(

**Comment by nickb24** [comment] 2020-12-30 13:44
@ben098765 How did you open a report while skipping this page?
![Screenshot_20201230-084241](https://user-images.githubusercontent.com/2193756/103355019-278e4480-4a7b-11eb-89e0-35e95fedc75c.png)

**Comment by ben098765** [comment] 2020-12-30 14:51
I dont understand? What did i skip? I opened a bug thread, cus it is a bug...
Its a suggestion? No.

If you dont wanna help and just try to make a fool out of me, you may leave the thread, please dont comment again then, other person if sees this will help if he knows how ( and he is not sarcastic)

**Comment by nickb24** [comment] 2020-12-30 15:24
> I dont understand? What did i skip? I opened a bug thread, cus it is a bug...
> Its a suggestion? No.
> 
> If you dont wanna help and just try to make a fool out of me, you may leave the thread, please dont comment again then, other person if sees this will help if he knows how ( and he is not sarcastic)

There is no reason to get hostile or defensive. I was not being sarcastic in my first post. I wanted to make sure there was not a bug in Github that would result in not showing the template when opening a new bug.

If you did indeed see the right bug template, then you must of seen this screen next after selecting 'bug report' and then completely ignored it:
![image](https://user-images.githubusercontent.com/2193756/103362964-f8320480-4a87-11eb-8fa5-3c2c8aba1616.png)

As you can see you didn't follow the template and failed to provide the information as it is presented in the template. 

Finally, your title has the words 'need help'. This to me indicates that this should not be a bug report and is probably a support request. For that the template is clear:
![image](https://user-images.githubusercontent.com/2193756/103363217-8e662a80-4a88-11eb-8c77-698e025f4042.png)

I want to help you, which is why I'm saying it's best not to open a bug report. You will get much better and quicker support on Facebook than here on Github. Countless number of people are using xDrip successfully if configured with the right settings on your device. To get that level of support you need to go to Facebook or Gitter, you won't get that on a Gitbug bug report. Bug reports are for problems with the xDrip code.

**Comment by ben098765** [comment] 2020-12-30 15:36
Oh sorry then, thought its sarcasm. 
Yea i saw it, but still i decided cus no one helps me there... I posted there, saw no one helps, then resorted to here as ladt resort, but i see here i cant get any help..
I guess ill just return to g6 app sadly...

**Comment by nickb24** [comment] 2020-12-30 16:13
@ben098765 I suggest you follow the instructions on the announcement post: https://www.facebook.com/groups/xDripG5/announcements

Then after following those instructions for setup if you are still having issues then I would post again on Facebook but this time doing the following:

1. Mention that you have followed the announcement post settings already
2.  Enable debug logs by following these instructions: https://github.com/NightscoutFoundation/xDrip/wiki/Enabling-Debugging-for-OB1-collector
3. After the logs are enabled, leave the app running for 15 minutes to collect some logs. 
4. Then take a screenshot of the error logs page of xDrip and post that on your Facebook post along with a screenshot of both status pages.

With all this information, you are far more likely to get support from people on Facebook. When people come across a post with vague information it makes it very difficult to even start to help you. Without information like which version of xDrip you are running, which phone and Android version and what settings you have configured in xDrip, people will just skip the post on Facebook and go to the next easy one to help. 

If you decide to make a new post on Facebook send me the link or post it here and I will help you if I can. I found your post on Facebook but there isn't enough information on it for me to help troubleshoot. You only posted a screenshot of the graph screen which shows missing readings but that's about it. There is no other information that can be used to troubleshoot. People on Facebook don't have the time to ask a hundred questions about each of your settings, status page and error logs. Present everything in one post and you will have a much higher chance someone will be able to help. 

@ben098765 In the meantime can you please close this issue?

**Comment by ben098765** [comment] 2020-12-30 16:43
I did it all.. Look ar my post in xdrip fb page... Fir one month i opened lot of posts and no one could help, even navid...
Yea ill close, ill just move to g6 app. Thanks anyway.

**Closed** 2020-12-30 16:43 UTC
