### ISSUE TITLE
bug: missing save button in treatment profile editor

### ISSUE THREAD

**Issue by jroth-haj** [NightscoutFoundation/xDrip#961] opened 2019-07-25 21:43 UTC
save button is only visible after splitting or deleting a block.

**Comment by LvnInLevis** [comment] 2019-11-05 22:39
Has anyone looked into this?

**Comment by Navid200** [comment] 2021-02-18 17:38
@jroth-haj Would you please update?
Is this still a problem?
Thanks

**Comment by jroth-haj** [comment] 2021-02-18 18:32
Yes.
Ist only If I Change a value and don't usw the Check Button in the Keyboard.
If I User the Check Button, it's OK.

Navid200 <notifications@github.com> schrieb am Do., 18. Feb. 2021, 18:38:

**Comment by Navid200** [comment] 2021-03-06 18:53
Great.
In that case, I hope you don't mind me closing it.
If you like to reopen, please clarify why this is required and why the work-around is unacceptable.
Thanks

**Comment by jroth-haj** [comment] 2021-03-06 18:59
It's still a bug and new users will have problems with it! This dialog GUI is unusable without sny external help.

**Comment by Navid200** [comment] 2021-03-06 19:18
@jroth-haj Would you please add a snapshot where the save option is missing?
Consider there may be a developer who can fix this.  But, if they don't understand exactly what the problem is, say they never use the treatment menu, they will never fix it.

**Comment by jroth-haj** [comment] 2021-03-06 19:29
I understand this. A a Screenshot would not be helpful. It only demonstrate a UI without the button.
It's when I minimize the Keyboard instead of using the Check Button in the Keyboard.
![Screenshot_20210306-202704](https://user-images.githubusercontent.com/1705174/110218517-7cef3380-7eba-11eb-822b-e5de9a5d1292.png)

![Screenshot_20210306-202833](https://user-images.githubusercontent.com/1705174/110218542-94c6b780-7eba-11eb-9d3b-dbb9c2f6e002.png)

**Comment by Navid200** [comment] 2021-03-06 19:32
Thanks for that.   Please let me ask a question now.
IN the second image, after you have minimized the keyboard, what will happen if you tap in the menu right beside 18 as if you wanted to make an edit?  Would that bring up the keyboard again with the checkmark available?

**Comment by jroth-haj** [comment] 2021-03-06 19:50
Using the slider or editing it again and using the blue Check Button at the Keyboard brings the save Button back.

**Comment by Navid200** [comment] 2021-06-01 02:25
@jroth-haj 
I don't see what the problem is.
After I make a change and tap on the checkmark, the save button appears.
If I don't tap on the checkmark and exit the form, I can go back and make the change again and tap on the checkmark this time.  Then, the save button appears.
I think it behaves exactly as intended.  I don't think we are going to change this unless I am misunderstanding you.

Can you please explain why you think this is a problem?
Why would a user make a change but not tap on the checkmark?
How is it going to be any better if we add a save button.  If the user is going to not tap on the checkmark, why would he/she not forget to tap on save?

**Comment by Navid200** [comment] 2021-06-01 02:26
I can make this change.  But, then, i will have to explain to the developers why this is needed.  If I cannot convince them, the change will never be adopted.  So, just because a developer makes the change does not mean that it will be released.
I need to know why this is needed so that I can be sure I can defend it when the time comes.  otherwise, it would be a waste of time.

**Comment by jroth-haj** [comment] 2021-06-01 05:05
Users are minimizing / closing the keyboard, not the input form. After that, they are missing the save button.
I expected to close the input form too, when using the checkmark button at the keyboard.

Thus behaviar ist confusing.

**Comment by Navid200** [comment] 2021-06-01 22:21
Let's say you start editing the carbs per unit and change it.  Then, you realize that you wanted to edit the insulin sensitivity and not carbs per unit.  All you have to do is to minimize the keyboard, tap beside insulin sensitivity, make your intended edit, tap on the checkmark and tap on save.  Your edits to carb per unit will automatically be cancelled.  So, minimizing the keyboard is like cancelling any edits you have made.

If we make the change you are requesting, the overall behavior will change.  Even if I make the change you are requesting, I promise you it will never be approved exactly for the reason I explained.

The only time a user gets a keyboard is if they tap beside an editable item on the page.  if you accidentally minimize the keyboard, all they need to do is to tap beside the value again, as they did originally, to reopen the keyboard.

**Comment by Navid200** [comment] 2021-06-07 11:56
A user could have several instances for different time periods as shown in the attached image.
![Screenshot_20210607-074729](https://user-images.githubusercontent.com/51497406/121011748-f66e1a80-c764-11eb-9553-106582332ef7.png)

You can think of the checkmark as the save button for the item you are editing.  The save button on the main screen saves everything you have edited.  Those have different purposes.
Minimizing a keyboard, currently, is not equivalent to having tapped on the checkmark.  It is equivalent to having changed your mind about editing the item you were on.

I am going to close this issue because I don't believe we should make a change.  
If you disagree, would you please explain?
We can continue to discuss and if needed, we can reopen.

**Closed by Navid200** 2021-06-07 11:56 UTC
