### ISSUE TITLE
"Can not display inject glucose value as time difference too great"

### ISSUE THREAD

**Issue by greekostas** [NightscoutFoundation/xDrip#1105] opened 2019-11-27 06:43 UTC
Hi all!
I have: MM1, Libre and smartwatch Optimus pro standalone.
Xdrip release 22-11-2019.
Works perfectly for 14 hours,then stops collecting. Event log says: " can not display inject glucose value as time difference too great" following two different times and dates.
Sometimes by manually restarting collector, shows values again for 10 minutes.
I have tried Xdrip release 31-1-2019 but about the same things. After 14 hours do not collecting at all.
If i uninstall Xdrip and install again everything works again for the next 14 hours.
It's a pity because the smartwatch, now, behaves awesome. 
Does anybody knows anything about that?
What is the meaning of  " time difference too great"?

**Comment by greekostas** [comment] 2019-12-01 14:15
I observed the "time difference", so i changed the watch time, 29 minutes forward, then immediately works again!!
Two days later the same again, i changed watch time, some minutes forward and works again.  After 6-7 days i got lost with time changes and i uninstall Xdrip, using my Samsung note 4 again.
Then i had a look at my Freestyle scanner time. I saw that the time in my scanner was some minutes forward and i wonder if all of these have been coused by the wrong time at the scanner.
 Does anyone knows if ,when activating a new Libre sensor with the scanner, the time of the scanner is somehow transferred to the sensor clock??

**Comment by jakobsandberg** [comment] 2019-12-05 01:01
Yes it's very likely the issue is your scanner time. Are you still having issues since that was corrected?

I'd also recommend checking out the Glimp S app to initialize your Freestyle Libre sensors: https://play.google.com/store/apps/details?id=it.ct.glicemia_starter&hl=en_US. You'll need to make sure your phone is compatabile first, but if it is, this app removes the hassle of managing two devices (phone and scanner) that can potentially diverge (e.g. system time).

**Comment by greekostas** [comment] 2019-12-05 07:01
Hi, thanks @jakobsandberg for your answer.
No i stopped using watch,i got confused with time changes. I'm thinking what to do. Before using Xdrip, i tried Glimp with my watch.Was working very stable, no time issue but no any alarms working. 
Don't know if it is an issue but my watch don't have Wear Os.
In few days i will use again watch with synchronised time with scanner and will see what will happen.

**Comment by jakobsandberg** [comment] 2019-12-05 20:17
@greekostas cool check back here if you're still having trouble after syncing the time on the scanner.

Also just to clarify my point above, the Glimp S app is separate from the Glimp app. Glimp S is simply for starting a new sensor (hence the "S"), it's not used for reading glucose values or setting alarms. I like it because I can use my Android phone to both start the sensor (via Glimp S) and also read data from the miaomiao (via xDrip), thus I don't use the Libre scanners anymore.

**Comment by greekostas** [comment] 2019-12-11 20:07
@jakobsandberg  thanks a lot. Didn't know anything about Glimp S.
Soon i will give it a try with my android watch and i will let you know 😉

**Comment by greekostas** [comment] 2020-01-26 19:05
Well, after correcting time ,everything worked great. 
But my watch was stolen... 😭
Now I am looking for a new watch and I am a bit confused..

**Comment by Navid200** [comment] 2021-02-27 01:26
I am going to close this because the unfortunate incident has moved you to look for alternatives.
We can always reopen this if needed.

**Closed by Navid200** 2021-02-27 01:26 UTC
