### ISSUE TITLE
Encountered backfill data we don't recognise: 21 1 127

### ISSUE THREAD

**Issue by rudgeman** [NightscoutFoundation/xDrip#792] opened 2019-02-22 05:25 UTC
When I went to start a new sensor today, my Sensor Status now shows Sensor Failed 6 and no matter what I reset or restart (phone, app, sensor, bluetooth) the logs continually show 

Encountered backfill data we don't recognise: 21 1 127

xDrip keeps asking me for calibrations which aren't accepter and prompt the same log error.

**Comment by rudgeman** [comment] 2019-02-22 05:27
Also occasionally flashing "Encountered Raw Data Sanity Issue 0.374"

**Comment by amspoke** [comment] 2019-06-08 16:17
I'm having a similar issue today. My new sensor started to work with an initial calibration of more than 40mg/dl. after a couple of hours started to say "Confused Calibration 1", and on the log i have tons of "Enconuntered backfill data we don't recognise: 8 5 127 2019-06-08 18:06:18". I have restarted the sensor, switched on and off, even updated xdrip, but no way. Please any help?

**Comment by amspoke** [comment] 2019-07-28 20:33
Hi,

any thing we can try? how we can clean this backfill data from the transmiter?, i have stopped the sensor, and started it again with no success, i have waited with sendor stopped for hours no way. Thanks for any help.

Best regards.

**Comment by jlecount** [comment] 2019-08-26 01:13
I just got this now also on a galaxy s8 ruining android Pie with dexcom g6.  Anything I can do?

**Comment by malcolmmackay** [comment] 2019-09-11 22:30
I am getting a very similar problem with a brand new transmitter. Firmware version 2.18.2.88 serial starting 8G. I am running the latest nightly of xDrip 09.10 and the native G6 collector.

I am getting some 'could not read reply to Auth challenge' and 'could not read after authrequesttx'. Android version 9. No problems before change of transmitter today.

**Comment by jlecount** [comment] 2019-09-11 22:36
When I got this issue, I just left it alone and eventually it ended up calibrating OK.  I don't think it was anything I did -- it went away on its own, apparently.

**Comment by malcolmmackay** [comment] 2019-09-11 22:44
Thanks for letting me know this jlecount. I will see if it sorts itself out overnight.

**Comment by jlecount** [comment] 2019-09-11 22:52
Sure.  I'd be curious to hear back from you if that's your experience too so we know I wasn't just an anomaly etc...Or maybe I did something that helped -- if so I don't recall anything other than ignoring it overnight.

**Comment by rudgeman** [comment] 2019-09-12 02:57
Mine ended up doing the same, fixed itself after a while.

**Comment by fooelisa** [comment] 2019-11-21 21:35
I seem to be having a similar problem with a 8Gxxx G6 transmitter, anyone ended up finding a way to fix this? Just opened a new issue on this here: https://github.com/NightscoutFoundation/xDrip/issues/1100

**Comment by malcolmmackay** [comment] 2019-11-21 22:39
In my case, the cause of the error was mechanical - when peeling the sensor off after 24 hours, I found that no sensing element was present. It had not been introduced under the skin! Instead, it was still stuck in the white inserter contraption. 

I have not encountered this problem with the dexcom before or since. I left it 24 hours before replacing the sensor because I assumed the insertion had worked and suspected I'd have an experience similar to others on this thread.

**Comment by fooelisa** [comment] 2019-11-21 23:30
Interesting, thanks for the hint! I'm about to swap out the sensor too, it's been over 24hrs by now as well. Thanks again!

**Comment by fooelisa** [comment] 2019-11-22 10:35
A fresh new sensor did the trick! I was a little hesitant to swap it out right away, before ruling out other issues, but about two days in we gave up hoping it would calibrate by itself eventually. It had a sensing element and some dried blood around it, so I think the insertion went alright. Not sure what could have caused for the sensor to be bad. We did go though multiple start/stop cycles on various phones, tried a different location the second time around, or maybe the sensor itself was faulty already 🤷‍♀

**Comment by malcolmmackay** [comment] 2019-11-22 18:42
Glad to see you are back up and running.

**Comment by Navid200** [comment] 2021-02-07 20:35
@rudgeman Since it seems your problem was resolved, would you please close the issue?
Thanks

**Comment by Navid200** [comment] 2021-02-18 01:34
Closing due to inactivity

**Closed by Navid200** 2021-02-18 01:34 UTC
