### ISSUE TITLE
Miao Miao Battery Always At 100% 

### ISSUE THREAD

**Issue by UberQueiroz** [NightscoutFoundation/xDrip#1391] opened 2020-07-28 00:00 UTC
Hi!

My bridge's battery on xDrip are always at 100% since last time I've installed a sensor. I talk to Miao Miao costumer service and they said it's must be a software issue.

My xDrip is up-to-date (update of July 25th).

 Can anyone help me?

Thanks in advance!

![Screenshot_20200727-205939_xDrip+.jpg](https://user-images.githubusercontent.com/66580535/88603724-195f7680-d04c-11ea-868e-bfc874f3e1df.jpg)

**Comment by edwin-hendriks** [comment] 2020-09-02 09:00
I have the same issue. I am pretty sure it is caused by xDrip+. I think that because other (less good) apps do not have this issue. It is also clear that xDrip+ does receive this info correctly because xDrip+ send all sort of info to the cloud, which in my case is my personal nightscout heroku app. There I see the correct battery percentage (see screencap below indicating 12% while xDrip+ always shows 100%):

![image](https://user-images.githubusercontent.com/13136750/91961384-65689f80-ed0b-11ea-8837-0474519a2468.png)

**Comment by edwin-hendriks** [comment] 2020-09-02 09:04
> > Hi!
> > My bridge's battery on xDrip are always at 100% since last time I've installed a sensor. I talk to Miao Miao costumer service and they said it's must be a software issue.
> > My xDrip is up-to-date (update of July 25th).
> > Can anyone help me?
> > Thanks in advance!
> > ![Screenshot_20200727-205939_xDrip+.jpg](https://user-images.githubusercontent.com/66580535/88603724-195f7680-d04c-11ea-868e-bfc874f3e1df.jpg)
> 
> Yo les diría a los de MiaoMiao que reemplazaran el dispositivo.

Which translates to "I would tell MiaoMiao to replace the device". However, you should NOT do that. It is pretty clear that it is an issue in xDrip+. See my other comment which explains. Sadly I do not have a solution, so I do hope that the great developers of xDrip+ can solve it.

**Comment by Navid200** [comment] 2021-07-08 04:01
@tzachi-dar Is this behavior expected, or not?
Is there anything we can do to xDrip to address this?

**Comment by tolot27** [comment] 2021-07-08 07:45
It should be easy to fix, I believe.

**Comment by tzachi-dar** [comment] 2021-08-08 07:38
I don't believe there is such a problem in xDrip.
This works well on my system (and on many others).
If anyone is ready to post here the message saying:
״We have all the data that we need ..." I can give it a second look.

**Comment by tzachi-dar** [comment] 2021-08-10 16:36
Closing the issue.
If someone can supply a debug message printing, please re-open the issue.

**Comment by Navid200** [comment] 2021-08-10 16:43
It's still open

**Closed** 2021-08-10 16:43 UTC
Labels: bug, ui, device-miaomiao
