### ISSUE TITLE
FR: DesertSync with 2 Masters/data sources

### ISSUE THREAD

**Issue by tremor** [NightscoutFoundation/xDrip#462] opened 2018-06-01 07:49 UTC
I want to use 2 devices to collect data (for example a android OS bases Smartwatch and a normal smartphone) to collect the data via NFC and/or MiaoMiao. Normally the smartwatch should collect the data and send it to Nightscout and to all xdrip Followers (Tablet and Smartphone). If the watch out of power the smartphone should take over and gather the data from the MiaoMiao and should now be the xDrip Master and distribute the data.

**Comment by tremor** [comment] 2018-06-01 08:54
The Followers follow only one of the two - it look pretty random - but the major problem is that one of the one of the masters doesn't get any data. It tries to connect to the miaomiao via bluetooth but the miaomiao only allows one peer at a time. If I turn off the active master the other becomes active after some time, but before that it only shows old data.

**Comment by tzachi-dar** [comment] 2018-06-01 15:55
We probably need to revive the tzachi-xdrip-uploader branch to get it done right. Then only one master and all others will collect the data. This will also allow calibrations to work correctly.

**Comment by drincle** [comment] 2020-06-09 22:22
Is there a way to setup multiple devices as a master, yet they'd all share the same treatment information simultaneously? Meaning, if my daughter enters carbs or boluses on her phone, that it would also register on my phone, and my wife's phone, and vice versa? The issue is, if my daughter doesn't have her phone on her, then mine or my wife's will need to be a master in order to pickup the G6 signal. But if we're all masters, then when entering treatments on one master, it will not sync with the other handsets unless they're setup as a follower. Additionally, if my phone is setup as an xdrip follower, then when my daughter doesn't have her phone reading and relaying data, my phone won't pickup her G6 signal because my data is set to come from her phone, not mine directly.

**Comment by Navid200** [comment] 2021-08-07 02:01
Can I close this issue?

**Comment by tremor** [comment] 2021-08-09 05:53
I'll think this is still a feature request....

**Comment by tolot27** [comment] 2021-08-09 06:16
This use case could be set up using NightScout as soon as #1403 is finished and merged.

**Comment by Navid200** [comment] 2021-08-11 13:15
@tremor 
Have you tried setting up the followers to use Nightscout follow instead of xDrip Sync follow?
Or, is there a reason you prefer xDrip sync?

**Comment by tremor** [comment] 2021-08-20 05:03
The xDrip sync works without Internet connection, when I'm on the road and all of my devices are connected to a mobile hotspot (without internet uplink).

**Comment by Navid200** [comment] 2021-09-11 14:59
@tremor What do you mean "xDrip sync works without Internet connection"?
xDrip sync needs Google messaging.  How can it work without internet connection?
You may be talking about Desert Sync.  

If you are asking for some feature to be added to Desert Synch, would you please change the title to reflect that?
We can then change this to be a feature request.

**Comment by Navid200** [comment] 2024-03-21 22:08
As of a few Nightly releases ago, you can upload treatments to Nightscout from both master and follower and both will show them all.

As far as having two masters, this seems to be possibly a limitation by the device.  You cannot have more than one device collecting from a Dexcom transmitter both on the mobile slot.  This is not an xDrip issue.  Now, that was only an example.
I understand the request is about Libre.   
If that is the request, the title should be changed to reflect that.  It doesn't seem to be related to Nightsocut.

I am closing this because it is not clear what is being requested or what is missing.  We can always reopen if needed.

**Closed by Navid200** 2024-03-21 22:08 UTC
Labels: enhancement, sync
