### ISSUE TITLE
Problem Parsing Package on any attempted update

### ISSUE THREAD

**Issue by JonathanM32** [NightscoutFoundation/xDrip#1892] opened 2021-12-14 04:54 UTC
Every time I go to update xDrip (I'm running version 17cbcf0-2021.03.08) I get a pop up saying "There was a problem parsing the package." Running on **Android 12 December update on a Pixel 4 XL.** This issue has been discussed [here](https://github.com/Navid200/xDrip/discussions/140)

### Screenshots
<img src="https://user-images.githubusercontent.com/5178078/145513092-f96d2d4d-177d-4025-b67f-ce4733c9814c.png" alt="drawing" width="250"/>

**Comment by tolot27** [comment] 2021-12-14 05:39
On wich update channel are you?

**Comment by JonathanM32** [comment] 2021-12-14 18:24
Oddly though nothing has changed, the update worked I think? I'm on the alpha channel.
![](https://lh3.googleusercontent.com/2svxon8hoNVRWaWm3Lk-t88BWolCVYMjRNgd-X6VY5ChB6avYuiYY6F-V0C7H80ubphTREFuk0l1yXANLvSu4Q2982w7gadX74ap3OmSlOaXEZQLZMJvREU_HUFEYOjPJa1tsKC8nznchlnTDH-4_boXtEynJRCtMJmcB4_t8GNkbDFBMWgdDfmImKsze5r5SbTD1iWXD9sjORd6wZgPo7XAUrzsrFLhPQfjCdXKNBvzrBSq-q8A2PfZsNCmrnCYag1f0l1k_TMiDutUbtbfZ87ywmPtsfgyNwPOYeJZygQ6WdUJ8FqfMf0Gf60PVxWQQ9Qo5xDnSUdaECtEGZhFSm5g218b8GiERA7x1V5WN-ZB4ZzdccqIgI7qFiL3w0sp8wfFyPcdK1L8ry4sYTxnu71ybMilS450xzO8qIwjBfQAesBxsIDVkzPzIs8D1By35wSfnOjCAXn3Nd6IV3Zzz6E6BQpGiRXd6zDZrAbzppQu-qJVvyaq_PDp7g2cSKkARKT9Bd6nyLr1_fO-Ei9krQvZ6Q2S6pGCnOWSDXBIFRoU1vNz1ijWCAb59u2P4IETjegh6a2mGtjpqy6Nx8m4WMCR2Vwcp0PkWehvH_GtfZ9BCxXRR1OWAXGBdqnJt3XUK61OQungx1zUOAAqtbtojr4QdfGMuk_XgG9SIt-v2wnGrjTD6BbnhzS0_lh8DPaONFTb-Cq_PPpNYEb976o=w1357-h929-no?authuser=0)

**Comment by tolot27** [comment] 2021-12-14 18:48
> Oddly though nothing has changed, the update worked I think? I'm on the alpha channel.

Maybe, it was just a connection problem. Please can you have a look in the log history and search for entries at the time the error occured?

**Comment by Navid200** [comment] 2021-12-14 19:49
@JonathanM32   Would you please provide xDrip logs before they are erased?

**Comment by JonathanM32** [comment] 2021-12-14 20:47
> > Oddly though nothing has changed, the update worked I think? I'm on the alpha channel.
> 
> Maybe, it was just a connection problem. Please can you have a look in the log history and search for entries at the time the error occured?

I doubt it's a connection issue because it happened on many different occasions across multiple connections scenarios. Not 100% sure what to make of it

**Comment by JonathanM32** [comment] 2021-12-14 20:48
> @JonathanM32   Would you please provide xDrip logs before they are erased?

Is there something specific from the logs that you want? I'm not seeing anything too specific that looks helpful. The issue is prompted by the system not xdrip

**Comment by Navid200** [comment] 2021-12-14 20:50
Were you able to just install over?  Or, did you need to uninstall first?

**Comment by tolot27** [comment] 2021-12-14 21:47
> The issue is prompted by the system not xdrip

How do you know it is from the system (do you mean Android OS) and not from xDrip?

**Comment by JonathanM32** [comment] 2021-12-14 21:50
> Were you able to just install over?  Or, did you need to uninstall first?

I was able to install it over. The difference was that I installed it from the files app rather than directly through xdrip

**Comment by JonathanM32** [comment] 2021-12-14 21:51
> > The issue is prompted by the system not xdrip
> 
> How do you know it is from the system (do you mean Android OS) and not from xDrip?

> From what I can tell the problem parsing package is an error that the Android package manager can throw if it sees something it doesn't like. I don't believe that is an extra specific issue

**Comment by tolot27** [comment] 2021-12-14 21:52
> > The issue is prompted by the system not xdrip
> 
> How do you know it is from the system (do you mean Android OS) and not from xDrip?

Ah got it, It is raised during installation of the app. Hence, it is an OS issue and not a download issue. There are several posts about this like [How to Fix There Was A Problem Parsing the Package](https://www.fonedog.com/android-data-backup-restore/there-is-a-problem-parsing-the-package.html).

**Comment by tolot27** [comment] 2021-12-14 21:54
I'm about closing this issue because it is not reproducible anymore. Please reopen the issue, if it occurs again.

**Closed by tolot27** 2021-12-14 21:54 UTC
Labels: question
