### ISSUE TITLE
xDrip and display currently used basal insulin and graph vizualise 

### ISSUE THREAD

**Issue by sebastiangrugel** [NightscoutFoundation/xDrip#1704] opened 2021-04-21 21:23 UTC
Hello.

- I would like display on xDrip screen information about currently basal insulin which is delivered by mu pump.(that can be in additional line with information from pump. (all data are in Nightscout but good to sync this with that source or maybe directly from xDrip master). Details on screnshoots. 
 
- additional graph with information about basal insulin during a selected period of time could be good idea. I saw something that in xDrip but this is only working when somebody is using AAPS. How this looks like with xDrip when AAPS is configured is visible in screnshoot. I have Medtronic Minimed 640G with Uploader to NS and xDrip (master) and information about basal insulin are not visible. Above graph is not possible to configure if somebody don't use AAPS

### Describe alternatives you've considered
I installed NSClient on my mobile-phone and enabled some local data on xDrip and NSClient but still this is not working.

![image](https://user-images.githubusercontent.com/19813648/115621908-6e889a00-a2f7-11eb-89cc-ac340d1b200a.png)

**Comment by tolot27** [comment] 2022-01-06 23:46
Closing as it is a duplicate of #895. If not, please reopen it and clearly explain why not.

**Closed by tolot27** 2022-01-06 23:46 UTC
Labels: ui, insulin-basal
