### ISSUE TITLE
not possible to scroll in preferences page or open subpreferences

### ISSUE THREAD

**Issue by AphgaDesign** [NightscoutFoundation/xDrip#1791] opened 2021-07-27 21:45 UTC
### Parameters window always get back or up on Android 12
With Android 12, when you want to navigate or change some preferences, the windows always return up when you try to scroll down and if you enter another preference section, it returns to first preference page.

### Your environment
- What version of xDrip: 05352f5-2021.07.17, Code 2107170910
- What type of hardware: Pixel 4a

### Expected behavior
Can navigate in preferences!

**Comment by Navid200** [comment] 2021-07-27 22:50
Please don't open issues for Android 12 yet as it is still beta.
If you are kind enough that you like to share your experience with us, please use the Gitter room:
https://gitter.im/jamorham/xDrip-plus

**Comment by tolot27** [comment] 2021-07-28 10:46
What do you mean with parameters? Do you mean preference/settings?

**Comment by AphgaDesign** [comment] 2021-07-28 11:15
Yes

**Comment by tolot27** [comment] 2021-07-28 11:42
@AphgaDesign Please can you confirm the updated title and description?

**Comment by AphgaDesign** [comment] 2021-07-28 12:23
Title is fine.

Nothing about that in log.

**Comment by btdkomplex** [comment] 2021-09-14 06:03
I have found this happens if the lockscreen wallpaper feature is turned on when running Android 12 beta.

**Comment by Navid200** [comment] 2021-09-14 12:38
@btdkomplex Are you saying if you disable the lockscreen wallpaper feature, you don't experience the problem?

**Comment by btdkomplex** [comment] 2021-09-14 13:06
Yes. You have to be quick to get to the option to disable it though.
It's a real shame though as I really relied on the lockscreen wallpaper. Hopefully it can be fixed when Android 12 is released proper.

**Comment by Navid200** [comment] 2021-09-14 13:11
@btdkomplex Is this the option you are talking about?
![Screenshot_20210914-090821](https://user-images.githubusercontent.com/51497406/133263584-b4756afb-11ee-42dd-b46b-1b4927685c3e.png)

**Comment by btdkomplex** [comment] 2021-09-14 22:25
Yes

**Comment by Navid200** [comment] 2021-09-15 01:49
I have installed the latest version of xDrip in a virtual device on Android 12.  
I don't see the problem.

I navigated to Settings -> xDrip+ Display Settings -> xDrip Color Settings
I changed the in-range color.
Then, I navigates back to the main screen.
There was never an issue with accessing any of the pages or changing the setting.

Is there any particular setting that you had this problem with?

It is also possible that the problem is not present in the virtual device.
But, would you please tell me exactly what settings page presents the issue?

**Comment by Navid200** [comment] 2021-09-28 22:12
@AphgaDesign Are you still experiencing problems accessing settings?

**Comment by AphgaDesign** [comment] 2021-09-28 22:46
No, all is ok now, I don't know why

**Comment by Navid200** [comment] 2021-09-28 22:52
Great.  So, I close the issue then.
Thanks

**Closed by Navid200** 2021-09-28 22:52 UTC
Labels: bug, settings, android12+
