### ISSUE TITLE
Xdrip+ 8K transmitter G6 sensor android 10 disconnecting

### ISSUE THREAD

**Issue by violapetermd** [NightscoutFoundation/xDrip#1451] opened 2020-09-26 12:08 UTC
Hello everyone,
would You be so kind to help me?
My son's configuration is as follows:

Android 10 OS on Samsung Galaxy A41
8K transmitter
G6 sensor (new, no restarts, 2. day)

The problem is, the transmitter often disconnects from the mobile. Made a small [interactive plot](https://neuromedical.pythonanywhere.com/xdrip/reading/) from the database (BgReadings and UserErrors). Right now the transmitter is connected to a Dexcom compatible device (Official Dexcom app from Play Store) <del>without a single disconnection</del>.

Thank You,
Peter

Edited 09/28/2020: The compatible device is dropping the signal too. What works: The transmitter remains paired -> Unpair the transmitter -> Restart the Dexcom G6 application.

**Comment by tolot27** [comment] 2020-09-29 05:27
What do you mean by "Dexcom compatible device"? Your Galaxy A41? You may ask the Dexcom support if does not work with the Dexcom app. Maybe your transmitter is a faulty one.

**Comment by violapetermd** [comment] 2020-09-29 06:04
Thank You for Your reply. 

I mean a Galaxy J5 (SM-J530, which is listed as compatible) with the official Dexcom application. I am wondering why the Signal Loss alerts are not stored in the database.

Best regards, VP

**Comment by tolot27** [comment] 2020-11-06 19:51
I still do not know which errors are ment with "UserErrors". Please can you post such errors? And why do you assume that the transmitter disconnects from the mobile while the compatible device is dropping the signal? That are different communication directions.
Maybe, you have a faulty transmitter?

**Comment by tolot27** [comment] 2020-12-15 22:53
@violapetermd If you still have trouble, please ask for support at https://www.facebook.com/groups/xDripG5 or https://gitter.im/jamorham/xDrip-plus.

If it is solved, please close this issue.

**Comment by violapetermd** [comment] 2020-12-17 15:45
@tolot If I am not mistaken the UserErrors is one of XDrip+'s database tables - the black trace on the plot (x-axis: timestamp, y-axis: severity, on mosueover shows the error message). After lot of pain (technical, of course) we switched from G6 to the Libre2, works fine (missing the not working mongoDB cloud upload (Atlas), though). Thank You for the excellent piece of applicatio! Best regards,

**Comment by jamorham** [comment] 2021-01-27 12:30
Can you try the latest nightly an enable both the `Minimize scanning` and `Avoid scanning` options. thanks

**Comment by Navid200** [comment] 2021-02-06 00:20
@violapetermd Hi,
Your last message suggests that you are not using G6 any longer and are now using Libre.  Is that correct?
In that case, you don't have the problem you opened this issue for, right?
That doesn't, by itself, mean that there is no issue.  However, there is no way for anyone to work with you to figure out what the problem is.

If you are not experiencing this problem any more, would you please close this issue?

**Comment by Navid200** [comment] 2021-02-24 15:41
If you have any problems using a G6 with xDrip, please post either in the facebook group or in the Gitter room.  Feel free to tag me.  I will work with you to resolve the issue.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Closed by Navid200** 2021-02-24 15:41 UTC
Labels: bluetooth, device-dexcom, question
