### ISSUE TITLE
xDrip+ refreshrate

### ISSUE THREAD

**Issue by markxoe** [NightscoutFoundation/xDrip#1302] opened 2020-04-14 11:39 UTC
Hello,

i am using xDrip with Nightscout, but my Sensor sends BG-data every 5 minutes, but xDrip refreshes every 10 minutes...
Is there any way to change this?
I looked into the code, but didn't find any way to change this...

Thanks in advance

**Comment by markxoe** [comment] 2020-04-14 19:13
After some reverse engineering and testing, [`final long grace = Constants.SECOND_IN_MS * 10;`](https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/cgm/nsfollow/NightscoutFollowService.java#L131) is (in my case) too short, because my uploader is sending the data after about 20-30 seconds after that...
A fix would be to let this value be changed by the User in the UI...
Could some Dev integrate this please?

Thanks

**Comment by akadismas** [comment] 2020-04-16 13:55
I also found that time delay on xDrip when refreshing BG-data may be sensible to difference between system time on Nightscout and on the phone with xDrip+

**Comment by markxoe** [comment] 2020-04-16 13:58
> 
> 
> I also found that time delay on xDrip when refreshing BG-data may be sensible to difference between system time on Nightscout and on the phone with xDrip+

I fixed it myself ( adjustable ): https://github.com/NightscoutFoundation/xDrip/pull/1307
But i have to wait, until someone looks at it

**Comment by akadismas** [comment] 2020-04-16 14:27
> I fixed it myself ( adjustable ): #1307
> But i have to wait, until someone looks at it

Suppose, it should be useful improvement, because eliminating system time gap won't solve the problem with uploader delay.

**Comment by markxoe** [comment] 2020-04-16 14:33
> 
> 
> > I fixed it myself ( adjustable ): #1307
> > But i have to wait, until someone looks at it
> 
> Suppose, it should be useful improvement, because eliminating system time gap won't solve the problem with uploader delay.

In my case it helps tho....
My Uploader uploads the data to nightscout, but xdrip+ syncs before that...

**Comment by markxoe** [comment] 2020-08-23 17:15
Soo this won't be fixed?
I really don't like an app that doesn't refreshes before the value is uploaded

**Comment by tolot27** [comment] 2020-12-21 12:45
Looks like a duplicate of #929.

**Comment by Navid200** [comment] 2021-03-15 18:05
Closing because it is very similar to #929.  Please add any comments you may have to that issue.
Thanks

**Closed by Navid200** 2021-03-15 18:05 UTC
Labels: duplicate, enhancement, sync-nightscout

**Comment by Navid200** [comment] 2023-11-21 12:33
The latest Nightly release (https://github.com/NightscoutFoundation/xDrip/releases/tag/2023.11.21) has a new setting when you select Nightscout follower as the data source.  It lets you delay when the follower reads from Nightscout.
Please try it out to see if it addresses this.
