### ISSUE TITLE
Displayed and uploaded trend arror differ

### ISSUE THREAD

**Issue by quizzmaster** [NightscoutFoundation/xDrip#681] opened 2018-11-12 15:49 UTC
The trend arrow which gets uploaded to NS isn't the same as displayed. Sometimes the uploaded is the same as my G6, sometimes the shown is the same. Shouldn't both trend arrows match and with native mode be the same as the Dexcom receiver shows?

**Comment by quizzmaster** [comment] 2019-04-24 22:55
I still experience this issue and so do others

**Comment by quizzmaster** [comment] 2019-04-24 23:27
In this example all the arrows should show the same direction (45down), but xDrip+ forwards a steady trend.

![photo5335033600443263858](https://user-images.githubusercontent.com/2745710/56700138-e74cbf80-66f8-11e9-8996-ee00b26fab82.jpg)

![photo5334657163739638489](https://user-images.githubusercontent.com/2745710/56700129-e156de80-66f8-11e9-90c9-2c7df8b42c0d.jpg)

![photo5335033600443263859](https://user-images.githubusercontent.com/2745710/56700142-ee73cd80-66f8-11e9-8746-a766da9a4248.jpg)

**Comment by quizzmaster** [comment] 2019-09-21 14:56
@jamorham 10 months without any comment? Is this behaviour intended or a bug?

**Comment by quizzmaster** [comment] 2019-10-06 22:41
Also the uploaded delta is different to the real delta.
e.g. xDrip, AAPS and NS show delta -3, but the SGV entry taken from the API says delta -5

**Comment by Cagier** [comment] 2019-12-04 23:21
I am experiencing the same issue I think.  I think the problem is that although the xDrip is working out what the arrow should be, it is in fact sending the arrow that the G6 has derived instead. I've deduced this from the fact that we have a separate G6 receiver and the arrow direction on the NightScout always seem to match the Dexcom receiver and these are often different to the xDrip app.

This seems to related to the G6 but may relate to G5 in Native Mode also?

I suggest that the xDrip app should transmit it's own arrow to remote systems rather than blindly sending on the arrow direction that Dexcom has worked out. It would be more consistent and less confusing (and more accurate!)

I think this may be related to https://github.com/NightscoutFoundation/xDrip/issues/800

**Comment by Navid200** [comment] 2021-02-10 13:50
@quizzmaster If you look at your post of April 24 with the 3 images, you can see that all three are showing the same -7mg/dL.  So, the slope is valid regardless of the app.  
The arrow is a graphical representation of the slope.  
This can be considered a bug for the other 2 apps, no?

If you disagree, would you please respond?
If you agree, would you please close the issue?

**Comment by Navid200** [comment] 2021-02-10 13:54
OK, as soon as I typed that, I saw that it may be taken the wrong way.

If you want to represent a slop graphically, you will have to come up with a resolution because you cannot have an infinite number of different arrows.  So, you will have to associate a range of slopes to each one of your arrows.
There seems to be a difference between how each app has grouped the different ranges of slopes.  There is not necessarily anything wrong.

**Comment by quizzmaster** [comment] 2021-02-17 20:31
@Navid200 The slope is correct, yes. Also that there are only a few different arrows (flat, 45 degrees, up, double up) is not the point.

xDrip uploads the BG values with a device name, the delta, the arrow and other informations, e.g.:
```
{"_id":"602d79d301181286acc396af","device":"xDrip-DexcomG5 G5 Native","date":1613593041389,"dateString":"2021-02-17T20:17:21.389Z","sgv":226,"delta":8,"direction":"FortyFiveUp","type":"sgv","filtered":0,"unfiltered":0,"rssi":100,"noise":1,"sysTime":"2021-02-17T20:17:21.389Z","utcOffset":60,"mills":1613593041389}
```
Also sometimes the uploaded delta isn't correct and doesn't represent the real delta to the previous uploaded value.

**Comment by Navid200** [comment] 2021-02-27 14:27
Would you mind adding your voice to the issue that had been opened before this one?
https://github.com/NightscoutFoundation/xDrip/issues/414
I am identifying duplicate or similar issues and asking people to consolidate.  
Thanks

**Closed** 2021-08-06 13:58 UTC
Labels: duplicate
