### ISSUE TITLE
Miamiao 2 with libre 1 - Calibration data missing

### ISSUE THREAD

**Issue by TheLordBaski** [NightscoutFoundation/xDrip#1591] opened 2021-01-05 19:36 UTC
Hello,

I am having issue with the xDrip+.

![Screenshot_20210105_203000_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/3714855/103690375-f048f780-4f94-11eb-9c23-29372c9733ea.jpg)

Android version: 10
Phone: Huawei P30 Pro
xDrip+: e14bae1-2020.07.13
Bt device: maiomiao2-958c

Issue occurred in 2nd day od senzor age.  I tried to recalibrate, didnt work so I forced remove all calibrations and entered 2 new calibration. After that issue started to occur, didnt get any data shown in app after that.
I checked calibration and there was no calibration, even when I added 2 calibrations there after calibration reset. They somehow got missing. I uploaded log via app. 

After second force recalibration I was able to get it working once again. 

So the issue is with the missing calibration data. 

If you need more info, I can provide it.

**Comment by tolot27** [comment] 2021-01-05 22:14
This issue looks like a duplicate of #1455. Please can you verify this and continue there after closing this issue?

**Comment by TheLordBaski** [comment] 2021-01-06 13:08
I checked that issue. I am not sure if the error is caused by missing calibration data or there is another issue. This issue is about forced recalibration and missing calibration data after I added 2 calibrations. (My error was caused because there was no calibration data, even when I added 2 calibrations.) If it's the same we can close this.

**Comment by Navid200** [comment] 2021-07-08 04:25
@TheLordBaski 
Are you still experiencing the problem?

Have you asked other users and developers?
You can do that by posting here:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by Navid200** [comment] 2021-08-06 12:24
Closing due to inactivity

**Closed by Navid200** 2021-08-06 12:24 UTC
Labels: duplicate
