### ISSUE TITLE
Bug report: Miao2 & Miband bluetooth conection problem

### ISSUE THREAD

**Issue by Nyan-Korea** [NightscoutFoundation/xDrip#1446] opened 2020-09-23 04:07 UTC
Xdrip loses bluetooth Miao Miao 2 or Mi band5 usally one time in two days.
And it never connect it again by it self.
I have to connect it again in 'Bluetooth Scan' menu.

-> I want Xdrip try to connect o Miao Miao 2 or Mi band automatically when it disconnects.

Thank you

**Comment by tolot27** [comment] 2020-09-23 05:56
@Nyan-Korea Which version of xDrip do you use?

This bug is maybe related to #1442.

**Comment by Nyan-Korea** [comment] 2020-09-23 06:06
The name of the apk file when I downloaded it is

'xdrip_miband_0.3.2.apk'

Thank you

**Comment by bigdigital** [comment] 2020-09-23 06:35
Hi. Could you please check if Miao Miao loses Bluetooth connection if you would use a latest nightly build so we can identify if this problem were caused by modifications in my 'xdrip_miband' apk?

**Comment by Nyan-Korea** [comment] 2020-09-23 06:49
Which is lastest version? can you give me the lastest version link?

**Comment by bigdigital** [comment] 2020-09-23 07:02
https://github.com/NightscoutFoundation/xDrip/releases/tag/2020.09.04

**Comment by Nyan-Korea** [comment] 2020-09-23 07:06
Mine is 09/09/2020 (0.3.2) releases. It is the lastest.

Am I confusing something..?

**Comment by bigdigital** [comment] 2020-09-23 07:14
Yes, this is the latest **modified** xdrip, which support miband5. But to identify the source of the issue, i ask you to install official xdrip (without miband5 support) and test if Miao Miao 2  would lose Bluetooth connections. In any case, before you switched xdrip, please send me debug logs like described [here ](https://bigdigital.home.blog/2020/08/25/new-xdrip-now-supports-miband-5/#debug)

**Comment by Nyan-Korea** [comment] 2020-09-23 07:15
Oh I see. I will.
Thank you

**Comment by Nyan-Korea** [comment] 2020-09-23 07:20
Just now I tried to install it, and I saw failed to install mesaage.
But it is hard to delete now version and install.

Because I have to show my data to doctor..

Is there a way to do test on this version(0.3.2)?

**Comment by Otto75so3e** [comment] 2020-09-23 08:11
1. Use the menu in the top right corner "Import/Export features" then "Export Database" and "Load/ Save Settings on sdcard".
2. Check if the files are present (internal storage/xDrip/exportCSV202009xx-xxxxx.zip & Downloads/com.eveningoutpost.dexdrip_preferences.xml)
3. After uninstall and installation import the files back.

**Comment by tolot27** [comment] 2020-11-04 06:15
@Nyan-Korea Could you solve the connection problem? If yes, please close this issue.

**Comment by tolot27** [comment] 2021-03-27 16:26
@Nyan-Korea Please try the latest version from https://bigdigital.home.blog/2020/08/25/new-xdrip-now-supports-miband-5.

Closing due to inactivity.

**Closed by tolot27** 2021-03-27 16:26 UTC
Labels: bluetooth, bug, device-miband
