### ISSUE TITLE
Xdrip+, Dexcom G6, Android Pie (9.0) Successful Connection Settings 

### ISSUE THREAD

**Issue by opasha** [NightscoutFoundation/xDrip#891] opened 2019-05-25 19:04 UTC
For anyone having issues with your connection to any Android Pie device (I have a Xiaomi Mi Max 3 with stock android AOSIP 9.0 ROM), use my following settings. I'm on the latest beta of xdrip+: attachment filenamexDrip-plus-20190110-14fecb8.apk. 

I've  come from libre 10 day sensors with miaomiao Bluetooth transmitter to dexcom G6 since the 14 day libres are encrypted. Native mode does not work period. Let @jamorham figure it out, but post all your concerns here. I'm tired of all the random threads where important posts like this get lost, so I'm trying to help anyone in a similar situation. Native mode G6 only works if you have fall back to xdrip on, but it auto enables itself and turns off fallback to xdrip, so it's a moot point. OB1 collector being off is the way to go. I will update my post to help you all restart your collectors - I have found the right way to do this even with pre-emptive restart being off due to OB1 collector being off.

The main G5 re-connect settings are necessary because sometimes the sensor refreshes after 10 minutes instead of 5 minutes, which you can clearly see in my second post with the difference in points. 

<a href="https://postimg.cc/hXKC0Qc2" target="_blank"><img src="https://i.postimg.cc/hXKC0Qc2/Screenshot-x-Drip-20190525-144621-01.png" alt="Screenshot-x-Drip-20190525-144621-01"/></a><br/><br/>
<a href="https://postimg.cc/QFSfYNMh" target="_blank"><img src="https://i.postimg.cc/QFSfYNMh/Screenshot-x-Drip-20190525-144657-01.png" alt="Screenshot-x-Drip-20190525-144657-01"/></a><br/><br/>
<a href='https://postimg.cc/q663N9Zx' target='_blank'><img src='https://i.postimg.cc/q663N9Zx/Screenshot-x-Drip-20190602-140126.png' border='0' alt='Screenshot-x-Drip-20190602-140126'/></a>
<a href="https://postimg.cc/47Hw3zQx" target="_blank"><img src="https://i.postimg.cc/47Hw3zQx/Screenshot-x-Drip-20190525-144724-01.png" alt="Screenshot-x-Drip-20190525-144724-01"/></a><br/><br/>
<a href="https://postimg.cc/Fktpk7Tg" target="_blank"><img src="https://i.postimg.cc/Fktpk7Tg/Screenshot-x-Drip-20190525-144735-01.png" alt="Screenshot-x-Drip-20190525-144735-01"/></a><br/><br/>

**Comment by opasha** [comment] 2019-05-25 19:11
Here's my proof that it works since using xdrip+ to start my dexcom g6 sensor with 2 hour warm up and calibration on Monday May 25, 2019.

<a href='https://postimg.cc/rdrQV1JF' target='_blank'><img src='https://i.postimg.cc/rdrQV1JF/Screenshot-x-Drip-20190525-150828.png' border='0' alt='Screenshot-x-Drip-20190525-150828'/></a>

**Comment by dwallersv** [comment] 2019-06-01 02:59
This works for me... Thanks a ton! There are always trade-offs, though... Looks like it doesn't read and process history, so if you're out of range, those readings will just be missing when you come back in range. Hopefully this can get fixed in the OB1 collector now that we can make it work with the new Samsung firmware.

**Comment by davide1985** [comment] 2019-06-02 10:03
I have tried these settings with dexcom g5 and samsung s10 but since I have been using them I have found values ​​very different from those of the capillary test. With my mobile these settings do not work well ..

**Comment by opasha** [comment] 2019-06-02 18:01
@davide1985, I agree with you, which is why you must callibrate with glucometer at least once - my readings are 100% within range of finger sticks.

One setting that messes everything up I just realized is:

Less common settings/Advanced Calibration/Automatic Calibration. This must be turned off. I was having the same issues where my readings would get away from my initial calibration about 20-30 mg/dL off when this setting was on.

I have corrected my post above to show this.

**Comment by opasha** [comment] 2019-06-02 19:44
Just showing you guys an update with my current settings listed above. It's been almost 11 days since my first calibration with these settings. I checked my sugar with finger stick using freestyle freedom lite glucometer (still the best in the business in my opinion), and it read 112. Here's my current reading below with xdrip+ latest beta.

<a href='https://postimg.cc/GBv25VMH' target='_blank'><img src='https://i.postimg.cc/GBv25VMH/Screenshot-x-Drip-20190602-154215.png' border='0' alt='Screenshot-x-Drip-20190602-154215'/></a>

**Comment by Fiebererdi** [comment] 2019-06-12 12:19
I will test it for Honor 9 lite with Android 9, because with OB1 collector i losing signal very often.

**Comment by pimeys** [comment] 2019-06-20 21:41
I got an announcement for LineageOS 16, which is their version from Pie for my Xiaomi Mi Mix 2. I'm currently using G5 amd will continue using it for the upcoming year. Does anybody experience problems eith the G5 native mode and Pie?

**Comment by drgymnast** [comment] 2020-01-24 04:29
I wonder if this works with the finow-q1-pro watch with g6

**Comment by Navid200** [comment] 2021-02-21 02:17
Thanks for the info.  Can we close this as an issue?  The information can still be accessed even if the issue is closed.
But, leaving it as an open issue suggests that action needs to be taken by the support team.

**Closed** 2021-02-21 02:20 UTC
