### ISSUE TITLE
Strikethrough in Alert List doesn't work correctly

### ISSUE THREAD

**Issue by Hexonium** [NightscoutFoundation/xDrip#888] opened 2019-05-23 10:21 UTC
If an alert is disabled in the Alert List it is supposed to become strikethrough. However, in some cases, the strikethrough also appear on other alerts. In the example below, only the 65 and 77 alerts are really disabled.

![Screenshot_20190523-180855_xDrip+](https://user-images.githubusercontent.com/34622676/58245515-8bbd3280-7d87-11e9-9693-84ae34848b9e.jpg)

**Comment by Navid200** [comment] 2021-02-12 16:12
@Hexonium Is this problem still present, or has it been resolved with more recent releases?
Thanks

**Comment by Hexonium** [comment] 2021-02-12 16:32
Still present in the latest version of the nightly channel

**Comment by Navid200** [comment] 2021-02-12 16:35
I just tested this and cannot reproduce the issue.  Would you please provide more detail helping us see the issue while testing?

**Comment by Hexonium** [comment] 2021-02-12 16:41
I wasn't able to identify a pattern to reproduce the issue. Right now only one line is wrong (the 45), but sometimes there are more. What kind of details would be helpful to you?

![Screenshot_20210212-173829_xDrip+](https://user-images.githubusercontent.com/34622676/107795755-588bb580-6d59-11eb-94e8-82a00125bbe6.jpg)

**Comment by Navid200** [comment] 2021-02-12 16:46
If only one member of the community experiences a problem, it is highly unlikely that anyone would spent the time to address it.
If I can experience the problem first hand, I will be able to either come up with a work-around, or label this as a bug.
So, getting back to your question, can you figure out what you have to do to recreate the problem?

**Comment by Hexonium** [comment] 2021-02-12 16:49
I'll let you know if I find a way to recreate the problem.

**Comment by Navid200** [comment] 2021-02-26 20:32
Please reopen the issue when you figure out how to recreate the problem.
Thanks

**Closed by Navid200** 2021-02-26 20:32 UTC
