### ISSUE TITLE
Xdrip extreme noise problem

### ISSUE THREAD

**Issue by saifraidan** [NightscoutFoundation/xDrip#1133] opened 2019-12-16 07:54 UTC
Any one can help me  with  Xdrip extreme noise problem.
* xdrip + dexcom g5 +Samsung s9+ 
![Screenshot_20191216-114142_xDrip+](https://user-images.githubusercontent.com/48510437/70888831-a17f9700-1ffa-11ea-8fb5-acb5f8775462.jpg)

**Comment by Navid200** [comment] 2021-02-12 22:03
@saifraidan Would you please close this issue if your problem has been resolved?
Otherwise, can you confirm that the cause of the problem is xDrip?  You can demonstrate that by using xDrip versus the Dexcom app and showing different noise value between the two cases.  If the noise is caused by the sensor, there is nothing we can do with modifying xDrip to address it.
You can post in the xDrip support group on facebook.
https://www.facebook.com/groups/xDripG5
Thanks

**Comment by Navid200** [comment] 2021-02-27 02:00
Closing due to inactivity

**Closed by Navid200** 2021-02-27 02:00 UTC
