### ISSUE TITLE
FR: Last day to start, or restart, a sensor (effectively, transmitter expiry) notification

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1416] opened 2020-08-22 23:00 UTC
There are often posts in the facebook xDrip group complaining why they have started a new sensor and have waited for the 2-hour warm-up period to find out that it is not working.  
After inquiring, it turns out they have passed day 99.

It would be very helpful if xDrip issued a warning on day 80 (or any day in that vicinity) informing the user that day 99 will be the last day they can start or restart a sensor on the current transmitter.  
Such a reminder could help users plan the duration of the next sensors accordingly.  
It would also serve as a reminder that they need to plan for the next transmitter.

**Comment by davidmtml** [comment] 2020-09-03 18:22
This would be a great addition!

**Comment by tolot27** [comment] 2020-10-26 06:53
This is related to or duplicated by #1467.

**Comment by Navid200** [comment] 2020-10-26 12:43
It absolutely is not.
There are two completely different elements, transmitter and sensor, each with a different end of life as the manufacturer has imposed.

1- The manufacturer wants us to use a transmitter for only 110 days.  As a result, the transmitter will not start a brand new sensor on day 101.
2- The manufacturer wants us to use a sensor for only 10 days.  As a result, the transmitter stops the session on day 10 of the sensor even if it is a brand new transmitter with 100 more days left on it.  

Issue 1416 is about point 1.
Issue 1467 is about point 2.
Yes, they are both related to Dexcom.  And yes, they are both imposed by the transmitter as there is no intelligence in the sensor.  But, no they are not duplicates.  We, who use Dexcom, have to worry about dealing with both of those limitations.
Addressing issue 1416 will not resolve 1467.  And addressing issue 1467 will not resolve 1416.

**Comment by Navid200** [comment] 2020-10-26 12:44
> This is related to or duplicated by #1467.

It absolutely is not.
There are two completely different elements, transmitter and sensor, each with a different end of life as the manufacturer has imposed.

1- The manufacturer wants us to use a transmitter for only 110 days. As a result, the transmitter will not start a brand new sensor on day 101.
2- The manufacturer wants us to use a sensor for only 10 days. As a result, the transmitter stops the session on day 10 of the sensor even if it is a brand new transmitter with 100 more days left on it.

Issue 1416 is about point 1.
Issue 1467 is about point 2.
Yes, they are both related to Dexcom. And yes, they are both imposed by the transmitter as there is no intelligence in the sensor. But, no they are not duplicates. We, who use Dexcom, have to worry about dealing with both of those limitations.
Addressing issue 1416 will not resolve 1467. And addressing issue 1467 will not resolve 1416.

**Comment by tolot27** [comment] 2020-10-26 13:08
@Navid200 Hence, it is related to #1486, isn't it? I find the title confusing. For me it is more meaningful to warn about transmitter expiry rather than a notification about the last day to start a new sensor.
IMHO, it should not be possible to start a start a sensor at day 101. In that case, the reason should be displayed.

**Comment by Navid200** [comment] 2020-10-26 13:19
@tolot27 
What is 1486?  Isn't it just a copy of an existing issue?
If you like an issue to be renamed, you can suggest to rename it.  We can talk about that.  I have no problem renaming an issue if it will expedite its resolution.  That's all I want.
But, why start a new issue?  Don't we have enough issues already?

The fact of the matter is that the transmitter expires on day 110  (99 days and 23 hours and 59 minutes).  But, you cannot start a sensor past day 99 (and 23 hours and 59 minutes).  This may sound like nitpicking.  But, it is what we have to deal with.  AS I said, I am more than happy to edit the title if it makes more sense.  
Respectfully, would you please delete the new issue?

**Comment by Navid200** [comment] 2020-10-26 13:25
I may not have made myself clear.  
Let's say an alert is added to warn the user, on day 102, that the transmitter will expire in 8 days.  In my opinion such an alert is pointless because the user cannot take any action then as he/she has already lost the chance of taking any action (starting a new sensor) when day 100 started.

**Comment by tolot27** [comment] 2020-10-26 18:48
@Navid200

> What is 1486? Isn't it just a copy of an existing issue?

It looks like but not exactly. I searched around and found no identical issue at creation time. The intention of #1486 is to have a notification which reminds on replacing the transmitter if expired, before attaching an expired transmitter to a new sensor. That happened sometimes and I was asked to enhance xDrip.

> Let's say an alert is added to warn the user, on day 102, that the transmitter will expire in 8 days. In my opinion such an alert is pointless because the user cannot take any action then as he/she has already lost the chance of taking any action (starting a new sensor) when day 100 started.

I do not agree that it is pointless because it can remind you that you have to use a new transmitter the next time you have to place a new sensor. The Dexcom receiver also gives this warning four and two weeks before the transmitter expires.

> If you like an issue to be renamed, you can suggest to rename it. We can talk about that. I have no problem renaming an issue if it will expedite its resolution. That's all I want.
> But, why start a new issue? Don't we have enough issues already?

Indeed, we have enough issues, already. That's the reason why I started reading every issue, tag them with appropriate labels, link them, if possible or close it, if resolved already. 😃 It would be very helpful to have more volunteers doing this. Maybe, you can help screening related issues?

Regarding to this issue, it was not clear to me what the issue intent is. Now, I understand it: it is to maximize the transmitter usage time. That is some kind of optimization at the cost of sensor usage time. Personally, I would name it a notification rather than a warning because not every user is optimizing the transmitter usage time. And it should be possible to enable/disable this notification.

Possible new title: "notification about last day to start or restart a sensor"

> Respectfully, would you please delete the new issue?

I'm open for closing #1486. :wink: Do you still believe that it is a duplicate of this issue?

**Comment by Navid200** [comment] 2020-10-26 22:28
@tolot27 
If I can help in developing or supporting the development of xDrip, I would love to.  Please tell me how I can contribute.

I have a problem with "... at the cost of sensor usage time".  I can adjust how long I use a sensor on the positive side or the negative side.  I usually choose to replace a sensor on day 20.  But, I can replace it on day 19 or day 21 or 18 or 22.  The only limit to this is that at some point the sensor may become too noisy.  I have used a sensor up to day 30.  I know many others who have done the same.

It seems to me that 1416 and 1486 are both asking for a message to inform the user that the transmitter days are coming to an end.  It seems we are just debating about the best wording.

Dexcom transmitter will not stop working.  There is no control mechanism inside the transmitter that forces the transmitter to stop working.  
Rather, the control mechanism will refuse to start a sensor.  That is a fact.  And that is why some people get to use their transmitter for 109 days while some others get only 100 days from theirs (not because the transmitter stopped on day 100, but, because the transmitter refused to start a new sensor on day 100).  That difference (9 days) is almost 10% of the lifetime of something that I pay $300 for (in Canada).  That's not cheap.  I would like to help users get the most for their money.
The best wording would exactly represent the fact.  

I suggest that the wording should inform the user of the fact and let the user decide how to use that information, just to order a new transmitter, just to plan the timing of the sensors, or both.    
The fact is that the last day they can start a sensor is day 99.

**Comment by Navid200** [comment] 2020-10-27 14:10
Would it be possible to expedite 1118?
Clearing Dexcom queue
This will save a lot of time.  It often comes up (facebook group).  It would be so good to have this option.

**Comment by Navid200** [comment] 2021-02-26 13:16
Closing this as it is a nice-to-have, not a necessity.

**Closed** 2022-09-21 18:08 UTC
Labels: enhancement, device-dexcom, ux-notification
