### ISSUE TITLE
Contour plus one - measuring glucose over Bluetooth

### ISSUE THREAD

**Issue by mustang011** [NightscoutFoundation/xDrip#1076] opened 2019-11-02 18:48 UTC
The Contour plus one meter does not connect to Bluetooth with xdrip when measuring blood. Data from the meter is imported only when pairing the device. The signal for measuring sugar and taking the measurement from the meter works only immediately after pairing the device. The next day, xdrip no longer connects to xdrip. You need to pair the meter again.

**Comment by mk886714** [comment] 2019-11-03 09:20
I use a accucheck aviva connect that worked in the beginning without any problems.
after a xdrip update it is the same, after pairing works, after 1h must be paired again. I think it's the bluetooth settings of xdrip

**Comment by mk886714** [comment] 2019-11-03 09:25
I have not looked for the cause, because I only need BG to calibrate for the cgm

**Comment by mustang011** [comment] 2019-11-03 09:48
I use nightscout as an electronic diabetes diary and show these results to a doctor. The doctor looks at statistics, how many percent of time I am in a good range of sugars.

The more often I calibrate the sensor (I have FreeStyle Libre), the xdrip shows results closer to those of a blood test. The sensor still shows large discrepancies for other ranges (differently for 50 mg / dl, 120mg / dl, 180mg / dl, 250 mg / dl). I calibrate / measure sugar with a glucometer 3-4 times a day. When I feel weak, I increase the number of blood measurements to 6-11 times a day.

**Comment by Navid200** [comment] 2021-02-13 21:27
@mustang011 Would you please close this issue if your questions have been answered.
If not, you can try the facebook group or the Gitter room.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by mustang011** [comment] 2021-02-13 21:43
Ok.

**Closed** 2021-02-13 21:43 UTC
