### ISSUE TITLE
Play Store availability?

### ISSUE THREAD

**Issue by Maxr1998** [NightscoutFoundation/xDrip#693] opened 2018-11-27 10:14 UTC
It seems xDrip+ isn't available on the Google Play Store, which means phones with Android for Work/Android Enterprise policies can't install it, since installing from external sources isn't allowed for them - thus are there any plans to submit xDrip to Google Play?

**Comment by zackallan** [comment] 2018-11-28 14:45
Thanks for bringing up this request. Having xDrip+ available on the Google Play Store would be great. This would really simplify the installation process and make xDrip+ more accessible. Furthermore the app could update automatically.

**Comment by castdoom** [comment] 2018-11-28 15:38
i think its because of costs and the constant "brilliant" updates wouldny be so easy through google play. there may also be legal issues with it being used in a medical way.

im sure if it was easy enough it would be there already unfortunately

**Comment by jamorham** [comment] 2018-11-28 16:02
Google play store apps are subject to many restrictions, for example it is a requirement to target the latest sdk versions/libraries even though that will likely break the app which is why I don't do it.

An app can't send text messages (used for Emergency Message feature) unless it is a default messaging app or assistant app.

There are a load of other similar issues and some where google are demonstrably wrong about their implementations and other situations where they haven't considered our use case when forming policy.
 
Depending on how they implement the rules, it may be possible to do something, for example within the "unreleased apps" section - I will investigate this and discuss with the foundation.

**Comment by jwoglom** [comment] 2018-11-28 16:50
@jamorham I was under the naive assumption that the reason why xDrip wasn't in the Play Store had to do with US FDA restrictions about mobile apps which interact with health devices, which would prevent Google from approving the app. The FDA says it may "exercise enforcement discretion" on:

"Mobile apps that allows a user to collect, log, track and trend data such as blood glucose, blood pressure, heart rate, weight or other data from a device to eventually share with a heath care provider, or upload it to an online (cloud) database, personal or electronic health record."

I could be totally wrong though -- Google might not enforce this or xDrip may not technically fall under these rules. 

As for submitting an unreleased app to the Play Store, which might bypass the previous restrictions if Google chose to enforce them: https://support.google.com/googleplay/android-developer/answer/3131213?hl=en

**Comment by Maxr1998** [comment] 2018-11-28 16:58
@jamorham thanks a lot for the response and for your willingness to discuss this issues with the foundation.
I understand your concerns, I'm an Android developer myself and am also annoyed by some of the policies Google enforces on us devs. Still, Play Store availability would be a huge plus for my dad, as he can't install xDrip on his new work phone while it's not on Google Play. Would it for example be possible to strip out the emergency feature on the Google Play version only? About the targetApi, what are the specific issues that happen with the new APIs? I'd be ready to help and test wherever I can.

**Comment by sodesignberlin** [comment] 2018-11-28 17:42
To be honest: I realy give a s… on Google and its proprietary Store. Iam fin with the excelent updates policy and avalability on github.

But at this point I would like to jump in with another question:
Why not going to make xdrip available in [F-Droid](https://f-droid.org/)?
Xdrip is opensource anyway and in my opinion this woud be the by far better place be (on the side of the "good guys" ;-) Of course there are some other restrictions to meet there (requirements for FOSS software…) but I would appreciate this step.

**Comment by IzzySoft** [comment] 2019-06-24 14:30
Some show-stoppers for F-Droid inclusion can be [found here](https://gitlab.com/fdroid/rfp/issues/1001#note_177122694): GMS, Firebase and Crashlytics are not acceptable. So this would need a FOSS flavor. What are the chances for that, @jamorham?

**Comment by jamorham** [comment] 2019-06-24 15:13
I don't really see the advantage to users of providing a stripped down version to meet various app store restrictions. Standard side-loading seems very efficient.

**Comment by IzzySoft** [comment] 2019-06-24 15:51
@jamorham please don't get me wrong with what I'm saying now, this is just my personal stanza: I see something **very** wrong if an app that deals with quite personal and sensible data contains trackers like Crashlytics or Firebase. Not because I don't trust the developer of the app – but can you guarantee what those modules upload and, more important, what they do not touch? They are closed source, so you can't look inside. Which is one reason why "tin foils like me" wouldn't dare using the app: we don't want our data ending up "there". So I very clearly see an advantage to that "stripping down" :wink:

Again, just to make sure: no offense meant! Just letting you know that there's a group of users who… well, no need to explain further I guess 😄

**Comment by mk886714** [comment] 2019-06-24 16:09
Ich denke diese Debatte ist überflüssig ich nutze oder ich nutze nicht! Wenn Daten ausgelesen werden ist das für jeden Endnutzer sein eigenes Risiko was ich bei github runterlade ist ebenso mein Risiko! Also wer meine Daten brauchen kann viel spass mit all dem Müll von meinem Handy

**Comment by IzzySoft** [comment] 2019-06-24 16:27
@mk886714 it might be obsolete for you (so feel free to ignore it). That doesn't mean nobody else cares :wink:

**Comment by jamorham** [comment] 2019-06-24 20:33
@IzzySoft I do take privacy pretty seriously and xDrip has lots of of features to support this. Crashlytics can be disabled via a preference option. xDrip opts out of android app backups and xDrip sync is protected with symmetric encryption where the key is exchanged out of band.  No registration is required for anything and the app will run fine without network access and/or google play services.

If you are still concerned, I think your best bet is to use something like "No root firewall" - With this you can completely block network access for specific apps/destinations. I have used this to totally lock down android on discount chinese import phones which did a lot of bad stuff - like installing adware randomly and who knows what else.  If you think google could be hostile, collecting data beyond which they disclose in their apis then you could treat your phone the same way.

**Comment by IzzySoft** [comment] 2019-06-28 06:43
Thanks for the additional details, @jamorham! And no offense meant to you (I fully believe you with "can be disabled" and all, and appreciate it) – but thing is, you cannot look inside the Crashlytics (or other proprietary) libraries as they are not "open". So while I'm confident *your* code works as described, I'm not sure about those proprietary components.

For me personally, I could of course block the app's access to the net (I usually root my devices even before unboxing, so I had the tools at hand – in my case, AFWall+ does that part fine). But the "average Joe" would feel overstrained just to think about such measures; others cannot use this approach as their devices are not rooted, and the no-root solutions cannot be applied if they need VPN for other means.

Options I could think of would be replacing the proprietary things by FOSS alternatives – like ACRA for crash reporting, etc. (I'm no Android dev, so I don't know what tools exactly to recommend for with part – I don't even know which areas you'd need covered that require e.g. GMS or Firebase). And I of course cannot tell how much effort it would be to "switch" (or providing a FOSS branch which doesn't have those libraries but then lacks the associated features, what you called the "stripped-down version"). I'm just pointing out what would be needed to get the app into F-Droid, and being on that road also makes tin-foils happy :smiley:

**Comment by jamorham** [comment] 2019-06-28 08:28
@IzzySoft regarding the existing option to disable Crashlytics: with that preference option in place, the component is never instantiated at all. I'm not aware of any way the library could become active in those circumstances.

**Comment by IzzySoft** [comment] 2019-06-28 15:55
Thanks, @jamorham – I'll take your word for it. Still, the library is there inside the APK, and thus will trigger scanners like Exodus Privacy or Appbrain. This results in the app being tagged "trackers inside", which will continue making people suspicious. It's a vicious thing.

I'm not pressing for it; I've brought up the concerns I see and you answered them, I'm not the one making (or forcing) a decision here. Guess the majority is fine if these facts are just summed up in the app's description…

Thanks for your patience with my arguments! Should you some day decide to provide the tin-foil minority with a FOSS variant, please let me know and I gladly assist in getting that to F-Droid. Until then, all the best!

**Comment by jeromecc** [comment] 2020-01-09 04:39
> I don't really see the advantage to users of providing a stripped down version to meet various app store restrictions. Standard side-loading seems very efficient.

Hi!
How are xDrip users warned when a new version becomes available (for instance, after a serious bug is discovered and fixed)?
I used to contribute to the development of a free software desktop Electronic Health Record in which I discovered a nasty weight conversion bug between grams and kilograms that could have tricked the user into prescribing the wrong posology. I was glad to have a .deb package repository that would propose an upgrade if the user updated his package list AND a url linking a text file (no tracker, no logs) containing the version that was checked at every startup and would trigger a popup suggesting to update ASAP...
Thank you.

**Comment by MasterPlexus** [comment] 2020-01-09 09:11
@jeromecc , you can check the source of xDrip (function checkForAnUpdate in https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/UpdateActivity.java how xDrip mades its internal check if an Update is avalible. Within xDrip it is a preference setting if and what should be checked (stable, nightlys and so on). This has nothing to do with a deb-package (as also this say nothing which language is used in your deb-Package), but maybe you can understand how it works, and use it accordingly. But anyway, normaly a deb-package should be provided from a repository, where you also can mark a update as an security-issue, so the repository-handler will act systematically due to that.

**Comment by Navid200** [comment] 2021-02-26 18:26
This thread contains lots of useful info.  We can still access it, and even add more comments to it, even when closed.
So, I hope no one minds my closing it.

**Closed by Navid200** 2021-02-26 18:26 UTC

**Comment by tolot27** [comment] 2021-02-26 21:39
@IzzySoft Crashlytics was removed in one of the January nightly builds.

**Comment by IzzySoft** [comment] 2021-02-26 22:48
Confirmed that's gone, but my library scanner reports a.o.

* Google Maps API (`/com/google/android/gms/maps`): NonFreeDep,NonFreeNet
* Android Wear APIs (`/com/google/android/gms/wearable`): NonFreeDep
* Google Mobile Services (`/com/google/android/gms`): NonFreeDep
* Firebase (`/com/google/firebase`): NonFreeNet,NonFreeDep
* New Relic (`/com/newrelic/agent`): Tracking
* Locale (`/com/twofortyfouram/locale`): NonFreeAdd

I won't argue Locale (I'm using Tasker myself, which uses the same API). And Wear might be something different as well. But I won't understand what for Google Maps is needed here, or what a tracker like New Relic has to do in a health app. GMS and Firebase we already had talked about. No offense meant, but I wouldn't trust my health data to an app coming with such – and I'm not alone with that. Though admittedly the majority seems not to care even if it would broadcast to "overseas" as they've got "nothing to hide"…

Tracking and such aside, this also means the app is not fully FOSS anymore. I might sound as a moralizer with that – but especially when it comes to sensible data (and what is more sensible than health data?) we need to put the bar pretty high.

**Comment by tolot27** [comment] 2021-02-26 23:37
This issue was about Google Play Store availability. For F-Droid, please read and continue at #902.

**Comment by IzzySoft** [comment] 2021-02-26 23:54
It was you who pinged me about it here :wink: Apart from that, my comment was unrelated to the distribution channel. But no worries, I won't prolong that here (actually I already had unsubscribed from this issue, just your explicit ping brought me in again; so I'll unsubscribe again now to not be tempted :see_no_evil:)
