### ISSUE TITLE
WearOS App and Blucon not working correctly

### ISSUE THREAD

**Issue by nsghub** [NightscoutFoundation/xDrip#683] opened 2018-11-13 09:32 UTC
With the No 2nd nightly my LG W100 WearOS watch stopped working as a collector. It collects values from the blucon for a short period of time, maybe 10 minutes. Restarting the collector service helps for another 10 minutes.
There are no issues with the Oct 30th nightly.

Since there were some changes in the code regarding libre/blucon was there also a change in the WearOS app code?

**Comment by gregorybel** [comment] 2018-11-13 17:51
sorry to hear this but modifications done can't explain this.

we need find root cause.

are you willing to help?

best is to send logs, can you activate wear logs and ask to send it to me?

are you sure you updated wear app too? you need to delete and reinstall.

can you tell me which value is used for BT watchdog?

**Comment by gregorybel** [comment] 2018-11-19 17:57
good to know.
could you please close the issue then?

**Closed** 2018-11-19 21:43 UTC
