### ISSUE TITLE
Dexcom G6 Battery Status Packet Error - 8Q Transmitter

### ISSUE THREAD

**Issue by nickb24** [NightscoutFoundation/xDrip#1504] opened 2020-11-11 22:02 UTC
I've discovered an issue I'm facing with an 8Q Transmitter and the battery status. The problem I noticed is that the 'Transmitter Days', 'Resistance' and 'Temperature' values are all wrong. 

I've determined the issues to be in the way the battery status packet is handled. The problem lies in the file: com/eveningoutpost/dexdrip/G5Model/BatteryInfoRxMessage.java

I've modified the code as follows and fixed the issue:
[BatteryInfoRxMessage.txt](https://github.com/NightscoutFoundation/xDrip/files/5526927/BatteryInfoRxMessage.txt)

It looks like there are only 2 types of packet sizes, 10 and 12. Not sure when this was introduced but it must be with the new firefly transmitters since I was not having this problem up until I switched to a 8Q transmitter. 

Question that remains is why the resistance value is not being sent anymore. I tried looking for a reason but I can't find anything yet. 

I'm not familiar enough with the xDrip code to feel comfortable making a code pull request. I think it's better for someone who has more experience with the code to take a look and see how best to implement this change. It could be a G6 problem only.

**Comment by tolot27** [comment] 2020-11-11 22:30
Thanks for this investigation. Please can you also report the firmware version of the transmitter?

**Comment by nickb24** [comment] 2020-11-11 22:57
> Thanks for this investigation. Please can you also report the firmware version of the transmitter?

2.27.2.98

**Comment by emp-00** [comment] 2020-11-12 19:49
Is this a new firmware?! I'm currently on an 8J tx and 2.18.2.98 --- just yesterday I received a new tx => 8M (firmware yet unknown)

**Comment by nickb24** [comment] 2020-11-12 19:52
> Is this a new firmware?! I'm currently on an 8J tx and 2.18.2.98 --- just yesterday I received a new tx => 8M (firmware yet unknown)

I just received this transmitter last week. Manufacturing date of Sept 2020. Serial number is 8Q. I'm in Canada

**Comment by emp-00** [comment] 2020-11-12 20:19
My brandnew 8M has manufacturing date Oct 2020. 

AFAIK xdrip is for sure reading the firmware version and uses this information somehow in the code (saw this in an older issue discussion). Since your tx is working this means that 2.27.2.98 seems to be either implemented already or it behaves exactly the same as the other "Firefly" firmware versions. Good to know - now back to the topic, sorry for the distraction.

**Comment by nickb24** [comment] 2020-11-17 15:43
> My brandnew 8M has manufacturing date Oct 2020.
> 
> AFAIK xdrip is for sure reading the firmware version and uses this information somehow in the code (saw this in an older issue discussion). Since your tx is working this means that 2.27.2.98 seems to be either implemented already or it behaves exactly the same as the other "Firefly" firmware versions. Good to know - now back to the topic, sorry for the distraction.

I wouldn't consider it 'working' per se. I also have the following issue too #1279 . Started having the problem only after using the new transmitter.

**Comment by Navid200** [comment] 2021-02-05 16:42
I am using an 8Q transmitter now.
I knew that the resistance and temperature were wrong.  But, Voltage A and Voltage B look reasonable to me.  Are they wrong?

**Comment by nickb24** [comment] 2021-02-05 16:48
> Voltage A and Voltage B look reasonable to me. Are they wrong?

They should be correct.

**Comment by Navid200** [comment] 2021-06-16 12:45
The battery voltages are shown correctly now.  
The resistance is not being sent anymore by Firefly I believe.
The temperature is shown correctly too in the logs.  
I have an open PR that will also add the temperature to the system status page:  https://github.com/NightscoutFoundation/xDrip/pull/1722

I hope you don't mind if I remove the bug label.

**Comment by Navid200** [comment] 2021-08-07 15:07
@nickb24 
The temperature is also shown now (starting with 2021.07.10).
Can we close this issue please?

**Comment by Navid200** [comment] 2021-09-11 22:19
Thanks for reporting the issue and discovering the reason and advising the solution.
Since the problem is resolved now, I am closing this issue.
Please reopen if you believe it should stay open for some reason.

**Closed by Navid200** 2021-09-11 22:19 UTC
Labels: device-dexcom-transmitter
