### ISSUE TITLE
Anyone using G6 with Xdrip on Samsung S7 willing to share settings?

### ISSUE THREAD

**Issue by torent5** [NightscoutFoundation/xDrip#760] opened 2019-01-25 20:52 UTC
I just can`t set this all to work.
Would anyone please help me and send screen with all the settings?

**Comment by jamorham** [comment] 2019-01-30 10:35
Please update to the latest nightly and disable the `Minimize Scanning` option in the G5 Debug settings.

**Comment by dave1812** [comment] 2019-02-06 20:47
wow, that was a terse and incomplete answer for the OP.

**Comment by dave1812** [comment] 2019-02-19 21:16
download the 7/15/18 version, take the defaults and it should work.

**Comment by Navid200** [comment] 2021-02-07 20:18
@torent5 If the problem is resolved, would you please close the issue?
Thanks

**Comment by Navid200** [comment] 2021-02-16 19:58
Closing due to inactivity

**Closed by Navid200** 2021-02-16 19:58 UTC
