### ISSUE TITLE
Dexcom G6 Bluetooth Connection Lost for Samsung Galaxy Watch

### ISSUE THREAD

**Issue by ech89** [NightscoutFoundation/xDrip#778] opened 2019-02-11 14:11 UTC
Lost connection for 4 hours at this point, after the last reading. The app continues to say " G6 state isn't currently known. Next connection will update this" . I restarted the app after two hours and no change.
The Bluetooth Link in the settings shows disconnected and the Deep Sleeping Error count is at 10. 

Firmware version :1.6.5.25
xdrip version: 14fecb8-2019.01.10
          code: 1901102241

**Comment by parapenT1sta** [comment] 2019-02-13 11:47
Did you try with 31st build? I am having issues with the new versions with my Android Wear Ticwatch E.

**Comment by ech89** [comment] 2019-02-13 18:16
I will have to try with that build, thank you for the suggestion.

**Comment by Navid200** [comment] 2021-02-07 20:25
@ech89 If the problem is resolved, would you please close the issue?
Thanks

**Comment by Navid200** [comment] 2021-02-18 01:32
Closing due to inactivity

**Closed by Navid200** 2021-02-18 01:32 UTC
