### ISSUE TITLE
blucon - readings stopped

### ISSUE THREAD

**Issue by jo1st** [NightscoutFoundation/xDrip#324] opened 2018-03-01 11:22 UTC
using with blucon nightrider and libre. all the sudden dead, no readings coming, signal missed. battery status has a strike accross. battery status alway on 100%, never changed since a week of usage or maybe nine days.

**Comment by tzachi-dar** [comment] 2018-03-01 16:14
My guess is that the blucon battery is dead. Can you replace it with a new one?

**Comment by jo1st** [comment] 2018-03-02 08:20
I did change it a battery and I restarted my phone and I also deleted the
cache  and the preferences of xdrip and eventually started working again
but today with a brand new battery again stopped connecting missing signal
again I think there is a bug.  my phone is Samsung S7 Edge, Android 7.0

**Comment by emielmiddel** [comment] 2018-03-13 15:37
I have the exact same issue. First time after 2 hours of using BluCon, replaced battery, it seemed to work. Now battery is 3 days in, and it just stopped working at all. Battery status is Always 100% so this I don't trust.

**Comment by kretep** [comment] 2018-03-18 08:17
I also notice an interruption in readings sometimes, but until now this seems to fix itself after 1 or 2 hours. Not sure if the problem is with the bluetooth connection or the blucon reader not being able to read.

I have seen battery levels at 100%, 3% and 0%, but nothing in between; it seems to die quite suddenly after about 16 days for me.

**Comment by gregorybel** [comment] 2018-03-19 12:49
if not done, please enabled Agressive service Restart.
 if you have a wear SmartWatch, it could be the problem. try deleting xdrip data on Watch.
when battery at 3 percent, simply change it. Blucon doesn't deliver proper battery info.

**Comment by TheDiabeticWay** [comment] 2018-05-15 10:15
I'm getting this issue on Note 8 keeps losing signal, cannot trust it at all now! :-( It does come back on but keeps doing it. any slight moment can stop it working.

**Comment by Navid200** [comment] 2021-02-12 00:34
@jo1st Would you please close this issue if it has been resolved?
Otherwise, would you please update?
Thanks

**Comment by Navid200** [comment] 2021-02-20 23:23
Closing due to inactivity

**Closed by Navid200** 2021-02-20 23:23 UTC
