### ISSUE TITLE
Alarm sounds continuously 

### ISSUE THREAD

**Issue by neirfeno** [NightscoutFoundation/xDrip#1418] opened 2020-08-24 22:12 UTC
Previous versions of the app would sound the alarm once, then repeat it as specified by the `Re-raise every x minutes if unacknowledged` setting. Current version alarms continuously, clicking on the notification opens the app alarm still going, try and select the snooze time (alarm still blaring), and click snooze. This is extremely frustrating. Please, please, please put it back the way it was. I believe this is a bug because otherwise the re-raise setting is pointless.

**Comment by tolot27** [comment] 2020-09-25 20:19
Please can you provide the xDrip version you are using and the version as it worked before?

**Comment by Navid200** [comment] 2021-02-24 15:49
@neirfeno Would you please ask in the support channels if you are still experiencing this?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
If this was a bug, we would have heard about it from many others.
After you do that, if you find out that others are also facing the same issue, would you please update us here?
Thanks

**Comment by Navid200** [comment] 2021-03-12 02:52
Closing due to inactivity

**Comment by noctividus** [comment] 2021-10-30 16:54
I can verify that indeed this is still an issue.
![Screenshot_20211030-080209_xDrip+](https://user-images.githubusercontent.com/5158351/139542065-9104048f-ff46-44ae-82ed-abba21921cbf.jpg)
![Screenshot_20211030-090239_xDrip+](https://user-images.githubusercontent.com/5158351/139540592-b0dccae4-093e-42ec-90f8-a5da28f3d420.jpg)

**Comment by noctividus** [comment] 2021-10-30 16:55
Additionally, I can't answer the last version it "worked" it has never worked for me.

**Comment by tolot27** [comment] 2021-10-30 21:46
@neirfeno We still don't know which "Previous versions" you are referring to. I did not have this problem with any of the versions I'm using.
Maybe, this is related to the alert tone. I'm using the same alerts the Dexcom app is using. These alerts are very short like a "beep beep". Afterwards, nothing is heard until the alarm is reraised.

**Comment by noctividus** [comment] 2021-11-02 22:12
This has been an issue for every version I've used. That probably means the bug is linked to a phone (Samsung Galaxy S10) since I've only ever used xDrip on this phone. I'm on Android Version 11.

The bug is only present on the alert that has "Override Phone Silent" and "Force Speaker" enabled. The other alert I have only sounds once and respects the Re-raise time. Those two options probably do some pretty crazy stuff with respect to alerts, so I would look into that code. 

This is a key function, because I would like to place my phone in silent mode sometimes but still get a "super high" alert. However, I would like that to only beep beep once.

**Comment by noctividus** [comment] 2021-11-02 22:55
Alerts that override the silent mode utilize the PlayFile method-

https://github.com/NightscoutFoundation/xDrip/blob/38fee03be56da6ce9cbe90e08dbe8e4b651c6edc/wear/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/AlertPlayer.java#L297

I'm not sure why PlayFile utilizes MediaPlayer synchronously as opposed to Async, but it does. This file has only really been touched by @jamorham, so maybe he can answer that. Maybe just because alert tones are always local files and not streams.

There's no explicit call to setLooping(false). I would imagine that it defaults to false, but hey, my phone is looping that sound, so maybe throw a mediaPlayer.setLooping(false) in there after it's started.

**Comment by Navid200** [comment] 2021-11-03 00:47
I have force speaker and override silent mode enabled on all my alerts.
I have never experienced this problem.  I have used xDrip with Android 6, 8, 9, and 11 over the years, always with force speaker and override silent mode enabled.

**Comment by tolot27** [comment] 2021-11-04 22:25
> I'm not sure why PlayFile utilizes MediaPlayer synchronously as opposed to Async, but it does.

Declaring a method as `synchronized` has nothing to do how the MediaPlayer plays a file. It is only used to block other threads of xDrip accessing the method (`PlayFile` in this case) at the same time. For this particular case it is necessary because the global instance variable `mediaPlayer` is modified (object is released, nulled and created again). This should not be done by more than one thread at the same time.

Beside the method declaration, you are still right that MediaPlayer does not play the sound asynchronously.

> There's no explicit call to setLooping(false). I would imagine that it defaults to false, but hey, my phone is looping that sound, so maybe throw a mediaPlayer.setLooping(false) in there after it's started.

Please can you modify `PlayFile` according to https://stackoverflow.com/a/38821524/10373188 and test whether this solves your problem? The linked solution also enables asynchronous playback and releases the MediaPlayer on completion.

**Comment by Navid200** [comment] 2022-05-05 12:34
@noctividus Does the alarm still sound continuously with releases after April 12, 2022?

**Comment by noctividus** [comment] 2022-05-12 04:11
This appears to be fixed in later releases. Thanks for the support!

**Closed** 2022-05-12 04:14 UTC
Labels: bug, ux-notification

**Comment by pablodr350** [comment] 2022-07-24 17:38
Issue continues... I always used samsung phones, and always had this issue. Alarm repeat every 30 seconds up to you disable. Annoying, but a lot years with it....

**Comment by Navid200** [comment] 2022-07-24 17:49
@jamorham Is there any way you can reproduce this?

**Comment by jamorham** [comment] 2022-07-24 17:57
@pablodr350 please confirm xDrip version you are using? If not using the latest nightly version please try that to check the bug is still present, it may already be fixed. If bug still exists, please describe in detail what happens and what you think should happen instead.

**Comment by pablodr350** [comment] 2022-07-24 18:13
Hi, usually update the nightly version every 1/2 months, now withy 2122051915, but I will update to 2122072308 now.
This always happened with all samsungs I had... S5... S8... and now S20.

Alert level trigger, and if you don´t SNOOZE, it will continue to sound every 20-30 seconds continuosly (I know because sometimes I can´t touch it and I have to wait with this sound a lot time and even thinking to throw the phone :) ).

at this time, maybe not solution, but yes, desn´t works correctly.

thanks¡¡¡

**Comment by Navid200** [comment] 2022-07-24 18:58
@pablodr350 Why did you post in this closed issue?
This issue is very particular.  I assumed you had read this issue and understood every detail of it.

You can open a discussion and we will work with you to resolve it. 
If you don't snooze an alert, it is not supposed to stop on itself.

Would you please open a discussion using the following?  
https://github.com/NightscoutFoundation/xDrip/discussions
If it ends up being related to an existing issue, I will let you know.

**Comment by rustymonkey** [comment] 2023-09-07 18:22
fwiw, I have often experienced this problem as well (currently with version 23ccbd1-2023.07.16, but have seen this for years). The problem, however, seems to occur intermittently. i.e. alarms will often sound and only occur once and other times they'll repeat endlessly until I restart the device.

Here's what I see in the Error and Event List after the problem just occurred:
13:47 MissedReadingService. Aggressively restarting collector service due to lack of reception: backoff: 240
13:47 Other Alert.  BG Readings Missed (@13:47)
13:47 AlertPlayer. SnoozeOnNotificationDismissService called source = bg_missed_alerts shown for: 14 seconds
13:47 BluetoothHeadset. Bluetooth Audio disconnected: <headphone name and address>
13:48 Notifications. Blocking alarm raise as data older than: 17
13:48 Notifications. Blocking alarm raise as data older than: 17
13:48 Snoozed Alert. Snoozed until: 2023-09-07 14:48:27
13:48 Notifications. Blocking alarm raise as data older than: 17

But now, after restarting the device, the alarm has occurred again, but this time it only played once. :-/

The issue occurs for me on a Pixel 5a (xDrip is only used for remote monitoring/alarms, collecting data from a nightscout instance). Alarm config settings are below.

![Screenshot_20230907-141531](https://github.com/NightscoutFoundation/xDrip/assets/34991028/b14bcbfe-b9f4-47bf-a53a-274969aab6fb)
![Screenshot_20230907-141603](https://github.com/NightscoutFoundation/xDrip/assets/34991028/16c47218-2f62-4d78-9ae6-4e696a952049)
![Screenshot_20230907-141542](https://github.com/NightscoutFoundation/xDrip/assets/34991028/b3784b72-f446-40a0-875f-bfe3da3cc42e)

**Comment by Navid200** [comment] 2023-09-07 19:09
@rustymonkey The next time this happens, please record the sound and let us hear it.  Also, play the same alert once by tapping on test and let us hear that as well.

**Comment by thederekFawcett** [comment] 2024-02-13 01:14
![Screenshot_20240212_200211_xDrip+.jpg](https://github.com/NightscoutFoundation/xDrip/assets/11082623/049758c3-c26e-4d47-b480-d770ad4a0deb)

@Navid200 here's an event log from tonight. One minute goes by really fast when you're doing something else (like washing dishes or phone is on the other side of a room when in public). I've been using xDrip for the better part of a decade but have only used alerts for my daughter's phone since mid-2021.

Have used Alpha, Beta, & Stable versions. I think this problem has always existed for us. We're kind of used to it but it's also wildly infuriating sometimes.
Using custom Dexcom tones for all our alerts. Haven't tried with standard xDrip ones because of standardization and audio recognition. Happens with all set alerts (high, low, persistent, etc)

Side note: when it beeps, it does it at full volume 

Version: 3e86af7-2023.11.14
 Code: 2123111417

![Screenshot_20240212_201024_xDrip+.jpg](https://github.com/NightscoutFoundation/xDrip/assets/11082623/66864e33-5dbf-4768-9e41-d3ab75cf7d35)

![Screenshot_20240212_201058_xDrip+.jpg](https://github.com/NightscoutFoundation/xDrip/assets/11082623/8ada9190-507f-426f-933c-5d893186d512)

**Comment by Navid200** [comment] 2024-02-13 03:26
@thederekFawcett You have posted in an existing issue.  Why is that?

Can you tell us how to recreate this problem?
I don't have a Samsung.  I have Pixel, Motorola and Asus.  When I snooze an alert, it stops.

**Comment by thederekFawcett** [comment] 2024-02-13 11:18
> @thederekFawcett You have posted in an existing issue. Why is that?
> 
> Can you tell us how to recreate this problem? I don't have a Samsung. I have Pixel, Motorola and Asus. When I snooze an alert, it stops.

This is before you dismiss (I never snooze) it. The problem is when it first alarms.

**Comment by Navid200** [comment] 2024-02-13 14:06
@thederekFawcett Then, it has nothing to do with this issue, as explained in the very first post.

Open a discussion and explain what the problem is and we can talk about it.  Put yourself in the shoes of someone who has not experienced what you consider to be a problem.  And please don't continue the conversation here.

**Comment by noctividus** [comment] 2024-02-14 17:32
The thing is, AlertPlayer.java hasn't been touched in a long time. There
hasn't been any work done on this bug. Every time people report the
problem, the developers basically ask them to "prove it" like it isn't
happening to them. If they can't reproduce it, then it isn't happening.
Then, after an android update or something, it goes away for that
particular user. That's what happened to me. And to be clear, I never did
this:

https://github.com/NightscoutFoundation/xDrip/issues/1418#issuecomment-961479682

And, nobody ever experimented with changing how xDrip plays files. I didn't
want to set up an android dev environment and build, and since it had gone
away from my phone, it would have been more difficult to test. For the
record, this issue is back for me with my new phone, but I just can't deal
with this nonsense so I disable alerts in xDrip and use my omnipod dash app
to alert.

Until someone goes in and looks at how alert sounds are played and actually
finds a bug and fixes it, this issue is going to keep popping up. And, if
magical code fixes equate to closed tickets, then you're probably going to
get people trying to reopen tickets because the general rules are "look for
existing issues" first and then open a new ticket none exist. From this
thread, it's pretty crystal clear that this is an ongoing issue, and from
the commits, it's pretty clear that nothing has been done.

**Comment by Navid200** [comment] 2024-02-14 18:35
I believe you.

The only way I can fix a bug is to recreate it first.  Then, I can verify that it has been fixed before submitting it for review.
Even if I experience a bug myself and want to fix it, I need to include in my submission how to recreate the problem.  Otherwise, it will not be accepted.  And it shouldn't be.

I am looking at alert player a lot because I am working on several projects related to it.
There is nothing in there I can look at to fix a problem I don't see.

I have been using xDrip for almost 6 years now, 24/7, with Android 4 all the way up to 14.
I have never experienced an alert that kept going.
There is a lot that could vary from phone to phone.  I have never had a Samsung.

Everyone is welcome to contribute.  We are all volunteers.  If anyone can fix a problem, we encourage them to come forward and share their expertise.

**Comment by noctividus** [comment] 2024-02-14 19:12
The barrier to actually set up a dev environment is huge. Not only Java, Android and all the dependencies, but also just an environment to test the apk on a phone with simulated high/low values coming in. You guys seem to have that. What I can do is make a recommendation:

Throw this in there right below `mediaPlayer_=` new `MediaPlayer();`

`mediaPlayer_.setLooping(false);`

No guarantees...but it seems like a no-brainer to start going after this issue. If it doesn't break the player, I would say it can stay in beta branches for a while before getting merged up.

**Comment by Navid200** [comment] 2024-02-14 20:54
I will never just add something to the code because it "may" fix something.  The code is already too complicated.  
Even some developer don't appreciate that and keep adding kill switches.  And then, users say why is xDrip so complicated?!

I don't have a Samsung.  So, I cannot test this.  Developers who have Samsung have asked please tell us how to recreate this and no one has been able to explain it.
So, it is not like everyone who has Samsung is experiencing this.  There are many xDrip users who use Samsung.  This is not a problem they all experience.

It is very likely you have a setting or customization that is causing it.

**Comment by Navid200** [comment] 2024-08-13 11:44
If xDrip was looping, why would only Samsung play the looping and other phones ignore it?

If this is xDrip looping, it should show in logcat, right?
Can you set up an old Samsung phone to use the fake data source so that it would repeatedly trigger alerts?
https://navid200.github.io/xDrip/docs/FakeDataSource.html
Connect the phone to Android studio and bring up logcat.  Can you show in the logcat logs that it is xDrip mediaplayer that keeps asking the phone to repeat the sound?

**Comment by Navid200** [comment] 2024-08-13 12:00
We have already ser looping to false:  
https://github.com/NightscoutFoundation/xDrip/blob/f96d4e5ba282bf385dfc2ea8b070b39cb8b4303e/app/src/main/java/com/eveningoutpost/dexdrip/utilitymodels/AlertPlayer.java#L384  

I am open to suggestions other than buying a Samsung.  I would like to fix this.  How can I?

**Comment by Navid200** [comment] 2024-08-13 12:21
Has anyone experiencing this checked to see if there may be a Samsung setting like the one linked below that could be causing this behavior?
https://www.samsung.com/za/support/mobile-devices/how-do-i-set-up-repeat-notifications-for-messages-on-my-samsung-galaxy-smartphone/

**Comment by rustymonkey** [comment] 2024-08-13 13:10
I'm no longer using xDrip, but fyi, I was experiencing the issue on a Pixel 5a so it's probably not Samsung-specific.
