### ISSUE TITLE
No display after update to Android 10 

### ISSUE THREAD

**Issue by LavineDavid** [NightscoutFoundation/xDrip#1258] opened 2020-03-04 17:21 UTC
Using a Note9, FreeStyle Libre, and an MiaoMiao2.

Everything worked fine up until the update to Android 10.

According to the Event Log it is steadily collecting data, but nothing will display. It is has been like this for 2days.

I have updated to the latest nightly build.

Could the OOPAlgorithm be the source of the problem ? The phone's device maintenance is showing that it keeps crashing. If that is the problem, any chance that you can provide a link to download a fresh copy and I'll delete the one I have, reinstall the new copy.

Or is there something else that I'm missing?

Thanks in advance for any help you that you offer.

**Comment by LaNiSa2016** [comment] 2020-03-05 19:03
Try the Workflow witg stop Force

Settings-> Apps-> xDrip+ -> Force Stop

Restart Phone

Open xDrip

**Comment by Navid200** [comment] 2021-02-22 01:04
@LavineDavid A lot has changed since Android 10 was first released.  If the problem is resolved, would you please close this issue?
Please use the support channels to see what other users are doing in similar cases in the future.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment] 2021-03-05 20:19
Closing due to inactivity

**Closed by Navid200** 2021-03-05 20:19 UTC
