### ISSUE TITLE
Eversense CGM

### ISSUE THREAD

**Issue by xLevelster** [NightscoutFoundation/xDrip#677] opened 2018-11-07 15:03 UTC
I don't get any data when connceting the Eversense to xDrip, can anybody solve this problem?

**Comment by xLevelster** [comment] 2018-11-07 17:55
Hey thanks for your fast response. I am using the newest Eversense XL for 7 days now. I did not know that I have to patch the Eversense App, since I did not find anything about how to set it up, so I just used the newest xDrip Apk and the latest version of Eversense CGM from the PlayStore. How can I get that patched Eversense App?

**Comment by AdrianLxM** [comment] 2018-11-07 19:33
You do need the companion app "ESEL": https://github.com/AdrianLxM/Esel/

At the moment you do have to build it for yourself. As up until recently you had to be quite tech-savvy anyway (flash another operating system onto the phone) this was the way to go.

We are working on a more user-friendly option now that you don't have to root the phone anymore.

**Comment by BernhardRo** [comment] 2018-12-12 22:55
There is an easier solution availabe as well:
https://github.com/BernhardRo/Esel/tree/master/apk
This does not require a rooted phone and no compiling...

**Comment by tremor** [comment] 2019-01-03 08:37
@xLevelster: Can you provide some informations regarding the system itself? How long does the battery of the transmitter last? Is it easy to remove it (for snorkeling/diving) and attach again? How accurate is it? What  happens when you don't calibrate twice a day?

**Comment by xLevelster** [comment] 2019-01-03 11:04
Battery lasts up to 36 hours. It is very easy to remove because it is just sticked to your skin with an adhesive. For me it is super accurate. You won't get any readings after 2 hours when you don't calibrate.

**Comment by BernhardRo** [comment] 2019-01-04 20:04
Yes, the battery lasts for about 36h, but it takes only roughly 10 min to reload it. Therefore it is no problem to easily take it off every day (e.g. before taking a shower) and reload it. For me, this is even an advantage as my skin had problems with the 14 days of wearing a freestyle libre. With eversense my skin gets a break and a new plaster every day and with this I have no problems at all.
In terms of accuracy: the values are somehow noisy, but accurate.

**Comment by tremor** [comment] 2019-01-08 10:34
Can you fix it without a plaster with armband or 3d printed holder?

**Comment by xLevelster** [comment] 2019-01-08 12:37
> Can you fix it without a plaster with armband or 3d printed holder?

Yes not really necessary but that should work, depending on how good it stays over the sensor.

**Comment by tremor** [comment] 2019-01-08 20:37
Ich ask because I have to remove it on some days more than once when I go diving...

**Comment by BernhardRo** [comment] 2019-01-08 21:51
You can remove the transmitter as often as you want - thats no problem!
You can also try to fix it as you want - but it must really be placed above the sensor, otherwise the connection gets lost.

**Comment by hartlijn** [comment] 2019-01-16 20:50
@BernhardRo what are the requirements of the phone for your solution?

**Comment by BernhardRo** [comment] 2019-01-16 21:12
Android?  Try it, then your know it!  It is running on my phone.  I do not know about more requirements.

**Comment by Navid200** [comment] 2021-02-17 19:53
@xLevelster It seems your question has been answered.
Can we close this issue?
Thank

**Comment by BernhardRo** [comment] 2021-02-18 09:06
Yes, I think we can close it!

**Closed** 2021-02-18 12:17 UTC

**Comment by k0rtalian** [comment] 2022-07-01 16:17
> There is an easier solution availabe as well: https://github.com/BernhardRo/Esel/tree/master/apk This does not require a rooted phone and no compiling...



> There is an easier solution availabe as well: https://github.com/BernhardRo/Esel/tree/master/apk This does not require a rooted phone and no compiling...

So is the modded apk not being updated anymore. I can't log on with the modded apk.

**Comment by BernhardRo** [comment] 2022-07-01 16:28
Hello, there is a newer version available:
https://bitbucket.org/norbert_bitbucket1/hackingeversense/downloads/Eversense_CGM_v1.2.107_b2030_SAP.apk
Do you need the European version or the US version? The US version has not been updated as we are all located in Europe.

**Comment by jamorham** [comment] 2022-07-01 19:58
Out of interest, does the new xDrip collector source called `Companion` work with the standard app?

**Comment by EpsomD2** [comment] 2022-08-10 13:46
I had tried to follow your instructions @BernhardRo to edit and recompile the US version of the app, but when I recompile it is yielding an error.  I have both a US and EU account with eversense as the older version you made worked fine for me when I had the sensor with the 90 day life, but now that the 180 day sensor has been approved the old app didn't work.  Does the newer version you posted on Jul 1 work with the 180 day sensor?

**Comment by BernhardRo** [comment] 2022-08-12 14:39
@EpsomD2 : You can check out this here: https://bitbucket.org/norbert_bitbucket1/hackingeversense/downloads/Eversense_CGM_v7.1.1_b2104_SAP.apk

**Comment by EpsomD2** [comment] 2022-08-12 18:33
@BernhardRo, works perfectly!  Thank you.

**Comment by EpsomD2** [comment] 2024-10-28 22:50
@BernhardRo, I was implanted with the new Eversense 365 sensor/app and it doesn't work with ESEL.  I was wondering if you would be able to modify it to work or create a companion app like you had previously?  I tried using fill in missing data from eversensedms.com function, but it yields an error of "Link Expired".

Appreciate all your help keeping those of us with eversense going with xDrip.

The latest apk downloaded from the play store today can be found at this link.  https://afco.box.com/s/e13buxjyu8cuh1rs8iffbww10w18irki

**Comment by Navid200** [comment] 2024-10-28 23:13
Two years ago, an xDrip developer asked you guys if the xDrip companion app mode worked with the official app or not.
None of you responded.

Would you be so kind to respond considering you are using the xDrip repository to communicate with each other?

**Comment by BernhardRo** [comment] 2024-11-03 12:06
> @BernhardRo, I was implanted with the new Eversense 365 sensor/app and it doesn't work with ESEL. I was wondering if you would be able to modify it to work or create a companion app like you had previously? I tried using fill in missing data from eversensedms.com function, but it yields an error of "Link Expired".
> 
> Appreciate all your help keeping those of us with eversense going with xDrip.
> 
> The latest apk downloaded from the play store today can be found at this link. https://afco.box.com/s/e13buxjyu8cuh1rs8iffbww10w18irki

@EpsomD2: Regarding the eversensedms connection: have you provided your login as provided in the Eversense app in the Esel settings below? And regarding your new 365 sensor: I am not able to test it, as this new sensor is not yet available in Europe, but I have updated Esel to use the notification listener more generic. Can you try: https://github.com/BernhardRo/Esel/blob/master/apk/esel_303.apk with deactivated "Get data from patched Eversense App"

**Comment by BernhardRo** [comment] 2024-11-03 12:07
> Two years ago, an xDrip developer asked you guys if the xDrip companion app mode worked with the official app or not. None of you responded.
> 
> Would you be so kind to respond considering you are using the xDrip repository to communicate with each other?

I think you are referring to this recent discussion: https://github.com/NightscoutFoundation/xDrip/discussions/3290#discussioncomment-8120318

**Comment by Navid200** [comment] 2024-11-03 12:27
@BernhardRo Thanks for the reminder

Can I ask then does it (Companion App mode for Eversense) work?
Or is it still not working for the US version?

**Comment by BernhardRo** [comment] 2024-11-03 13:39
> @BernhardRo Thanks for the reminder
> 
> Can I ask then does it (Companion App mode for Eversense) work? Or is it still not working for the US version?

Well, I can not test the US version, but actually nobody complains - therefore I guess it is working.

**Comment by EpsomD2** [comment] 2024-11-04 03:27
@BernhardRo, I can confirm that the companion app has been working just fine along side the US version (prior to the upgrade to 365).  The way to make it work is to run the regular app, logged in as a US user, and run the companion app logged in as a Euro user.

**Comment by EpsomD2** [comment] 2024-11-04 03:31
> > @BernhardRo, I was implanted with the new Eversense 365 sensor/app and it doesn't work with ESEL. I was wondering if you would be able to modify it to work or create a companion app like you had previously? I tried using fill in missing data from eversensedms.com function, but it yields an error of "Link Expired".
> > Appreciate all your help keeping those of us with eversense going with xDrip.
> > The latest apk downloaded from the play store today can be found at this link. https://afco.box.com/s/e13buxjyu8cuh1rs8iffbww10w18irki
> 
> @EpsomD2: Regarding the eversensedms connection: have you provided your login as provided in the Eversense app in the Esel settings below? And regarding your new 365 sensor: I am not able to test it, as this new sensor is not yet available in Europe, but I have updated Esel to use the notification listener more generic. Can you try: https://github.com/BernhardRo/Esel/blob/master/apk/esel_303.apk with deactivated "Get data from patched Eversense App"

Yes, I am using the same login and pass as used in the app. It still gives the "Link Expired" message. 
I've updated to the latest version you posted and am waiting to see if it starts to pull data.

**Comment by EpsomD2** [comment] 2024-11-04 16:23
> > > @BernhardRo, I was implanted with the new Eversense 365 sensor/app and it doesn't work with ESEL. I was wondering if you would be able to modify it to work or create a companion app like you had previously? I tried using fill in missing data from eversensedms.com function, but it yields an error of "Link Expired".
> > > Appreciate all your help keeping those of us with eversense going with xDrip.
> > > The latest apk downloaded from the play store today can be found at this link. https://afco.box.com/s/e13buxjyu8cuh1rs8iffbww10w18irki
> > 
> > 
> > @EpsomD2: Regarding the eversensedms connection: have you provided your login as provided in the Eversense app in the Esel settings below? And regarding your new 365 sensor: I am not able to test it, as this new sensor is not yet available in Europe, but I have updated Esel to use the notification listener more generic. Can you try: https://github.com/BernhardRo/Esel/blob/master/apk/esel_303.apk with deactivated "Get data from patched Eversense App"
> 
> Yes, I am using the same login and pass as used in the app. It still gives the "Link Expired" message. I've updated to the latest version you posted and am waiting to see if it starts to pull data.

@BernhardRo, I can now confirm that the Esel is pulling data from the Eversense365 notifications, thank you.  It still does not connect to the website to fill in missing data.  Now it is yielding a new error code:
{"error":"invalid_grant","error_description":"Invalid Username","error_code":5003}  
Thinking about the steps I've had to take to get the companion app working in the past where I had to create a Euro login, I have a feeling that the issue is because in the US the website is https://us.eversensedms.com, can you per chance make a change for US users?

**Comment by BernhardRo** [comment] 2024-11-13 16:35
@EpsomD2 Can you try the latest update: https://github.com/BernhardRo/Esel/blob/dev_us/apk/esel_303_us.apk
This version provides new settings: Enable "Use US server us.eversensedms.com for backfill" in the preferences and check if it is able to fetch data via the API

**Comment by EpsomD2** [comment] 2024-11-13 18:33
> @EpsomD2 Can you try the latest update: https://github.com/BernhardRo/Esel/blob/dev_us/apk/esel_303_us.apk This version provides new settings: Enable "Use US server us.eversensedms.com for backfill" in the preferences and check if it is able to fetch data via the API

Works like a charm now!  Many thanks.

**Comment by halprewitt** [comment] 2024-12-22 00:44
@BernhardRo Using 303_us.apk and Enable "Use US server us.eversensedms.com for backfill" in the preferences. A problem if Enable "Fill missing data from eversensedms.com" causes an error of "Link Expired". Disable this option, and the Link Error will not appear.  A 2nd question, if sending to Nightscout with AAPSClient installed,  is Enabling "Send to AAPS and xDrip" necessary?

Thanks, hp

**Comment by BernhardRo** [comment] 2025-01-06 19:31
Hello, sorry for the late reply. 304 should work with Eversense 365. At least I got some positive response for it - I cannot test it as I do not have access to it (not yet available in Germany).  A debug value is only sent, if "Send constant value for debugging" is activated. This must be deactivated. Regarding "Link Expired": sometimes it takes some minutes until the login is successful. Have you tried to wait about ~20min? For reading data from the Eversense app, it needs access to the notifications. Esel asks for that at the initial start of the App.

**Comment by halprewitt** [comment] 2025-01-26 16:55
@BernhardRo and @EpsomD2 
I got Esel 3.04 for the 365 to send live readings to xDrip and glucodatahandler but stills failed sync, read or get missing data from us.eversensedms. Gives Warning: ["error":"invalid_grant"] every 5 mins and Error: ["Message":"Link Expired"] if I ask for a Read or Sync.   Esel has been running +12 hours.  Log in and password  to server are correct, and Auto Sync interval is set greater than 0.   Log and setting screen captures are attached. 

![Image](https://github.com/user-attachments/assets/5e31f54d-8bbf-4e61-8c11-1e03eb3350c4)
![Image](https://github.com/user-attachments/assets/86ecae6b-a5af-45b8-91d5-d1ed21d39dd7)

**Comment by Navid200** [comment] 2025-01-26 17:13
@halprewitt Does the official 365 app create notifications for readings?
Can you see the readings in an ongoing notification?
I would like us to provide coverage for the companion app mode.  That is something we can talk about here.

If you want to talk about detecting code and how to create an unofficial app other than xDrip, please kindly have that conversation somewhere other than the xDrip repository.

We want to help diabetics by providing xDrip.  If xDrip cannot help, which is understandable in some cases, there may be alternatives.  But, we need to use this repository for xDrip only.

**Comment by halprewitt** [comment] 2025-01-26 17:27
@Navid200  Yes the 365 app uses notifications. I am using the companion mode to xDrip, getting there by the Esel app.

Is there another way to read live and history data into xDrip from Eversence 365? (other than using Esel).  That would be a tremendous & popular addition to xDrip.

**Comment by Navid200** [comment] 2025-01-26 17:33
@halprewitt 
 xDrip is not able to get readings from365 with Companion app mode because we have no added it yet and that is why I asked you if the official 365 app provides notifications on your phone or not.  If it does, we can add the ability.

I can also provide a test version of xDrip to you for testing.

**Comment by halprewitt** [comment] 2025-01-26 17:53
@Navid200 

Excellent.  How soon?  I am happy to help. I am a user of the 365 and a retired tech pioneer (google my name).

In addition to live data, need it to include events and option to backfill some numbers of hours/days from their servers (have US and EU ones).

Thanks, hp

**Comment by Navid200** [comment] 2025-01-26 18:29
@halprewitt I was going to provide it to you right now until I saw your post.  Are you saying there is a non-US option of the app?

**Comment by halprewitt** [comment] 2025-01-26 19:21
@Navid200 

No, only a choise of servers.  us.eversensedms.com or global.eversensedms.com.

**Comment by Navid200** [comment] 2025-01-26 20:32
@halprewitt 
I will explain how to test here:
If you are using xDrip, you should create a backup first so that you can restore after the test:
https://navid200.github.io/xDrip/docs/Backup-Database.html  

After you have created the backup, you will need to uninstall your xDrip.
Then, install this: https://navid200.github.io/xDrip/docs/Backup-Database.html  
This is for testing only and you should not distribute it.

You need to have the official Eversense 365 installed:
https://play.google.com/store/apps/details?id=com.senseonics.eversense365.us&pcampaignid=web_share 
Set it up to show your readings.

Now, in the test xDrip that you just installed, enable Companion App mode as explained here:
https://navid200.github.io/xDrip/docs/Follow/CompanionApp.html 

Does it show readings?   
Try enabling or disabling Companion Bluetooth.

**Comment by halprewitt** [comment] 2025-01-26 21:51
@Navid200

Works receiving live sensor data except 2 issues: (1) missing some of the 5 min data update and (2) not receiving events. such as the finger BL test, insulin unit/type and other events.  I switched on the Settings −> Less common settings −> Bluetooth Settings −> Companion Bluetooth and appears to have fixed (1) missed data but will continue to watch.  

Need option to include events and a way to backfill some numbers of hours/days from their servers.  Have a solution to these?

**Comment by Navid200** [comment] 2025-01-26 22:15
@halprewitt Would you please post a screenshot of xDrip with readings coming from Eversense 365?

**Comment by halprewitt** [comment] 2025-01-26 22:22
@Navid200 

The 365 and xDrip of the data.

![Image](https://github.com/user-attachments/assets/68193c24-500c-45ae-af89-3a63930864ab)
![Image](https://github.com/user-attachments/assets/7cf7242f-3bac-4894-bf48-5bac90c9c43a)

**Comment by Navid200** [comment] 2025-01-26 22:29
@halprewitt Blood glucose test does not go through Companion App.  At least, not now.  And this is not limited to Eversense.  It is a limitation of the xDrip Companion App mode.  
This will be merged and as soon as it is, you can switch to the Nightly release to get it to do what it does now.

We continue to improve xDrip when possible.  
Thanks for your help testing.

**Comment by halprewitt** [comment] 2025-01-26 22:58
@Navid200 

Eversense will be shortly releasing the 365 in the EU.  Because xDrip is getting the data from the Bluetooth feed, this should work in the EU as well. There will soon be +10,000 Eversence users who can use xDrip to get data for their watches and other apps.

Some apps do pass events (likely does not matter the type).  I think Esel does pass them.  
(1) This should not be difficult to add because the data is there.

(2) What about adding the option to backfill some numbers of hours/days from their servers? (This option is in Esel).

(3) Rather than include the fix as a Companion option, why not move it into the current 640/Eversense selection?

Will get the next night update to do more testing.  

Thank u for the work.

**Comment by Navid200** [comment] 2025-01-28 14:42
As of the 2025.01.28 release, Eversense 365 US can be used as a companion app with xDrip.
