### ISSUE TITLE
No calibration reset after libre sensor change

### ISSUE THREAD

**Issue by ANDREAPIPPI** [NightscoutFoundation/xDrip#241] opened 2017-12-15 14:10 UTC
Hi jamorham.
I use libre with bluereader and xdrip+ from 16 days, and probably for my mistake I didn't reset calibrations after changing the libre sensor, so results are not satisfying as they were with the previous one, due to the different response of the new sensor.
Is it possibile to restart calibration at this (any) point?
If yes, how?
If not, could it be possible to add this possibility in a next xdrip+ release?
And, BTW, is any place on the web where I can find instructions or a Help on how to use xdrip+, that I find extraordinary, but due to its many capabilities not so easy to use for an incompetent like me.
Sorry for my questions, but with libre, blureader and xdrip+ I found a new way of living my diabetes, and I would like to use all its features.
Thanks a lot, jamorham.
Andrea    :-)

**Comment by ANDREAPIPPI** [comment] 2017-12-15 15:20
Hmmm jamorham, sorry, I found it!
It was under "Stop sensor", that I didn't check before because I wanted to reset calibrations, not to stop the sensor.
But it is there, and works, so now I have a fresh, new calibration graph with only new data.
BTW, I have seen somewhere that calibration can be made more exact using complex curves, up to 9th order and over, using "**Least squares fitting**".
Do you know it?
The other question regarding the "help" is still on, please.    ;-)
Bye.
Andrea   :-)

**Comment by jamorham** [comment] 2017-12-15 22:47
When you change sensor you should use `Stop Sensor` and `Start Sensor`

If you have more information about calibration curves feel free to drop me an email my username at gmail.

There is some additional information about blucon here: https://github.com/gregorybel/xDrip-plus/wiki/How-to-use-Blukon-with-xdrip

Jon

**Comment by ANDREAPIPPI** [comment] 2017-12-15 22:56
Thanks a lot, Jon, appreciated..
Bye soon, I hope.
Andrea   :-)

**Comment by ANDREAPIPPI** [comment] 2017-12-16 22:55
Hi Jon.
Regarding best data fitting, I don't know what is your mathematics knowledge, but I found here: 
http://reference.wolfram.com/language/guide/CurveFittingAndApproximateFunctions.html)
something that looks interesting, given the many information on the problem and its solution.
Just for example, give a look in that page to the link "Related Tutorials--->Curve Fitting", here:
http://reference.wolfram.com/language/tutorial/CurveFitting.html
It looks clear even for a non-mathematic guy like me.
Hope this can be of some help.
Bye
Andrea      :-)

**Comment by jamorham** [comment] 2018-01-04 22:19
I understand about curve fitting but I was more interested in whether you know of any evidence that the Libre curve should be anything other than a linear regression - eg a straight line.

**Comment by ANDREAPIPPI** [comment] 2018-01-04 23:47
Hi Jon.
I'm using Libre from a full year, and I had trouble due to the impossibility to fit data on a straight line. Some time the sensor had different percentage variations between high and low values, when checked with a glucometer. E.g., I have the examnple of a discontinuous pergentage variation this summer, when the sensor gave -20mg/dl at real 80, +45 at real 150, and -32 at real 250
25. So the variation was -25%, +30%, and less than -13% at high values. This occurred for some days, but later the sensor had a total debacle, becoming so fluctuating that I had to change before ending time. This happened with some other sensor, and this is the reason why I was thinking about the usefullness of a curve instead of a line fitting.
BTW, just a suggestion to all Libre users here: due to the lack of affidability in the first hours, till to one full day, I install the new sensor one day before its life end, but withiur coupling it with the reader or the Bluereader. This works, the mad values that are "normal" after installation disappear  almost completely.
Moreover, I start again the xDrip+ calibration every 5 days, in order to be sure that old and different percent variation cannot affect the new checks.
My little cent.
Thank you for your attention, and Happy New Year.  Andrea   :-)

**Comment by RaabenFuchs** [comment] 2018-03-13 22:11
Hi,
this is a very important topic i was looking for, first,

at the beginning (i'm on bluereader, too) i didnt understand why to stop the sensor, either.. do you know what happens if you scan both sensors with nfc in the first day of new seonsor? :-) (or would it make sense to stop the old sensor automatically?)

the calibration thing is very interesting, i changed from glimp app, where i did a three point calibration on every new sonsor, which seemed very good to me (one calib @ ~100mg/dl, 2nd between 70and 90, third 130 to 150, if applicable)
i think it should be a curve, too. in my german translation it is even named "calibration curve" =)
So a few weeks ago i did five calibs on my new sensor and did a screenshot  of that "really nice curve". indeed i was really surprised, too, that it looks so cury.

theres also to say, that there seem to be changes on the libre sensors, too (maybe also to their internal calibration?) because newly the sensors show a straght line, after the self destructing 14d timer is over.
and as i always like to tell, i guess former sensors crashed when starting them at to high or to low bG values, (due to internal calib) which maybe fixed by abott now...

@jamorham i'm going mail you my calib curve screenshot
@ANDREAPIPPI "affidability " seems to be italian, maybe you know something about the glimp app? or how it works? as their site deebee.it is only italian

**Comment by RaabenFuchs** [comment] 2018-03-13 22:44
One more thought about this:

Think of your bodys reaction to high/low blood glucose:

-above 160, your liver filters sugar out, the glucose in fat could be higher than in blood
-below 70 your body begins regulation, sugar could be boosted from some kind of reserve to blood, which delays fat sugar, leaving it lower than bloods

in these cases, the calibration should be a  curve, but maybe linear between 80 to 150
although this screenshot doesnt fully underline it, i think cucrves are more natural than lines, this is what they tell you in university

**Comment by RaabenFuchs** [comment] 2018-03-14 15:39
ok, to relativate this a bit:

-linear is a good approximation anyway.
-and if you read the instruction of your bloodglucose meter, they normally say, there can be deviations about 10 till 20 %  ->  when you have a failure of 10% on the cgm this isn't to bad, because trends are more important than values, as the diabetic advisor would say
so don't panic

**Comment by tolot27** [comment] 2020-12-14 21:43
I'm closing this issue because the opening question was answered.

**Closed by tolot27** 2020-12-14 21:43 UTC
Labels: calibration, device-libre, question
