### ISSUE TITLE
numberwall_background not loaded on app start/phone reboot

### ISSUE THREAD

**Issue by zjedr** [NightscoutFoundation/xDrip#1077] opened 2019-11-02 22:34 UTC
numberwall_background is not loaded on reboot and is not displayed in configuration page after reboot.
I believe people using this feature are wanting to display medic alert information on their lock screen, therefore this is an important feature to fix. 
Found on Galaxy S9 running 9.0

**Comment by Navid200** [comment] 2021-02-12 19:58
@zjedr Would you please explain how this problem can be recreated?
Assume you are talking to someone who has never used xDrip.  Don't expect them to know what any acronym means.  Explain every single step required to recreate this problem.
Your post contains 3 lines.  You may need to create a post that contains 30.  Use as many lines as you need to help us recreate the problem.

Alternatively, if the issue has been resolved already, would you please close this issue?
Thanks

**Comment by zjedr** [comment] 2021-02-13 23:37
Number wall on lock screen does not display image after reboot.

Number wall on lock screen allows a background image to be display under the BG reading. 
The image is not loaded on the lock screen or in xdrip setting after your phone is rebooted and xdrip has started.

- number wall and image are set in Settings/xDrip+ Display Settings/Number Wall on Lock Screen
- set 'Use on Lock screen' on
- select 'Configure Number Wall', then select the folder icon and choose an image to display 

Lock screen now displays image and BG reading correctly until phone is rebooted.

After reboot (and xdrip starting) the background image is not displayed on the lock screen and is not shown in the 'Number Wall on Lock Screen' settings area.

This occurs on multiple phones including Samsung S9, Unihertz Atom and both Android 9 and 10, stable and nightly release.

Example image:-
![t1logo](https://user-images.githubusercontent.com/13398921/107864441-3d7f8980-6eb0-11eb-8cd1-8a73519bcb6f.png)

**Comment by Navid200** [comment] 2021-06-01 01:17
After I restart the phone, I can still see the image until xDrip starts.  As soon as xDrip starts, after a reboot, the image disappears.  
It is as if the image is stored in a cache that is cleared by xDrip upon a restart.

**Comment by jamorham** [comment] 2021-06-01 16:47
The numberwall is done using lockscreen wallpaper so it is quite likely the system will store this and display the old/previous one on reboot. I believe the issue being reported is that a customized background image is no longer applied after reboot.

Investigating this issue so far, I'm thinking it is that xDrip no longer has permission to load this image after reboot, that apps are granted external storage permission per reboot session maybe or possibly external storage isn't available at boot time. That would explain it I think. If that is the problem then I think I would instead. I will try to reproduce this to get a more exact idea of the cause of the problem.

**Comment by Navid200** [comment] 2021-06-02 12:13
@jamorham Could this be related?
There seems to be an issue with getInternalName.

![Untitled](https://user-images.githubusercontent.com/51497406/120477954-57b77780-c37a-11eb-8a9d-28b1f8f725ad.png)

**Comment by marciogranzotto** [comment] 2021-10-29 22:54
@Navid200 nope, that's because you have to install the Lombok plugin on android studio
https://projectlombok.org/setup/android

**Comment by Navid200** [comment] 2021-10-29 23:02
@marciogranzotto Right

Any idea what is causing this bug?

**Comment by marciogranzotto** [comment] 2021-10-29 23:04
I'm taking a look at the code now. I think the issue is that xDrip holds the path for the original image and for some reason it becomes null. I'm trying to get the chosen image and copy it to the app's internal storage. That way the app will always have a valid image file.

**Comment by marciogranzotto** [comment] 2021-10-30 00:18
![image](https://user-images.githubusercontent.com/11080704/139513345-27cbbf8f-fb74-41a8-adff-cc401a6810a6.png)
yeah! here's the issue

**Closed** 2021-11-17 15:41 UTC
Labels: bug, widget
