### ISSUE TITLE
nonmonoticSequenceException

### ISSUE THREAD

**Issue by yosepito** [NightscoutFoundation/xDrip#1294] opened 2020-04-08 16:07 UTC
The error in the log happens (I think) during the first days of a sensor (I'm using Libre with MM2). It seems to be related to BT disconnections but I'm unsure of this.
The initial calibration was done earlier than Xdrip requested it although the menu "initial calibration" was already available. It had received more than 3 data points.
The error says:
NonMonotonicSequenceException: org.apache.commons.math3.exception.NonMonotonicSequenceException: points 0 and 1 are not strictly increasing. 
Then it follows the last reading timestamp and, surprisingly, it compares the last reading with itself, instead of the previous one, thus the error.
Since it started to get disconnections from BT in spite of being the collector on my side, I suspect it might alter the BT connection (in those cases, it yields the error "receiving too much data"). But I'm unsure on this. It only happens eventually and randomly.

I'm using the version 7d97b62-2019.09.30 since I saw no new improvement relevant to me and I this version works perfectly in my Android 6 with MM2 and Libre.

It's perhaps a minor issue, but it deserves the attention in case it may affect to calibrations or anything else. I'm not an expert.

Thanks!

**Comment by Navid200** [comment] 2021-02-19 03:55
@yosepito Would you please close this issue if it has been resolved?
You can use the support channels to see what others have to say.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

You say initial calibration was done before xDrip requested it.  Why?  What makes you think that's not the cause of your problem?

**Comment by Navid200** [comment] 2021-03-01 01:52
Closing due to inactivity

**Closed by Navid200** 2021-03-01 01:52 UTC
