### ISSUE TITLE
Libre2 patched app suddenly stopped working

### ISSUE THREAD

**Issue by LubomirKovalcik** [NightscoutFoundation/xDrip#1227] opened 2020-02-05 07:58 UTC
Hello,

 I am using Libre2 patched app as source and it suddenly stopped working overnight.

I can still scan sensor with nfc and patched app and it is showing values. But there are no values received in xDrip. I have tried restarting collector and still no luck..

**Comment by MasterPlexus** [comment] 2020-02-05 08:33
In Librelink, did you have a red mark by the alerts?

Just try the following:
Go to android settings, apps, all apps, at top right the three dots, select system, scroll to "Bluetooth", and tap it, select memory, then tap button Clear memory  (not the cache button).
After that, check that the bluetooth is really active on your phone, go to patched LibreLink and rescan the sensor. wait for 5-10 minutes, and hope that the data transmition will restart...

If not, then it could be, that the Bluetooth stack of the Sensor was upset. Sometimes the Sensor starts to rework after half a day if you have luck.

Finaly, please mention which Phone did you use, wich android version, and wich xDrip version (this is maybe importand for documentation, and further investigation)

**Comment by juris2903** [comment] 2020-02-05 18:01
The same for me. Allready tryed everything... Still works with nfc, but not with xdrip+ Phone xiaomi redmi note8t android 9.0. Worked for me normaly only about three days then in liberlink patched app the red mark appeared and xdrip stoped to get mesures from sensor. I think problem is android 9.0 pie or bletooth problems in it...

**Comment by LubomirKovalcik** [comment] 2020-02-05 18:05
I am using Xiaomi Mi9 , android 9.0, xdrip 20191027.

Reinstalling both apps helped me to solve this problem.

**Comment by juris2903** [comment] 2020-02-05 18:29
Did you reinstall apps while the current sensor was active?

**Comment by Gyk3522** [comment] 2020-02-06 19:58
Good afternoon!
Yesterday we installed a new sensor. The sensor was activated by the Librelink application. After 60 minutes, no data was transferred to xDrip +. Error 120 appears. NFC reads data from the sensor. We use the phone Sumsung A50.

**Comment by Gyk3522** [comment] 2020-02-08 17:21
Hello!
put a new sensor the problem is gone.

**Comment by steve8x8** [comment] 2020-02-11 16:00
There is a way to find out whether the problem is with LibreLink (not) receiving one-minute (BLE) data, or with the inter-app connection LL->xDrip:
- connect the phone to a computer that has adb, abe (Android Backup Extractor), tar and sqlite installed
- `adb backup -f ll.ab -noapk com.freestylelibre.app.de`
- `abe unpack ll.ab ll.tar ""`
- `tar xf ll.tar`
- look for `sas.db` and, using sqlite3, extract the `currentReadings` table, then check the timestamps whether they stop early
This isn't for beginners though...
(NFC data go to the `realTimeReadings` and `historicReadings` tables.)

**Comment by keencave** [comment] 2020-02-20 16:39
Good idea. But this will only prove that the LL app is receiving readings from the sensor. An other user in that case found them in the sas.db but didnt receive any readings in xDrip. In that case the intent mechanism seemd to be broken somehow.

**Comment by Navid200** [comment] 2021-03-02 03:32
Closing the issue as it seems the original problem was resolved.
Please use the support channels before opening an issue.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Closed by Navid200** 2021-03-02 03:32 UTC
