### ISSUE TITLE
Feature Request: Guardian Connect Standalone from Medtronic

### ISSUE THREAD

**Issue by zuckerschneckchen** [NightscoutFoundation/xDrip#413] opened 2018-05-01 20:52 UTC
If it possible to became the data from the Guardian connect to xdrip, thanks for all.

**Comment by Navid200** [comment] 2021-02-12 01:15
@zuckerschneckchen Would you please close this issue if it is not valid any longer?
Otherwise, please update.
Thanks

**Comment by tolot27** [comment] 2021-02-17 19:25
Duplicate of #131

**Closed by tolot27** 2021-02-17 19:25 UTC
