### ISSUE TITLE
Calibration for Freestyle Libre2 not working any more

### ISSUE THREAD

**Issue by Laurent67** [NightscoutFoundation/xDrip#1371] opened 2020-06-23 18:51 UTC
Since two years I had been working with Freestyle Libre and was really happy with the performance. I did one calibration at every morning and this did really well work for me. Six weeks ago, I migrated to Freestyle Libre2, using Bluetooth. Unfortunately, I found that the calibration was fixed at a slope of 1.0! This does not correspond to my experience at all. As a measure of first help, I decreased the blood glucose targets to the lowest number allowed by AndroidAPS in order to get at least some better insulin administration. But the situation remains bad, with slopes until 1,6 not properly covered by xDrip+. 

xDrip should therefore offer the normal calibration, NOT FIXED at a slope of 1.0, at least as an option.

This is the calibration data of actual sensor
[FSL2-Kalibrierung - Sensor-2020-06-13.pdf](https://github.com/NightscoutFoundation/xDrip/files/4821320/FSL2-Kalibrierung.-.Sensor-2020-06-13.pdf)

Additional data for the calibration show clearly the slope SHOULD NOT BE fixed to 1!

![Screenshot_20200801-084816](https://user-images.githubusercontent.com/7566125/89339806-0cbbcd80-d69f-11ea-965b-257d6986bddc.png)
![Screenshot_20200802-101706](https://user-images.githubusercontent.com/7566125/89339813-0f1e2780-d69f-11ea-894f-e31b946e3222.png)

**Comment by yosepito** [comment] 2020-07-07 08:48
see #1350 
We have that problem too 

OOP cannot be calibrated unless you choose the complement Xdrip classic algorithm as the BG source in advanced calibrations options. At least, I may have more accurate data, although the problem of uploading wrong native data to NS persists

@tzachi-dar : please, is there any possibility to solve this?

**Comment by Brunchen** [comment] 2020-07-26 09:55
hello,

in my opinion all included calibration types in xdrip+ are static ones and wrong.

there is only one solution: include my suggested kinetic solution with an ordinary differential equation. with this equation everyone will achieve consistent values for libre data and ordinary glucose measurement.

look here:
https://github.com/NightscoutFoundation/xDrip/issues/1141#issue-541041401

very easy to implement in source code, but i don´t have these developer skills. 

it is a pity that nobody does this.

**Comment by tzachi-dar** [comment] 2020-08-30 11:20
We now have the possibility to calibrate libre 2 (using mm/blucon/bubble).
If anyone is interested to test this, please write here.

**Comment by Laurent67** [comment] 2020-08-30 16:38
I very much would so much appreciate the possibility to calibrate libre2. I will do anything for it, but tell what I can do.

**Comment by tzachi-dar** [comment] 2020-08-30 17:48
Please see instructions here:
https://gitter.im/LibreOOPAlgorithm/Lobby

**Comment by yosepito** [comment] 2020-08-31 08:47
Excellent news. Thanks a lot, @tzachi-dar 
Just a summary to check that I've understood well the procedure:
1) the first file in that link is your forked version of Xdrip (both files are downloaded with the same name, "app-debug.apk"). This is the Xdrip version we should run, ¿right? Please, could you clarify which is the base version for this fork? I use Amazfit watch to see my BGs and receive alerts, and would love to maintain it during the test.
2) the second app-debug.apk" file is OOP2. However, and this is what I could not understand well, you say we should install it but we shouldn't use OOP. What does this mean? Perhaps you may mean that we should **delete** the old OOP, install the new OOP2 and then, I do not know whether we should activate libre external algorithm or not. Can you clarify this step please?
3) You say it can be used with MM, bubble and blukon. Does this mean we should not use the Libre patched app? It means that we need a bridge. Is this right?

I've downloaded everything and wait for further clarifications to test this. I'm very interested. I would sacrifize simplicity of only wearing L2 for the sake of accuracy in calibrations. Now, I'm wearing a L2 that works well with libre patched app in the limit of +20 calibration most of times, that it is unable to mantain that when going low or high. Most of these times, callibration exceeds +25 or +30. I'm thinking the problem is me: 174cm and 62kg leave not much skin for the libre working well.

I will test this in parallel: a smarthpone with android 7 running your Xdrip version and OOP2 with MM2 and its calibrations, and another with android 9 and libre patched app.

thanks!

**Comment by yosepito** [comment] 2020-08-31 08:51
another question: what values will be uploaded to NS? So far, it uploaded Libre2 raw values. Will this method upload calibrated values? Thanks!

**Comment by yosepito** [comment] 2020-08-31 09:50
> 
> 
> Excellent news. Thanks a lot, @tzachi-dar
> Just a summary to check that I've understood well the procedure:
> 
>     1. the first file in that link is your forked version of Xdrip (both files are downloaded with the same name, "app-debug.apk"). This is the Xdrip version we should run, ¿right? Please, could you clarify which is the base version for this fork? I use Amazfit watch to see my BGs and receive alerts, and would love to maintain it during the test.
> 
>     2. the second app-debug.apk" file is OOP2. However, and this is what I could not understand well, you say we should install it but we shouldn't use OOP. What does this mean? Perhaps you may mean that we should **delete** the old OOP, install the new OOP2 and then, I do not know whether we should activate libre external algorithm or not. Can you clarify this step please?
> 
>     3. You say it can be used with MM, bubble and blukon. Does this mean we should not use the Libre patched app? It means that we need a bridge. Is this right?
> 
> 
> I've downloaded everything and wait for further clarifications to test this. I'm very interested. I would sacrifize simplicity of only wearing L2 for the sake of accuracy in calibrations. Now, I'm wearing a L2 that works well with libre patched app in the limit of +20 calibration most of times, that it is unable to mantain that when going low or high. Most of these times, callibration exceeds +25 or +30. I'm thinking the problem is me: 174cm and 62kg leave not much skin for the libre working well.
> 
> I will test this in parallel: a smarthpone with android 7 running your Xdrip version and OOP2 with MM2 and its calibrations, and another with android 9 and libre patched app.
> 
> thanks!

I answer myself: in the question (2), OOP2 SHOULD NOT BE ACTIVATED in Xdrip (uncheck enable external algorithm). Otherwise, it will deliver no BG readings. The raw data is different to the libre 2 raw data, since I'm comparing in parallel with two collectors. I will test it with calibrations today and will report tomorrow.

As a potential answer to (1): BG data readings are different to those stemming from the libre-2 patched. Since raw data is different, in the collector with OOP2 and tzachi-dar's Xdrip the BG table yields the calibrated values, so I guess it will upload these calibrated values to NS, which is perfect. Did not test that yet.

thanks @tzachi-dar for this, I really appreciate it.

**Comment by yosepito** [comment] 2020-09-04 15:51
my experience with this new OOP2

my update of running in different collectors a Libre2 patched app calibrated at its maximum (+20) and oop2 in another collector. I compared both values with finger pricks (aviva accu-chek), and the result is that OOP2 calibrated is innacurate. It needs to be re-calibrated constantly. For instance, a calibration early in the morning with a slope of 0.57 and intercept of 34.9, resulted in too high values. A new calibration during afternoon resulted in 0.73 and 8.8 for slope and intercept. The main problem it estimated a BG of 168 when it was 133, or a value of 55 when it was 70. I understand that the approach was to reverse the estimation, from libre2 BG readings to Libre1 raw values, and from these you applied the Xdrip algorithm. However, my guess is that it introduces the error twice, one from libre2 BG readings to raw values, and then from raw values to Xdrip BG values. The idea is very much appreciated, but the result is not fine yet. As I said above, I think the problem is the inconsistency of Libre2. Sometimes is within an acceptable range of +/- 5 or 10, and sometimes is well above +30. I found that, in my case, and with this current Libre2 sensor I wear, the calibration of +20 is a good estimation, although I know values are higher when BGs are higher than let's say 140 (tonight, it was 170, but Libre2+20 readings were no higher than 147). right now Libre2+20 readings are closer to finger pricks (BG finger pricks around 70). So my conclusion: Libre2 is close to finger pricks when BG is controlled at let's say 100 mg/dl or lower. But the error increases at values above 130-145 mg/dl, so **the offset range of -40/+20 in calibrations seems to be insufficient**. It is, in my experience, unable to reach high values because of the +20 limitation. 

The benefit of the new OOP2 calibrated values is that Xdrip follows highs and lows quicker than Libre2+20 (patched app). Libre2 is very slow to follow that. But OOP2 may require a calibration at least twice per day, an issues that does not happen with Libre1 calibrations. For those of you using this new OOP2: how close are your calibrations? Hope this reflection helps to improve the OOP2 calibration.  Thanks for your efforts!!!! I will keep on comparing values with a new libre2 in a week or two.

**Comment by Brunchen** [comment] 2020-09-04 18:26
@yosepito 
you may have to consider the dependency of dBG/dt and correlate these with the aviva accu check ones. try it.

**Comment by yosepito** [comment] 2020-09-04 18:45
@Brunchen 
agree and understand what you mean
just for clarification: all the calibrations were made under stable conditions, which means that 5min. delta was below 3mg/dl for at least 20 minutes

on the other hand, that is exactly what I meant when comparing calibration based on OOP2 vs. Libre-2 calibrations based on just the intercept. OOP2 is able to follow quick changes earlier and quicker than libre-2

was your comment about these issues?

**Comment by Brunchen** [comment] 2020-09-06 09:46
thank you, "stable" is necessary. thats what i meant.

**Comment by patanito** [comment] 2020-12-09 11:25
I think that the issue can be closed considering the latest developments made by @tzachi-dar regarding OOP2 and the Xdrip version developed.
Further instructions provided by @tzachi-dar here: [https://gitter.im/LibreOOPAlgorithm/Lobby?utm_source=notification&utm_medium=email&utm_campaign=unread-notifications](url) 
Summarized as follows (extracted from there):

Latest version of the oop2 can be found at: [](https://drive.google.com/uc?id=14QKSvS5gMWseXvbt_CjYqcD7QdT_2HRW&export=download )
latest version of xdrip can be found at: [](https://drive.google.com/uc?id=1hLE_mWYeC3S84p9nOZUck37lqJHFahhZ&export=download )

What one has to do is: 
1) install oop2 and see that it works (just open it). 
2) install xDrip. (you might have to backup your settings and DB, and uninstall the old version first.) 
3) When asked for the sensor choose libre bluetooth. 
4) Start the sensor. 
5) Scan the libre sensor with xDrip it will ask you if to connect to bluetooth streaming. Press yes. 
6) Scan the sensor again. 
7) after about 15 minutes you will be asked to enter a calibration. 


The sensor seems to wake up only once a minute to advertise. 
It has to be disconnected from a running patched LL app to start advertising. 
Please stop or deinstall that app. Then you should see the sensor in the BT scan. 
The UID is the company name with follwing serial number of the sensor.
Please ensure that any app which was prior connected to the sensor is not working. 
Otherwise it will interfere the xdrip BT connectivity as is permanently try to to connect to the L2 again.

Big thanks to all the developers for this

**Comment by Laurent67** [comment] 2020-12-09 11:47
Dear patanito,

does this mean, that this patch now went into the master of xDrip and I simply have to install to latest xDrip version together with oop2. If this is the case you can close the issue. 

But I still have to do the upgrade according to the instructions.

Lars

**Comment by patanito** [comment] 2020-12-09 12:12
@Laurent67 : no, it is not fully integrated. As mentioned above, the version of Xdrip you should install is the tzachi-dar version. You should do a backup of data and profile, uninstall Xdrip and install that version prior to perform those steps. See the conversation in gitter (see the link above)

I cannot close the issue, I have no privileges to do so.

**Comment by tolot27** [comment] 2020-12-09 12:24
This issue will be closed if #1524 gets merged.

**Comment by PhilTU** [comment] 2020-12-30 19:37
It was merged 10/12/20

**Comment by tolot27** [comment] 2020-12-30 22:19
Closing it because #1524 is merged, already.

**Comment by tolot27** [comment] 2020-12-30 22:19
@PhilTU Thanks for catching this up. 😄

**Closed by tolot27** 2020-12-30 22:19 UTC
Labels: bug, calibration, device-libre
